### PR TITLE
-webkit- missing from appearance

### PR DESCRIPTION
**Pull request by Eskyee**
added -webkit & resolved appearance problem in debug

### CODE REVIEW

**Comment by NicolasDorier** [comment]
You must not delete the original one or you are break for the browser supporting the appearance attribute.

**Comment by NicolasDorier** [comment]
don't close, just add the line you deleted back and update this PR.

**Comment by Eskyee** [comment]
I will update this evening,

**Comment by Eskyee** [comment]
updated reverted appearance tag , removed -webkit-
line 4187:  appearance: none;

**Comment by NicolasDorier** [comment]
you need to have both `appearance: none;` and `webkit-appearance`

**Comment by Eskyee** [comment]
updated the file is the same as the original now,

**Comment by lepipele** [comment]
We may also want to add .DS_Store to .gitignore in order to prevent those files from being added during commits, see: https://github.com/btcpayserver/btcpayserver/pull/43/files

**Comment by Eskyee** [comment]
yes I made this mistake with VS code ... commit

**Comment by lepipele** [comment]
Yeah, once they are part of commit you need another commit to modify `.gitignore` and delete the files already in repository. I'll jump on Slack to see what you wanna do with this ;)

**Comment by lepipele** [comment]
Resolved with #48

**Pull request closed without merging**
