### PR TITLE
check for enabled flag on translations 

### PR DESCRIPTION
**Pull request by Kukks**
So that we can have in-progress translations

### CODE REVIEW

**Comment by NicolasDorier** [comment]
what problem does it solve?

**Comment by Kukks** [comment]
So that we can get rid of the arabic PR and move the translations in there until we add rtl support

Also good for when we have translations not fully complete.

**Comment by Kukks** [comment]
Didn't know about that flag there. Good enough

**Comment by NicolasDorier** [comment]
Not a flag, just in the script I filter stuff that are not ready

**Pull request closed without merging**
