### PR TITLE
Bootstrap theming 

### PR DESCRIPTION
**Pull request by lepipele**
Adding support for changing default theme for both Bootstrap and CreativeStart

### CODE REVIEW

**Comment by NicolasDorier** [comment]
@rsandrade hey you LTC guys can create a bootstrap theme so we have something to play with? :D

**Comment by lepipele** [comment]
@NicolasDorier I'll reach out to you in the morning on details - we still need to do some migration `style` and `class` migrations so that theming is fully supported. If @rsandrade wants to join us for talk that would also work - defining how we approach stuff that's not done with bootstrap but with other style is definitely something we need to go over.

**Comment by lepipele** [comment]
OK @NicolasDorier - test and give it try - it should work well and both CSS files (bootstrap + creativestart) can now be replaced in policies.

**Comment by NicolasDorier** [comment]
Man I am so happy to not have to deal with what you are doing... testing :p

**Comment by NicolasDorier** [comment]
I suggest two things: 

* Rename the field "Creative Theme" to "Additional theme" because it might not be creative one right?
* Add a new tab in server (like "Theming"). Policies is not about design normally.

**Comment by NicolasDorier** [comment]
So is it possible to keep the font for the title, but small font keep the old font?

**Comment by lepipele** [comment]
@NicolasDorier ready to merge

**Pull request merged**
