### PR TITLE
Update PayButtonEnable.cshtml

### PR DESCRIPTION
**Pull request by sgracia13**
Editing the <button> tag to contain a cleaner title for a better UI experience.

### CODE REVIEW

**Comment by sgracia13** [comment]
Feel free to leave any comments. Open to discussing anything further you might need on this project in the future as well!

**Review by Zaxounette — CHANGES_REQUESTED** [review]
I think you misunderstood the issue's request.

In #1940 , Pav is specifically speaking of the lin N°3 aka ` ViewData.SetActivePageAndTitle(StoreNavPages.PayButton, "Please confirm you want to allow outside world to create invoices in your store (via API).");`

The string you changed needs to stay as is in my opinion, can you undo your change and modify the above string instead ?

**Comment by sgracia13** [comment]
ahh fair enough. Will do!

**Comment by sgracia13** [comment]
Created New separate PR.

**Comment by Zaxounette** [comment]
> Created New separate PR.

Then this one can be closed :)

**Pull request closed without merging**
