### PR TITLE
Add Argoneum

### PR DESCRIPTION
**Pull request by osnwt**
Add Argoneum support to NBitcoin, NBXplorer and BTCPayServer

These changes depend on NBitcoin ( see PR MetacoSA/NBitcoin#844) and NBXplorer (see PR https://github.com/dgarage/NBXplorer/pull/256) support. Runtime tests may fail unless both are updated.

### CODE REVIEW

**Comment by rockstardev** [comment]
@osnwt now ping for rebase here.

**Comment by osnwt** [comment]
> @osnwt now ping for rebase/fix here.

I've rebased it locally. The result is buildable, but perhaps not runnable since it depends on NBXplorer which has AGM support just merged in, but there was no new release published yet.

So I have to wait for new NBXplorer release, then rebase this and few more repositories which depend on it.

**Comment by osnwt** [comment]
Please understand that btcpayserver evolves, and I can rebase my changes on top of it. But by today it is not yet ready to support Argoneum.

It uses an official NBXplorer library. Last release of NBXplorer was [2.1.3](https://github.com/dgarage/NBXplorer/releases) dated May 24th, but Argoneum support was added on May 29th. So until new NBXplorer release is published, there is no sense to rebase this after each change. I am waiting for new NBXplorer release.

I can wait since we have BTCPayServer for AGM running in production for more than month. But this merge is required to switch to the official code, not privately built.

**Comment by osnwt** [comment]
Rebased on top of current master.
It also fixes a minor unrelated typo.

**Comment by osnwt** [comment]
Tests failed on external Poloniex Exchange API. Not a code issue.

**Comment by osnwt** [comment]
Rebased once again...

**Comment by NicolasDorier** [comment]
need rebase.

**Comment by osnwt** [comment]
Of course, it needs... for the 4th time. Because it conflicts with just added Chaincoin (PR #1674), while my PR #1504 still isn't...

**Comment by osnwt** [comment]
Rebased

**Comment by osnwt** [comment]
Are you kidding me? I rebased it few times, and every time it was ignored until conflicting changes merged. Even being trivial like version number, you asked me to rebase again and again.

Now it's made conflicted again.

Guys, I can't demand to merge this in (even if I would prefer to NOT support a dedicated fork for a running pay.argoneum.net system). But if you are NOT willing to merge this at all or will ask me to rebase again (with trivial version number change made much later after me) - just refuse the PR. Because in the form as it's been happening now during 2 months, it just looks like plain disrespect for me.

**Comment by bolatovumar** [comment]
THIS IS UNACCEPTABLE @astupidmoose CAN'T WAIT TO ACCEPT ARGONEUM AT SHITCOINCARDS.COM MERGE THIS NOW!!!!!211fwf1jh1!

**Comment by astupidmoose** [comment]
> THIS IS UNACCEPTABLE @astupidmoose CAN'T WAIT TO ACCEPT ARGONEUM AT SHITCOINCARDS.COM MERGE THIS NOW!!!!!211fwf1jh1!

Why you always tagging me? I don't know you.

**Comment by pavlenex** [comment]
@osnwt Please, have some patience. Altcoins as we said numerous times, are not our priority. We just had our biggest two releases yet and everyone are focused on it. You're free to fork off if you don't prefer how we prioritize PR's. I'm sure your PR will be merged once someone has time to dedicate to looking into it.

**Comment by osnwt** [comment]
> @osnwt I'm sure your PR will be merged once someone has time to dedicate to looking into it.

@pavlenex If you spend a minute to read the history of this PR, you would understand why I wrote that. Let me explain once again.

AGM is not my personal project. I was a contractor to get job done. It was formally finished 2 months ago. But I promised them to do all my best to include changes into official source, so they do not have to ask me every time to rebase private fork. I should stop doing it 2 months ago, but I always stick to my promises and continue pinging it unless have a final resolution here. My formal job is done, I can't track and rebase it forever.

1) This PR was submitted 2 months ago, it is a part of other changes including NBitcoin and NBXplorer, where changes were merged.
2) Since submitted, I was asked by 3 contributors (@rockstardev, @Kukks, @NicolasDorier) to rebase it since the base was changed. It was rebased literally in few minutes after requests.
3) After rebases it was checked and **approved twice** by @Kukks.
4) Last time rebase was requested because another altcoin was added to the end of list, so it conflicted. To resolve, one could just add a comma and include both parts, it was not a super difficult merge. Currently a version number is changed, but formally speaking this change conflicts again with this trivial and obvious change. It was ready to be merged, but it was not.

It's pretty fine for me if you refuse a PR, or if you tell me to wait a month or a year. Not ok is when **I was asked few times to rebase** again and again, and the **code was approved** by a contributor with write access, and still not merged (AGM, this https://github.com/btcpayserver/btcpayserver/pull/1504), but similar PR (another altcoin ChainCoin, https://github.com/btcpayserver/btcpayserver/pull/1636) **submitted almost 2 months later** was merged, making my PR trivially incompatible.

**Comment by Kukks** [comment]
We're not refusing the PR. I told you to rebase to let you know it would be needed after some updates. I approved the PR because I wanted to let others know that IMO it would not impact anything badly and seemed correct to me. I did not merge myself because I only use my repo write permission for critical bugs and very minor changes. Yes, it was unfortunate some other altcoin got merged before yours after being submitted after you but there was no favoritism at play here. 

So as @pavlenex said, be patient, this is not a priority for us but it will get merged eventually.

**Comment by Kukks** [comment]
@osnwt I disabled Argoneum on master because your custom rate provider went down. You will need to fix soon or I'll remove the related code within 1 month.

**Comment by astupidmoose** [comment]
@bolatovumar should fix it.

**Comment by osnwt** [comment]
> @osnwt I disabled Argoneum on master because your custom rate provider went down. You will need to fix soon or I'll remove the related code within 1 month.

Sorry, the rates provider was moved to another server. I already sent a request to fix it in DNS.

**Pull request merged**
