### PR TITLE
Improve currency selection

### LINKED ISSUE #4154: Improve Currency Selector
Expected Experience:
- Dropdown should appear without having to delete text first

Current Experience:
improve-payment-method-selector

### PR DESCRIPTION
**Pull request by dennisreimann**
Removes the current value on focus, so that the user gets to see the available options. If no selection or change is made, the value is reset to the previous value on blur.

Closes #4154.

https://user-images.githubusercontent.com/886/191958053-524f85f5-da6b-4782-944e-dae455e57ced.mp4

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Nice and simple workaround Concept ACK

**Review by dstrukt — APPROVED** [review]
Works exactly as discussed - beautiful!

tACK

**Comment by woutersamaey** [comment]
Just curious. Are all browsers behaving the same way? I'm not very familiar with this dropdown feature.

**Comment by dennisreimann** [comment]
@woutersamaey Yes, the display varies, but in general it works the same across browsers. See [datalist](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist) for reference.

**Pull request merged**
