### PR TITLE
I've added asterisk. Isn't that impressive?

### PR DESCRIPTION
**Pull request by rockstardev**

### CODE REVIEW

**Comment by rockstardev** [comment]
#589

**Comment by pavlenex** [comment]
NACK.

**Comment by Eskyee** [comment]
kool

**Comment by britttttk** [comment]
@Kukks can you review?

**Comment by Kukks** [comment]
why did you close? we could merge this @pavlenex  :P

**Comment by pavlenex** [comment]
I thought it was just for the show on the live-stream, sorry. Overlooked. Re-opened now.

**Comment by rockstardev** [comment]
@Kukks this is now in #593 done by @BenSanex right?

**Comment by Kukks** [comment]
No it's not, separate things

**Comment by BenSanex** [comment]
Yeah I left this one out of mine so we can just merge this and hopefully have no conflicts.

**Pull request merged**
