### PR TITLE
Attempting selenium test fix for CanUseLightningSatsFeature

### PR DESCRIPTION
**Pull request by rockstardev**
Swithcing to using WaitForElement and simplifying finding of alert message

### CODE REVIEW

**Review by Kukks — APPROVED** [review]

**Comment by dennisreimann** [comment]
My impression ist, that the WaitForElement shouldn't be necessary here – we'd have the same problem in many other places as well. Selenium is so tedious to work with. :(

**Comment by rockstardev** [comment]
@dennisreimann because of `FindByElement` flakiness I would always use `WaitForElement`. The priority is to get our pipeline to stop failing; right now we kinda started ignoring failing tests on PR which is quite problematic.

**Comment by dennisreimann** [comment]
I recently did quite a few rounds of fixing the tests, so that the Selenium ones aren't really flaky anymore from what I've seen.

**Comment by rockstardev** [comment]
> I recently did quite a few rounds of fixing the tests, so that the Selenium ones aren't really flaky anymore from what I've seen.

https://app.circleci.com/pipelines/github/btcpayserver/btcpayserver/4871/workflows/42482858-8e48-4631-b1b6-7d4bdd74a950/jobs/13989

@dennisreimann look at the open PRs and see how many of those are Selenium fails

**Comment by dennisreimann** [comment]
@rockstardev I don't think this is correct. Yes, tehre are many Selenium failures, but most of them are either older PRs, which do not include the recent fixes or they are cases where Selenium completely fails because of timeout issues. The latter seems to be a pipeline/CI issue, which sometimes occurs.

The remaining case is `CanUseLightningSatsFeature` related as far as I see: Even this one after rebasing master with this PR merged fails: https://app.circleci.com/pipelines/github/btcpayserver/btcpayserver/4879/workflows/6400b176-32f9-4971-8535-beb5f08fe42c/jobs/14016

**Pull request merged**
