### PR TITLE
Use Safe.Raw and Safe.Json instead of Html.Raw and the JsonHelper, move sanitization at the View level

### PR DESCRIPTION
**Pull request by NicolasDorier**
This PR is basically simplifying the code when we serialize JSON in our views.
On top of it, we make sure to use the Sanitizer in place where HTML can be output.

Please review and test the 2FA part, we were based on a old template impacted by [a bug](https://github.com/aspnet/Announcements/issues/285).

### CODE REVIEW

**Comment by pavlenex** [comment]
- [ ] Register and create a store
- [ ] Two factor test U2F
- [ ] Two factor test 2FA
- [ ] Two factor test U2F
- [ ] Connect a wallet
- [ ] Deploy LN
- [ ] LN public page test
- [ ] Create a payment request
- [ ] Payment test payment request
- [ ] PoS payment test
- [ ] Payment Button test
- [ ] BitPay Translator test

**Comment by NicolasDorier** [comment]
Thanks @pavlenex  can you pull and try again the U2F?

> Under Server Settings I see a weird service called - totoservice

Debug stuff.

**Comment by NicolasDorier** [comment]
@pavlenex fixed invoice, check again

**Comment by NicolasDorier** [comment]
I could not reproduce the problem with progress bar.

**Comment by pavlenex** [comment]
Confirm that U2F and invoice are fixed, can't reproduce the broken crowdfunding progress bar either now.

**Pull request merged**
