### PR TITLE
Fix app permissions

### PR DESCRIPTION
**Pull request by dennisreimann**
As pointed out by @nicolasdorier [here](https://github.com/btcpayserver/btcpayserver/pull/3205#issuecomment-999437555).

### CODE REVIEW

**Review by Kukks — CHANGES_REQUESTED** [review]
I don't think this is where it should be changed. but rather in `CookieAuthorizationHandler`.

For example:
* If `appId` is present, use `GetAppDataIfOwner` not `GetApp`
* if storeid is pre-set, che check that `app?.StoreDataId== storeId`

This would solve it globally instead of making sure we match it in every usage. Plus it allows us to reduce a call to the DB to re fetch the app data

**Comment by NicolasDorier** [comment]
Agree with @Kukks

**Comment by dennisreimann** [comment]
Ok, but I think there are cases in which GetOwnedApp wouldn't be the right fit if appId is present. How to distinguish those?

**Comment by dennisreimann** [comment]
@Kukks @NicolasDorier you were right, there are no occurrences where those permissions shouldn't be checked, so it is this simple one line change.

I've also added the fix for the login codes view here, which is needed to make the build work.

**Review by Kukks — CHANGES_REQUESTED** [review]
Please also address my second point in the example

**Pull request merged**
