### PR TITLE
PoS app to show POS view for easy setup

### LINKED ISSUE #5532: PoS app show QR code in settings for easy setup
### Discussed in https://github.com/btcpayserver/btcpayserver/discussions/5527

<div type='discussions-op-text'>

<sup>Originally posted by **ndeet** December  1, 2023</sup>
When setting up PoS terminals you link the PoS app on the home screen, as it contains a very long uuid it would be very helpful to display a QR code on the PoS settings page, so you can scan instead of type it. </div>

### PR DESCRIPTION
**Pull request by TChukwuleta**
Resolves #5532 by including a QR code on the PoS settings page for easy setup

### CODE REVIEW

**Review by dennisreimann — APPROVED** [review]
tACK

**Comment by dennisreimann** [comment]
@dstrukt @pavlenex Good to go from my side.

**Review by dstrukt — APPROVED** [review]
tACK - LGTM, I like the decision to tuck behind a button click

**Comment by dennisreimann** [comment]
In the wallet settings we have a Font Awesome icon for that, but it'd be nice if we could replace it with a custom one :)

grafik

**Comment by TChukwuleta** [comment]
I thought the same. But looking at the design doc, I decided to stick with the custom own too. Unless we want to include one similar to the font awesome icon

**Comment by dstrukt** [comment]
We should use the QR icon (over the Scan icon) I agree @pavlenex, and I think we use the non-font-awesome QR icon in the past, but I could be mistaken?

**Comment by TChukwuleta** [comment]
Hey @dstrukt  not sure I know of this icon. Could you point me to this?

**Comment by dennisreimann** [comment]
@dstrukt we don't have one yet, I also didn't find something in Figma. If there is a collection of icons I'm not aware of let me know and I could also get to #5485.

**Comment by dennisreimann** [comment]
Updated, thanks @dstrukt.

grafik

**Review by pavlenex — APPROVED** [review]
We can merge this one imo.

**Pull request merged**
