### PR TITLE
Remove CoinSwitch and Changelly

### LINKED ISSUE #1858: Changelly integration broken
When the changelly popup show up, No currency or amount seems like they were passed to it.

### PR DESCRIPTION
**Pull request by Kukks**
closes #1858

### CODE REVIEW

**Comment by BitcoinMitchell** [comment]
As stated [here](https://github.com/btcpayserver/btcpayserver/issues/1858#issuecomment-689838678), I'm asking you to refrain from removing CoinSwitch.

**Comment by Kukks** [comment]
> As stated [here](https://github.com/btcpayserver/btcpayserver/issues/1858#issuecomment-689838678), I'm asking you to refrain from removing CoinSwitch.

Would have been nice to state that BEFORE i made the code changes..

**Comment by BitcoinMitchell** [comment]
> > As stated [here](https://github.com/btcpayserver/btcpayserver/issues/1858#issuecomment-689838678), I'm asking you to refrain from removing CoinSwitch.
> 
> Would have been nice to state that BEFORE i made the code changes..

I did not see the issue or this PR before. No need to get mad at me... I'm just providing feedback. 

It's up to the team to decide if it's worth the upkeep, just saying that it seems to work for me (except for small transactions).

**Comment by Kukks** [comment]
closed in favor of #1900

**Pull request closed without merging**
