### PR TITLE
[WIP] Switch to .netcoreapp3.1

### PR DESCRIPTION
**Pull request by NicolasDorier**
Supersede https://github.com/btcpayserver/btcpayserver/pull/1070

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Ping @PinpointTownes you make breaking change on OpenIddict3.0? How can I fix this?

image

**Comment by PinpointTownes** [comment]
> Ping @PinpointTownes you make breaking change on OpenIddict3.0?

Yes. And it's pretty much the whole point of alpha packages (technically, SemVer also allows you to adopt breaking changes in all types of pre-releases, even RCs).

The `HandleAuthentication` API was removed recently - based on your feedback - and you can remove the calls safely, as your handlers are specific to a single `grant_type` and won't interfere with each other.

Regarding `EnableRequestCaching`, it was split into `EnableAuthorizationEndpointCaching` and `EnableLogoutEndpointCaching` (you very likely only need the first one in your case).

You'll also need a migration as the OpenIddict EF schema was updated to support the device code flow. I'm pretty sure we chatted about that on Skype last month.

That said, I see you have a pending PR to remove OpenIddict, so you should probably merge it before moving to 3.1, to save some time (there's no much point migrating to a new version of a lib' you're not going to use).

**Comment by NicolasDorier** [comment]
@PinpointTownes I don't plan on merging the removal of OpenIddict.

**Comment by PinpointTownes** [comment]
Roger. Feel free to ping me on Skype if you need help or hit any issue.

**Comment by NicolasDorier** [comment]
Something broke in openiddict on https://github.com/btcpayserver/btcpayserver/pull/1259 then this PR should be ready.

**Pull request merged**
