### PR TITLE
HTML lang setting and Head tags for POS and Crowdfund public pages

### PR DESCRIPTION
**Pull request by Nisaba**
Modifications allowing the user to improve the SEO of their pages

### CODE REVIEW

**Comment by dennisreimann** [comment]
You'll need to rebase against master :)

**Comment by Nisaba** [comment]
hmm, that seems to be the case especially since other modifications have been made in the meantime

**Comment by Kukks** [comment]
You need to start using dedicated branches for features

**Comment by Nisaba** [comment]
well, should be ok now...

**Comment by NicolasDorier** [comment]
ping @dennisreimann

**Comment by dennisreimann** [comment]
This PR needs a rebase first. I think it diverged from an outdated branch.

**Comment by Nisaba** [comment]
Hi,
@dennisreimann said to me:
	
"Despite that, we won't be merging any PR befor this one is done https://github.com/btcpayserver/btcpayserver/pull/5809


The Big Cleanup by NicolasDorier · Pull Request #5809 · btcpayserver/btcpayserver
I think it makes sense for you to wait until that one is on master and then you can rebase your PR."

So, what are the latest instructions?

**Comment by dstrukt** [comment]
Bumping this PR @dennisreimann

**Comment by dennisreimann** [comment]
As said above, this PR needs to get rebased on current master.

**Pull request closed without merging**
