### PR TITLE
Payment Requests: List view improvements

### PR DESCRIPTION
**Pull request by TChukwuleta**
#3872 

Improved Payment Requests List View fix

### CODE REVIEW

**Comment by myezanebo** [comment]
Help me please about how I withdraw my account.phone number 27 0825415835.

**Comment by pavlenex** [comment]
Thanks for picking up on this issue @TChukwuleta! 

It seems when you click on the payment request link it leads to edit, instead of view. The concern here is that users may not immediately figure out that three dots abstract something as simple as being able to view a payment request.

@dstrukt did you envision that edit link edits payment request, and the name link leads to viewing it or is edit a correct direction here? Should view and `...` be different actions? Also with introduction of this, we'd have to add it to pull payments to ensure consistency in the UI.


https://github.com/btcpayserver/btcpayserver/assets/36959754/b8237bcb-9021-49ed-938d-7c999cc7b8fe

**Comment by TChukwuleta** [comment]
Hello @pavlenex 

Yea, the previous implementation was actually an edit. I think making it a 'view' is good for a better user experience as against 'edit'
I'd update that.

**Comment by pavlenex** [comment]
Gotcha. 

> I'd update that. In that case I'd also remove 'view' from the dropdown

Let's keep it there for now, until people get used to it, may not be obvious for people yet, and we also need to consolidate other views, then we can optimize them all and remove view from dropdown.

**Comment by TChukwuleta** [comment]
Hello @pavlenex  this has been updated

**Review by dennisreimann — APPROVED** [review]
tACK

**Comment by dennisreimann** [comment]
@dstrukt you can review this now.

**Review by dstrukt — APPROVED** [review]
tACK!

Great work @TChukwuleta!

Agree with @pavlenex wrt Edit/View, if we get feedback that the current iteration is more difficult or confusing, we can always adjust as we work through all of the views.

Apologies my review took so long!

**Pull request merged**
