### PR TITLE
Update ListApps.cshtml

### PR DESCRIPTION
**Pull request by radWorx**
From ListApps, View App opens new tab.

### CODE REVIEW

**Comment by bolatovumar** [comment]
People might already be used to the existing behaviour so changing it now might confuse people.

**Comment by NicolasDorier** [comment]
@pavlenex this open app on a new tab when one click "View App" button instead of changing the current page.

I don't really know what's the best.

**Comment by pavlenex** [comment]
@NicolasDorier An unwritten rule is that the new tab is used to open external website links, for anything internal, it opens up in a current page, so I'm not that fond on changing what we currently   have.

**Comment by radWorx** [comment]
It's a UX thing in my opinion. Keep the ListApps page open and App in new tab as opposed  haveing to click back when on CF or PoS page.

**Comment by rockstardev** [comment]
I propose proceeding by creating linked "New tab" icon next to the "View" link... that opens new tab and re-uses that tab for App if user clicks link again.

We can replicate this with split button in Settings (where we have ViewApp opening link in new tab). For example:

split-button

**Comment by pavlenex** [comment]
Ok, that sounds like a good trade-off imo.

**Comment by rockstardev** [comment]
Continuing in #1303

**Pull request closed without merging**
