### PR TITLE
Improve Pull Payment view

### PR DESCRIPTION
**Pull request by dennisreimann**
Making sure the different constellations work properly, especially in terms of different breakpoints.

## Mobile

mobile-1

mobile-2

mobile-3

## Medium

medium-1

medium-2

## Large

large-1

large-2

### CODE REVIEW

**Comment by pavlenex** [comment]
I appreciate the influx of PR's but it would be good to focus on stuff we agreed on. For example this will most likely be a wasted effort because of the #1719. Don't have anything against the changes but would be good if we can collaborate a bit better to avoid overlaps and wasted efforts.

**Comment by Kukks** [comment]
Yeah, I think what we should do is merge this one and then consolidate both views to have a common UI framework to reduce code duplication. Easier to be consistent when we use the same "layout"

**Comment by dennisreimann** [comment]
@pavlenex sorry, I must have overlooked the issue. Did these spontaneously as I came across that page testing stuff. Will take a better look at the list next time.

**Comment by pavlenex** [comment]
No worries, this is still a good PR, just may get obsoleted quick, don't want your efforts to be in vain.😺 
I still think we'll get something good out of it, once merged, we can consolidate the layouts and then proceed with #1719 😉

**Pull request merged**
