### PR TITLE
fix invoice fetcher in crowdfund

### PR DESCRIPTION
**Pull request by Kukks**
Fixes bug where invoices were not being counted at all.
Also fixes an issue where you could no longer view invoices of a specific app.  Had to introduce a new invoice filter `appid`. 

Not the most efficient code but couldn't think of a better way for now.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
we can't query on `appId` this is not a column and mean we must bring in memory all the invoices, which is not acceptable.

**Comment by Kukks** [comment]
Yeah it is quite bad, I'm guessing there is no other way around it right?

**Comment by NicolasDorier** [comment]
no way to work around.

**Comment by NicolasDorier** [comment]
Normally fixed by https://github.com/btcpayserver/btcpayserver/commit/4016ded58466148119a07120543ae460abeac074

**Pull request closed without merging**
