### PR TITLE
Display fiat value of invoice during checkout

### PR DESCRIPTION
**Pull request by rockstardev**
As requested by #148

### CODE REVIEW

**Comment by hubiktomas** [comment]
Still liked this version https://github.com/btcpayserver/btcpayserver/issues/148#issuecomment-387942990 more as it looked more consistent - all totals together and additional info under. But if the majority is for this one, then ok. It will not stop me from using BTCPay Server. :)

**Comment by Kukks** [comment]
Maybe it can be configurable?  Not for this PR, but what if we allow stores to accept a template file with handlebars bindings or some simple templating engine?

**Comment by rockstardev** [comment]
OK, after extended discussion with @NicolasDorier and taking all points here in consideration I've removed "Order Amount in Fiat" (notice my showoff use of `git rebase` that made that commit... poof... disappear ;)).

So now what we have is - if Invoice is defined using Fiat (like USD) then we will show that value below "Order Amount" this way, similar to rate:

showing fiat value

If however invoice is defined using Crypto Currency as a source... then we don't show that or exchange rate (although it would be funny to excuse DOGE for this and show 1Đ=1Đ):

not showing fiat for invoices that are in crypto

I hope this allows us to finally close this issue and that merchants who wanted fiat display will be satisfied ;).

@NicolasDorier feel free to merge at your convenience when you test locally on how new layout feels.

**Comment by NicolasDorier** [comment]
let's merge this, we will adapt if there is complaints

**Comment by hubiktomas** [comment]
The exchange rate should not be displayed if the selected currency != order currency. But if I have order in BTC and select LTC in the BTCPay, there should be FX rate and order amount in the original currency displayed.

See the case below - order for 1 BTC, LTC selected.

image

**Comment by rockstardev** [comment]
@hubiktomas join on #179

**Pull request merged**
