### PR TITLE
Invoice View Improvements

### PR DESCRIPTION
**Pull request by dstrukt**
A lot has been discussed around this view, but there are some low hanging fruit that we've all agreed, in one form or another, that needs to be improved, so I thought I'd go ahead and make those simple changes.

Few reorders, sizing changes, label updates, etc.. to make things consistent with other views.

Before:
Screen Shot 2021-11-12 at 4 49 59 PM

After:
Screen Shot 2021-11-12 at 5 01 36 PM

-------------

1. I wonder what others think..should you be able to select LNURL from this list if it's not accessible? If not, I'm not 100% sure how to fix, might need some help from @dennisreimann on that one.
Screen Shot 2021-11-12 at 4 49 09 PM
Screen Shot 2021-11-12 at 4 14 58 PM

2. I'm not sure if these section labels make as much as sense as they could, but I think they're a step in the right direction, cc @pavlenex @Zaxounette.

------------

h/t @woutersamaey Imagine you'll have some thoughts, and will feed into your larger PR.

### CODE REVIEW

**Comment by satwo** [comment]
Looks much better already! 

What about checkboxes instead of a selectlist for `Supported Transaction Currencies`? Selecting multiple options with cmd+click isn't such a great UX.

**Comment by dstrukt** [comment]
Absolutely agree the multi-select component we use is pretty terrible, and been something on my list as well .. but not 100% sure I have the dev prowess to tackle that one, know how to iterate through the array on the View, but getting the Model to return the proper Information .. would be a good simple challenge though.

**Comment by satwo** [comment]
Oh yeah, that can definitely have its own PR, I was just brainstorming general ideas for this page :)

Really glad to see the ball rolling on improving this view, it definitely needs it IMO.

tACK.

**Review by dennisreimann — APPROVED** [review]
Good job!

**Comment by dennisreimann** [comment]
Made the payment methods list checkboxes, which fits better -- thanks @satwo for the suggestion!

image

> I wonder what others think..should you be able to select LNURL from this list if it's not accessible?

The invoice creation form is kinda tricky in that regard: The payment methods are tied to a store -- and hence the store is selectable in the form, we would have to reload the page whenever the store changes. I think we can enhance it and build an improved version once the store-centric changes are done or even meanwhile -- didn't do it here, because it'd involve a bit more changes.

**Comment by woutersamaey** [comment]
I have a copy change suggestion.
Instead of “Store’s default settings” can’t we put “Use the store’s default payment method” or “Use the store’s default” (shorter version)?

It reads kinda weird as it is currently.

**Comment by woutersamaey** [comment]
And i hate that POS Data field. What is that? If it’s an advanced option it should be hidden, or if not, there should be a tooltip / help icon.

**Comment by dstrukt** [comment]
@dennisreimann Nice job! I was so close in my attempt .. thought more was necessary than actually was needed .. but was good to learn from your code!

> The invoice creation form is kinda tricky in that regard: The payment methods are tied to a store -- and hence the store is > selectable in the form, we would have to reload the page whenever the store changes. I think we can enhance it and build > an improved version once the store-centric changes are done or even meanwhile -- didn't do it here, because it'd involve a > bit more changes.

Sounds good.

@woutersamaey Agreed some of the copy could definitely be improved, and I think that's within the scope of this .. will take a stab at some of the copy per your suggestions, etc.. here in a bit to wrap up this PR.

**Comment by Zaxounette** [comment]
> I have a copy change suggestion.
Instead of “Store’s default settings” can’t we put “Use the store’s default payment method” or “Use the store’s default” (shorter version)?
> It reads kinda weird as it is currently.

Agreed it could be imroved.

We could reuse the `Inherit from store settings` or we could improve on that as well while we're at it with something in the likes of `Inherit from store` (1) or just `Store default` (2).

**Comment by dstrukt** [comment]
Outside of wording, which I like your suggestions @Zaxounette, I think the first thing it calls into question, for me, is .. when did I set these defaults .. and subsequently, how do I change them?

I like the concept, and I think it's the type of UX improvements that really push things to the next level, but can be equally frustrating if not well explained how the result was achieved.

**Comment by satwo** [comment]
> And i hate that POS Data field. What is that? If it’s an advanced option it should be hidden, or if not, there should be a tooltip / help icon.
> 
> The 2 notification fields should perhaps also be hidden under an “advanced” section… this is very technical and more something you’d use with am API than through the GUI

Had the exact same thoughts.

**Comment by dennisreimann** [comment]
Created the additional options and moved the POS data (with added explanation) and notification fields to that.

image

Also applied @woutersamaey's wording change to the default payment method field.

**Comment by woutersamaey** [comment]
@dennisreimann thanks man!
To be 100% honenest, it still sounds a bit wierd because POS data is really just metadata? There is already a field for `orderId` and `itemDescription` so the extra explanation is suggesting a superfuous use case.

Maybe slightly use a different explanation?

To be 100% content, I'd prefer to see this field renamed to `MetaData`, but not sure if we could get consensus on that?

**Comment by woutersamaey** [comment]
Nitpick, maybe uppercase the word `Url` to `URL` ?

**Comment by dstrukt** [comment]
So damn quick @dennisreimann ... great work!

If we roll with MetaData, can it be Metadata?

+1 to "URL"

**Comment by woutersamaey** [comment]
Actually in the invoice visible from the API there is already a field called `Metadata`, so if we were to apply it here, that would collide.
Maybe the POS Data is here for historic reasons? If that is the case, maybe it can be deleted and we use the new Metadata field for the same purpose?

A more experienced dev than me is going to have to weigh in I believe.

**Comment by dennisreimann** [comment]
> Maybe the POS Data is here for historic reasons? 

AFAIK the `posData` property exists because of BitPay API compatibility. /cc @kukks

**Comment by dstrukt** [comment]
Mistake. 

Wrong branch, getting tired, going to submit that PR and go to sleep.

**Comment by pavlenex** [comment]
I like the cleanup, good job. One minor note is that it's weird that invoice form  is left-aligned, shouldn't it be centered? Or is this something we'll tackle in the future versions once we improve the #2619  empty states for consistency? Just want to make sure centering is planned in the future, that's all.


Screenshot 2021-11-15 at 21 39 03

**Review by pavlenex — CHANGES_REQUESTED** [review]
@dstrukt `amount` is no longer a required field. Neiher is currency if the preferred currency is selected, we should reflect that in the design.

**Comment by satwo** [comment]
A few more ideas:

-The checkbox list should default to all boxes checked. Right now, if you create an invoice and leave the payment methods as-is (assuming they are all enabled for the store), all three methods will be enabled in checkout, even though none are checked in Create Invoice.

-Instead of `Use the store's default` or `Inherit from store settings`, why not just pre-select the actual default, and append "_(Store default)_" or even just "_(default)_" to the selection? Therefore, if BTC On-Chain is the store default, the pre-selected option would be something like "BTC On-Chain _(default)_". I think this might be easier to understand and provide better/clearer information - the user can actually see what the store default is right there in the invoice, without having to go back to settings to check.

-`Supported Transaction Currencies` should only show store-enabled payment methods, but right now it shows all 3 possible methods regardless of whether any of them are disabled at the store level.

-When you change stores, the store-specific settings (defaults, available payment methods, etc) should change as well on the Create Invoice page.

I understand this is probably beyond the scope of this PR, and would be happy to open a new issue for it if others are in agreement.

**Comment by dstrukt** [comment]
- Agree with all checked be default
- Agree on the second point, and it addresses my concern with knowing what is the current default .. I still wonder how that was set / how to adjust it, but we can address that at a later point. May need some help with that one though.
- Yeah, I've brought this one up too, but I think there's some technical context behind this that @dennisreimann can or already has provided somewhere. I think it would need to be followed up in an additional PR.
- Agreed, and will remove the need for the Store selection on this view, etc.. we'll have to do some proper QA for this if/when we switch over to the Store-Centric architecture.

Great feedback @satwo!!

**Comment by satwo** [comment]
@dstrukt Made a slight change that mostly takes care of the first point (still possible to submit the form with all payment methods unselected; if this happens, all methods are enabled). 

Reading back over the thread again, I just realized that @dennisreimann already addressed some of my points, sorry Dennis! Indeed the new Store-Centric UI will go a long way to solving some of these issues.

For the other stuff not related to changing the selected store, it probably makes sense to make a new PR. One additional thing I've been thinking about is whether it's possible to unify `Supported Transaction Currencies` and `Default payment method on checkout` into a single, easy-to-understand control.

**Comment by dstrukt** [comment]
Beautiful, thank you - I think this PR is good to go.

But @satwo YES!

Also could include typing your currency vs. having a selectable list as part of improving that experience. I know there's a few technical considerations involved in all of that, but being able to make those distinctions more simple and clear would be a huge improvement .. could be something we explore in mocks for proposal.

**Pull request merged**
