### PR TITLE
Create RELEASE-CYCLES.md

### PR DESCRIPTION
**Pull request by pavlenex**
This PR adds documentation around release cycles in BTCPay and tends to outline processes and ensures there's documented structure on roles and responsibilities. Feedback welcome.

Initially I wanted to put it into `docs` folder, but then I noticed we have `RELEASE-CHECKLIST.MD` so I've just created the `.md` there.

### CODE REVIEW

**Review by dennisreimann — APPROVED** [review]

**Review by dstrukt — APPROVED** [review]
I like the standardization of this process - LGTM!

**Review by NicolasDorier — APPROVED** [review]

**Comment by NicolasDorier** [comment]
Btw, I think I should document the release process as well if somebody need to do it.

If I put that later, do you think it should be in the same document or different document?

**Comment by pavlenex** [comment]
@NicolasDorier We already have release-checklist.md is that what you are referring, or is it something else?

**Comment by NicolasDorier** [comment]
doh, forgot about it! Yes it is this one, I'll need to elaborate a bit.

**Pull request merged**
