### PR TITLE
Swagger: Added explanation for empty currency field in Create Payment Request

### PR DESCRIPTION
**Pull request by woutersamaey**

### CODE REVIEW

**Comment by NicolasDorier** [comment]
so the reason I didn't declared currency as null is that the `currency` field is only optional for create/update. But never null when you do a GET.

**Comment by NicolasDorier** [comment]
I actually changed the doc, but forgot to push before merge :/

**Comment by woutersamaey** [comment]
> so the reason I didn't declared currency as null is that the `currency` field is only optional for create/update. But never null when you do a GET.

I think we can make the distinction if we define 2 models in Swagger. 1 for create/update and 1 for get. Both are the same except the nullable field. Or is that not what you meant?

**Comment by NicolasDorier** [comment]
yeah we should define 2 model in swagger normally.

**Pull request merged**
