### PR TITLE
More Translations

### PR DESCRIPTION
**Pull request by dennisreimann**
Going through #6295 and adding more translations.

### CODE REVIEW

**Comment by dstrukt** [comment]
Will do a review, tag when ready!

**Comment by pavlenex** [comment]
tACK, this really adds a lot of missing gaps I reported here and beyond, good work @dennisreimann!

The only gaps I managed to find that are important are are in the wallet setup page
Screenshot 2024-10-21 at 12 32 24
Screenshot 2024-10-21 at 12 32 56
Screenshot 2024-10-21 at 12 33 00

@dennisreimann up to you if you'd want to add this, we can as well leave it out as a good first issue. 
Screenshot 2024-10-21 at 12 32 02

**Comment by dstrukt** [comment]
Pulled latest, added more and checking through the ones @pavlenex originally flagged, mine are minor, but thorough.

Huge improvement here already!

**Comment by pavlenex** [comment]
@NicolasDorier This one is waiting for your review, especially due to failing LN tests. Also @dennisreimann contacted you with some information on how to proceed with translating other strings.

**Comment by dennisreimann** [comment]
Nicolas agreed that we can tackle this after the release, good to go then.

**Pull request merged**
