### PR TITLE
Wallet UI quick wins

### LINKED ISSUE #5850: Coinselection should show more utxo and allow to sort by amount and show fiat value
The way I use coin control is to find an amount that match closely what I want to send and leave no change.

Like when funding another wallet / account.

10 per page is not enough and there should be sorting.  Could switch to sorting by amounts by default since I don't think many people care about the block height.

### PR DESCRIPTION
**Pull request by dennisreimann**
Draft mode, so that we can discuss the following changes:

- Unify single/multiple inputs display
- Destination: Move labels above amount
- Coin Selection: Add sorting by amount and confirmations, add page size. Closes #5850
- Move PSBT and BIP21 buttons up to input related button group
- Turn checkboxes in Advanced Settings into toggles
- Improve spacings and button groups

## Simple

wallet-plain

## Full

Screenshot 2024-03-19 at 13-22-33 Send BTC

### CODE REVIEW

**Comment by nostitos** [comment]
Moving the camera button to the address bar is a very low hanging fruit too.

**Comment by dennisreimann** [comment]
> Moving the camera button to the address bar is a very low hanging fruit too.

Re-added.

**Comment by nostitos** [comment]
https://github.com/btcpayserver/btcpayserver/issues/5784

Supposedly it's done.

**Comment by dennisreimann** [comment]
Yes, it got lost in my first version of this draft though. Thanks for the pointer!

**Comment by dstrukt** [comment]
> Moving the camera button to the address bar is a very low hanging fruit too.

ACK, glad to see it was done, have more thoughts, but immediate ones:

- Like the 2 column approach, but think the `Hide Coin Selection` CTA should be more correlated with that section, and `Add Destination` should take up the full line imo

...need to explore a better way to group this, as it'd be nice to push the CTA to the top right of the Coin Selection section, but then it wouldn't look great when hidden

- X selected / Total should be put where the Sort by is, then

- Sort by should be pushed to the right

- Think we should add cards around the destination sections, so we can eliminate the <hr> tags, will help delineate sections better

- Could arguably do that to the Coin Selection section as well

Mind if I take a quick stab at some visual explorations based on this? Love the push, looks much better!

**Comment by dennisreimann** [comment]
> Mind if I take a quick stab at some visual explorations based on this? Love the push, looks much better!

Sure, go ahead, glad to get this going.

**Review by Pjrich1313 — CHANGES_REQUESTED** [review]
Nodes and legally binding contracts only

**Comment by dennisreimann** [comment]
@dstrukt Shall we merge this and you'll take it from there?

**Comment by dennisreimann** [comment]
@NicolasDorier This one is ready for code review and merge. @dstrukt might do additioonal improvements based on this in a separate PR.

**Review by dstrukt — APPROVED** [review]
tACK

Going to follow up on this PR with a visual polish. Don't want to delay the improvements for that!

**Pull request merged**
