### PR TITLE
Transactions: Improve TX ID display

### PR DESCRIPTION
**Pull request by dennisreimann**
As per discussion with @NicolasDorier.

tx

### CODE REVIEW

**Comment by NicolasDorier** [comment]
@dennisreimann now I have another issue with this solution: CTRL + F searching for the txid in the list doesn't work anymore. :(

Is it something that can be improved in the component?

**Comment by NicolasDorier** [comment]
So I tried to set `elastic="true"` then I can CTRL+F. But the end of the transaction's id repeat itself.

**Review by dstrukt — APPROVED** [review]
functional tACK!

**Comment by NicolasDorier** [comment]
HUGE improvement for me

**Pull request merged**
