### PR TITLE
Add all buyer fields to create invoice page and adjust layout

### PR DESCRIPTION
**Pull request by bolatovumar**
This PR is a re-worked version of [this PR](https://github.com/btcpayserver/btcpayserver/pull/2603) based on feedback in this comment: https://github.com/btcpayserver/btcpayserver/pull/2603#pullrequestreview-697984211.

|Before|After|
|---|---|
|Capture|Capture|
|   |Capture2|

### CODE REVIEW

**Comment by dstrukt** [comment]
Added this as a list item for the design call, but wasn't able to get to everything, how should we combine the great work being done on this PR with (https://github.com/btcpayserver/btcpayserver/pull/3092)? Will there any potential conflicts?

cc @dennisreimann 

----------

Really liking the introduction of the Buyer fields! However, I wonder .. should the language be "Customer"? 

cc @pavlenex @Zaxounette

**Comment by bolatovumar** [comment]
@dstrukt we can merge #3092 and then I can rebase this PR against latest code and have the buyer fields added on top

**Comment by satwo** [comment]
tACK, but I agree with @dstrukt that `Customer` is probably the better choice. 

Might be worth putting some validation on the `Phone` field too?

**Comment by dstrukt** [comment]
Beautiful @bolatovumar, great work!

+1 to phone validation, unless there's something I'm missing.

**Comment by bolatovumar** [comment]
@satwo @dstrukt I can add phone validation but one drawback I noticed with it is that the validation doesn't happen in real time, it only happens on form submit (unlike email). I'm guessing this is probably there are different phone formats and .NET needs to do this on the server to match the request locale or something. I left it out because of this.

**Comment by Zaxounette** [comment]
> Really liking the introduction of the Buyer fields! However, I wonder .. should the language be "Customer"?

I agree, `buyer` can be changed to `customer` in the Buyer Detail title.

Buyer in each field can be delete altogether. With the title, we know those fields will relate to customer information and the specific detail needed in that field is sufficient (ie. Phone instead of Customer Phone)

**Comment by dstrukt** [comment]
Agreed @Zaxounette nice catch!

**Comment by satwo** [comment]
@bolatovumar I was thinking the same thing - not quite so simple to do international phone validation compared to domestic...

I'm sure it's fine for now but maybe something to think about long-term? (if/when businesses start to hook their phone systems into BTCPay Server.)

**Comment by NicolasDorier** [comment]
Concept NACK.
Those fields are meant to be deprecated, as they have no meaning and impact.
If I remember @dennisreimann worked on a better solution somewhere, where it was dynamic (a table which you can add rows to)

**Comment by bolatovumar** [comment]
@NicolasDorier ok, got it, closing this PR.

**Pull request closed without merging**
