### PR TITLE
Adjust invoice badge styling

### LINKED ISSUE #1744: Invoice Opening UX
Opening an invoice requires clicking on the little i inside the purple circle

- Previously clicking anywhere on the yellow invoice would open a new tab with all the transaction details
Screen Shot 2020-07-15 at 9 34 14 AM

### PR DESCRIPTION
**Pull request by bolatovumar**
**Before:**
Screen Shot 2020-09-13 at 5 27 00 PM

**After:**
Screen Shot 2020-09-13 at 5 21 05 PM

close #1744

### CODE REVIEW

**Comment by pavlenex** [comment]
LGTM

**Review by Kukks — APPROVED** [review]

**Review by Kukks — CHANGES_REQUESTED** [review]
I think it may have broken some tests

**Comment by mariodian** [comment]
The idea itself is good but the default coloring is off imo (not sure if that should be addressed in this PR though). The white text on the light greenish background isn't very visible. Especially on smaller screens with big resolutions. I can barely read the text on my mbp 15" even though macs do really good job at displaying colors and contrast.

**Comment by bolatovumar** [comment]
> The idea itself is good but the default coloring is off imo (not sure if that should be addressed in this PR though). The white text on the light greenish background isn't very visible. Especially on smaller screens with big resolutions. I can barely read the text on my mbp 15" even though macs do really good job at displaying colors and contrast.

Colors are defined by the themes although I believe the text is always white. I do agree that it's not the easiest to read. I think color changes should be a separate issue/PR though.

**Comment by bolatovumar** [comment]
> I think it may have broken some tests

I will take a look.

**Comment by bolatovumar** [comment]
@Kukks OK, build is green now, tests are good.

**Comment by Kukks** [comment]
Will merge, but can you test latest on master after and see if the coloring is OK since this is automated? 
We have labels for: invoices, payouts, payjoin, payment requests and apps as of master branch

**Pull request merged**
