### PR TITLE
Improves Api Key View

### PR DESCRIPTION
**Pull request by dstrukt**
Been going through some of the subpages and doing some quick clean up while I work through these views in Figma to prep for the Store Centric UI updates ... so apologies for future potential PR spam.

List Before:
Screen Shot 2021-11-12 at 8 23 50 PM

List After:
Screen Shot 2021-11-12 at 8 24 04 PM

Empty State Before:
Screen Shot 2021-11-12 at 8 24 26 PM

Empty State After:
Screen Shot 2021-11-12 at 8 27 02 PM

Note: Might be worth checking the main conditional, I think it's good though.

Otherwise this was just aesthetic clean up, labels, titles, padding, etc..

### CODE REVIEW

**Comment by woutersamaey** [comment]
Doesn't it look weird you can have an api key "without permissions" as shown in the screenshots?

**Comment by dstrukt** [comment]
That's a good point .. should at least >1 permission be required to create a key? I could see arguments for both side.

**Review by dennisreimann — APPROVED** [review]
Yeehaw!

**Comment by woutersamaey** [comment]
> I could see arguments for both side.

Since permissions cannot be changed after the api key was created, it should always have at least 1 permission.

**Comment by dstrukt** [comment]
@woutersamaey Will try to solve in a separate PR, might be another good small task for me to try to tackle, if I cannot, will reach out!

Otherwise, I think this PR is good to go!

**Comment by Kukks** [comment]
> That's a good point .. should at least >1 permission be required to create a key? I could see arguments for both side.

> Doesn't it look weird you can have an api key "without permissions" as shown in the screenshots?

No there are use-cases for a key with no permissions. Such as using btcpay just for proof-of-account

**Review by Kukks — APPROVED** [review]

**Pull request merged**
