### PR TITLE
Support LNURL in crowdfund app

### PR DESCRIPTION
**Pull request by Kukks**

### CODE REVIEW

**Comment by pavlenex** [comment]
I assume this enables LNRUL for all, not just for topup?

**Comment by Kukks** [comment]
image
image

This PR needs some UI love. :( Otherwise everythign else is ready

**Review by dennisreimann — APPROVED** [review]
There wasn't much to be done, good work!

**Comment by NicolasDorier** [comment]
good for me, but please add a test that run the logic of `ViewCrowdfund.cshtml`. There is lots of magic string here, it will blow up sooner or later, so put a test so we can catch this.

**Comment by NicolasDorier** [comment]
need rebase

**Comment by NicolasDorier** [comment]
I rebased this one, ViewCrowdfund.cshtml was the most impacted

**Pull request merged**
