### PR TITLE
Fix PJ 

### LINKED ISSUE #1500: Invoices tab incorrectly marks payjoin to p2sh-p2wpkh as non-payjoin
**Describe the problem/bug**
When performing payjoin with p2wpkh, Invoices tab marks it correctly. With p2sh-p2wpkh it says it is paidOver with the amount of my payjoin utxo. (See image below, each wallet started with 1 UTXO of 0.1337 BTC size and it shows payment for 0.1337 + the actual invoice value)

**Your environment**
* Version of BTCPay Server: Github commit 7adaa14

**To Reproduce**
1. Create invoice with store that has p2sh-p2wpkh hot wallet, at least one utxo, and payjoin enabled.
2. Perform payjoin to pay the invoice.
3. Open invoice tab
4. See it was paidOver and it was marked as paying utxo value extra.

**Expected behavior**
It should be marked as payjoin and not paidOver. (see p2wpkh example in image below)

**Actual behavior**
It is marked paidOver  (see p2sh-p2wpkh example in image below)

**Screenshots/Links**
範囲を選択_001

### PR DESCRIPTION
**Pull request by Kukks**
@junderw @NicolasDorier  
Supersedes #1501  to fix #1500 

* Added e2e test for all supported formats
* fixes issue with null ref exceptions and not being able to get signablecoins from the psbt directly

### CODE REVIEW

**Comment by junderw** [comment]
building and testing now

**Comment by junderw** [comment]
Fixed!!!

範囲を選択_001

**Comment by junderw** [comment]
tested ACK c5bd2ef26f96885e7696b0d80beceb8b688ecd87

**Comment by NicolasDorier** [comment]
@Kukks `Added e2e test for all supported formats` there is no test.

**Comment by Kukks** [comment]
https://github.com/btcpayserver/btcpayserver/commit/4be6c06af57a6ce4f2d0c13ee8d7db2fad0983e2

**Comment by junderw** [comment]
Just a note: master broke this with some commits after merging, but it is fixed again in 79c70b31a3e30cb4fc25d46143ef6fdfeae49a6d (current master)

**Pull request merged**
