### PR TITLE
Make Invoice Create Faster And Fix Gap Limit Issue

### PR DESCRIPTION
**Pull request by xpayserver**
This make address reserve only when user "activate" payment method in ui. It is optional setting in store checkout ui so no difference existing store. 

This way BTC wallet only use address customer intend pay so it reduce gap limit issue almost entirely. In ETH case, it make it more likely for ETH and ERC to end in same wallet. Lightning no effect.

Also this make invoice creation very fast almost 10x faster

### CODE REVIEW

**Comment by NicolasDorier** [comment]
I think @pavlenex will like that one.

@xpayserver I like the principle. However, rather than having this I would prefer a different model where we have two steps to the checkout process rather than hack around the interface.

1. Select your crypto currency
2. Show the current UX

Maybe @dennisreimann  might be interested to work on the UX to make that possible.

IMHO this mode should be the default.
But for the Bitpay's legacy API level, we will keep the current behavior, as to not break consumer of the API who expects finding the payment methods as soon as invoice created.

Ping @Kukks I think this is worth to discuss for the next invoice API. That it takes into account this option.

**Comment by NicolasDorier** [comment]
related discussion https://github.com/btcpayserver/btcpayserver/issues/434

**Comment by Kukks** [comment]
> I think @pavlenex will like that one.
> 
> @xpayserver I like the principle. However, rather than having this I would prefer a different model where we have two steps to the checkout process rather than hack around the interface.
> 
> 1. Select your crypto currency
> 2. Show the current UX
> 
> Maybe @dennisreimann might be interested to work on the UX to make that possible.
> 
> IMHO this mode should be the default.
> But for the Bitpay's legacy API level, we will keep the current behavior, as to not break consumer of the API who expects finding the payment methods as soon as invoice created.
> 
> Ping @Kukks I think this is worth to discuss for the next invoice API. That it takes into account this option.

I prefer this flow as choosing the invoice currency in advance means you cannot switch mid-way in the invoice. This flow will also be possible with #863 where you create an optiopn to choose your intended payment option
For Invoice API #1760, we can just add the "activated" property on the payment method array object (and create the post endpoint to activate like in here)

**Comment by pavlenex** [comment]
Just a 🤖 linking issues, don't mind me.
Related #1728 #434
Closes #924

**Comment by Kukks** [comment]
cc @astupidmoose I feel like we've talked about this before

**Comment by astupidmoose** [comment]
Yea, I think this was an old issue which I just learned to work around. 

https://github.com/btcpayserver/btcpayserver/issues/22

**Comment by rockstardev** [comment]
+1 on keeping current flow rather than choosing currency in advance and then not being able to switch midway. Ability to select while still on invoice is one of the biggest advantages we have. All the other checkouts suck because their engineering teams were too lazy to implement this advanced scenario.

**Comment by NicolasDorier** [comment]
ok, I think I will merge this before next release then.

**Comment by NicolasDorier** [comment]
@xpayserver I made some breaking change, can you rebase? It should not be hard.
You may want to do a hack I did for Monero in PaymentMethodId as well.

**Comment by xpayserver** [comment]
> @xpayserver I made some breaking change, can you rebase? It should not be hard.
> You may want to do a hack I did for Monero in PaymentMethodId as well.

I have rebase

**Comment by mariodian** [comment]
tACK - it really speeds things up

**Comment by pavlenex** [comment]
@xpayserver do you mind resolving remaining conflicts, I promise we'll expedite the merge, since it's been approved a few times already.

**Comment by Kukks** [comment]
@xpayserver can you rebase?

**Comment by wallopthecat** [comment]
Is this being blocked by something?

**Comment by Kukks** [comment]
> Is this being blocked by something?

We needed the author to rebase but seems like they did and did not get a notification. Let me rebase it myself and see

**Comment by Kukks** [comment]
Rebased and fixed a number of things along with added tests. I think it is good to go now, will merge if there are no objections

**Comment by rockstardev** [comment]
@Kukks can you push commit on @xpayserver repo, I don't have access:

```
From fba22a981048a2ac005de1f1c6a0e1fae2c72f49 Mon Sep 17 00:00:00 2001
From: rockstardev <rockstardev@users.noreply.github.com>
Date: Mon, 4 Jan 2021 23:19:22 -0600
Subject: [PATCH] Rearranging lazy payments position in UI to be near dependent
 Unified QR code

---
 BTCPayServer.Client/Models/StoreBaseData.cs          |  3 +--
 .../Controllers/GreenField/StoresController.cs       |  2 +-
 BTCPayServer/Controllers/StoresController.cs         |  2 +-
 BTCPayServer/Data/StoreBlob.cs                       |  3 +--
 .../StoreViewModels/CheckoutExperienceViewModel.cs   |  6 +++---
 BTCPayServer/Views/Stores/CheckoutExperience.cshtml  | 12 ++++++------
 6 files changed, 13 insertions(+), 15 deletions(-)

diff --git a/BTCPayServer.Client/Models/StoreBaseData.cs b/BTCPayServer.Client/Models/StoreBaseData.cs
index 7e0e76c5..ff4b9be6 100644
--- a/BTCPayServer.Client/Models/StoreBaseData.cs
+++ b/BTCPayServer.Client/Models/StoreBaseData.cs
@@ -35,6 +35,7 @@ namespace BTCPayServer.Client.Models
         public bool LightningAmountInSatoshi { get; set; }
         public bool LightningPrivateRouteHints { get; set; }
         public bool OnChainWithLnInvoiceFallback { get; set; }
+        public bool LazyPaymentMethods { get; set; }
         public bool RedirectAutomatically { get; set; }
 
         [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
@@ -53,8 +54,6 @@ namespace BTCPayServer.Client.Models
 
         public string HtmlTitle { get; set; }
 
-        public bool LazyPaymentMethods { get; set; }
-
         [JsonConverter(typeof(StringEnumConverter))]
         [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
         public NetworkFeeMode NetworkFeeMode { get; set; } = NetworkFeeMode.Never;
diff --git a/BTCPayServer/Controllers/GreenField/StoresController.cs b/BTCPayServer/Controllers/GreenField/StoresController.cs
index 321d994d..e3f98c85 100644
--- a/BTCPayServer/Controllers/GreenField/StoresController.cs
+++ b/BTCPayServer/Controllers/GreenField/StoresController.cs
@@ -168,8 +168,8 @@ namespace BTCPayServer.Controllers.GreenField
             blob.LightningAmountInSatoshi = restModel.LightningAmountInSatoshi;
             blob.LightningPrivateRouteHints = restModel.LightningPrivateRouteHints;
             blob.OnChainWithLnInvoiceFallback = restModel.OnChainWithLnInvoiceFallback;
-            blob.RedirectAutomatically = restModel.RedirectAutomatically;
             blob.LazyPaymentMethods = restModel.LazyPaymentMethods;
+            blob.RedirectAutomatically = restModel.RedirectAutomatically;
             blob.ShowRecommendedFee = restModel.ShowRecommendedFee;
             blob.RecommendedFeeBlockTarget = restModel.RecommendedFeeBlockTarget;
             blob.DefaultLang = restModel.DefaultLang;
diff --git a/BTCPayServer/Controllers/StoresController.cs b/BTCPayServer/Controllers/StoresController.cs
index 62892a51..79970f79 100644
--- a/BTCPayServer/Controllers/StoresController.cs
+++ b/BTCPayServer/Controllers/StoresController.cs
@@ -402,10 +402,10 @@ namespace BTCPayServer.Controllers
                 }
             }).ToList();
             vm.RequiresRefundEmail = storeBlob.RequiresRefundEmail;
-            vm.LazyPaymentMethods = storeBlob.LazyPaymentMethods;
             vm.LightningAmountInSatoshi = storeBlob.LightningAmountInSatoshi;
             vm.LightningPrivateRouteHints = storeBlob.LightningPrivateRouteHints;
             vm.OnChainWithLnInvoiceFallback = storeBlob.OnChainWithLnInvoiceFallback;
+            vm.LazyPaymentMethods = storeBlob.LazyPaymentMethods;
             vm.RedirectAutomatically = storeBlob.RedirectAutomatically;
             vm.ShowRecommendedFee = storeBlob.ShowRecommendedFee;
             vm.RecommendedFeeBlockTarget = storeBlob.RecommendedFeeBlockTarget;
diff --git a/BTCPayServer/Data/StoreBlob.cs b/BTCPayServer/Data/StoreBlob.cs
index eb593199..ea40ea7e 100644
--- a/BTCPayServer/Data/StoreBlob.cs
+++ b/BTCPayServer/Data/StoreBlob.cs
@@ -34,12 +34,11 @@ namespace BTCPayServer.Data
         [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
         public NetworkFeeMode NetworkFeeMode { get; set; }
 
-        public bool LazyPaymentMethods { get; set; } = false;
-
         public bool RequiresRefundEmail { get; set; }
         public bool LightningAmountInSatoshi { get; set; }
         public bool LightningPrivateRouteHints { get; set; }
         public bool OnChainWithLnInvoiceFallback { get; set; }
+        public bool LazyPaymentMethods { get; set; }
         public bool RedirectAutomatically { get; set; }
         public bool ShowRecommendedFee { get; set; }
         public int RecommendedFeeBlockTarget { get; set; }
diff --git a/BTCPayServer/Models/StoreViewModels/CheckoutExperienceViewModel.cs b/BTCPayServer/Models/StoreViewModels/CheckoutExperienceViewModel.cs
index 95aad703..2e758e5a 100644
--- a/BTCPayServer/Models/StoreViewModels/CheckoutExperienceViewModel.cs
+++ b/BTCPayServer/Models/StoreViewModels/CheckoutExperienceViewModel.cs
@@ -44,6 +44,9 @@ namespace BTCPayServer.Models.StoreViewModels
         [Display(Name = "Include lightning invoice fallback to on-chain BIP21 payment url")]
         public bool OnChainWithLnInvoiceFallback { get; set; }
 
+        [Display(Name = "Only enable the payment method after user explicitly activates it")]
+        public bool LazyPaymentMethods { get; set; }
+
         [Display(Name = "Redirect invoice to redirect url automatically after paid")]
         public bool RedirectAutomatically { get; set; }
 
@@ -66,9 +69,6 @@ namespace BTCPayServer.Models.StoreViewModels
         [Display(Name = "Custom HTML title to display on Checkout page")]
         public string HtmlTitle { get; set; }
 
-        [Display(Name = "Only enable the payment method after user explicitly activates it")]
-        public bool LazyPaymentMethods { get; set; }
-
         public List<PaymentMethodCriteriaViewModel> PaymentMethodCriteria { get; set; }
     }
 
diff --git a/BTCPayServer/Views/Stores/CheckoutExperience.cshtml b/BTCPayServer/Views/Stores/CheckoutExperience.cshtml
index f89783e9..29ab7497 100644
--- a/BTCPayServer/Views/Stores/CheckoutExperience.cshtml
+++ b/BTCPayServer/Views/Stores/CheckoutExperience.cshtml
@@ -62,12 +62,6 @@
                     <label asp-for="RequiresRefundEmail" class="form-check-label"></label>
                 </div>
             </div>
-            <div class="form-group">
-                <div class="form-check">
-                    <input asp-for="LazyPaymentMethods" type="checkbox" class="form-check-input"/>
-                    <label asp-for="LazyPaymentMethods" class="form-check-label"></label>
-                </div>
-            </div>
             <div class="form-group">
                 <div class="form-check">
                     <input asp-for="LightningAmountInSatoshi" type="checkbox" class="form-check-input" />
@@ -86,6 +80,12 @@
                     <label asp-for="OnChainWithLnInvoiceFallback" class="form-check-label"></label>
                 </div>
             </div>
+            <div class="form-group">
+                <div class="form-check">
+                    <input asp-for="LazyPaymentMethods" type="checkbox" class="form-check-input" />
+                    <label asp-for="LazyPaymentMethods" class="form-check-label"></label>
+                </div>
+            </div>
             <div class="form-group">
                 <div class="form-check">
                     <input asp-for="RedirectAutomatically" type="checkbox" class="form-check-input" />
-- 
2.26.2.windows.1

```

**Review by rockstardev — APPROVED** [review]
LGTM... I'm kidna torn on the fact user needs to click on button to activate. But I guess we can always change it later - activate as soon as method is selected.

Unified QR Code is not working initially, but starts working if both onchain and offchain methods are activated. 

I would leave it like this... provided patch to move settings closer so it's more obvious to store owner - if they want lazy payment methods for now, they won't work combined with unified QR code.

https://user-images.githubusercontent.com/5191402/103610069-dbad2680-4ee4-11eb-980e-c8999540d3b3.mp4

**Comment by pavlenex** [comment]
I'm with @rockstardev on this one, `Activate payment method` button is very confusing UX-wise. What does it even mean to a regular user and why are we adding an unnecessary step for the checkout here?

Since it's a Server Setting Policy, I can live with it, but would prefer payment method to be activated when currency is selected instead.

**Comment by wallopthecat** [comment]
> 
> 
> I'm with @rockstardev on this one, `Activate payment method` button is very confusing UX-wise. What does it even mean to a regular user and why are we adding an unnecessary step for the checkout here?
> 
> Since it's a Server Setting Policy, I can live with it, but would prefer payment method to be activated when currency is selected instead.

How about changing the wording to "choose/use this currency" or "click to use CURRENCYNAME" - it prevents people who click on the other currencies so they get the total amount (to see if they can afford it) from generating addresses they don't intend to use

**Comment by astupidmoose** [comment]
> I'm with @rockstardev on this one, `Activate payment method` button is very confusing UX-wise. What does it even mean to a regular user and why are we adding an unnecessary step for the checkout here?
> 
> Since it's a Server Setting Policy, I can live with it, but would prefer payment method to be activated when currency is selected instead.

Agreed. I can only imagine the number of customers who will open tickets asking "How do I activate a payment account" or something similar. I hope this is optional.

**Comment by Kukks** [comment]
@xpayserver  @rockstardev  @pavlenex @astupidmoose  I have rebased and updated this PR so that it automatically activates when you load or change a payment method. There is no visible difference from the standard checkout now

**Comment by Kukks** [comment]
@xpayserver For some reason I cannot rerun the tests on CircleCI because they are running on your account or something. Can you re run them

**Comment by pavlenex** [comment]
This now LGTM, though I haven't tested it with altcoins, but it's good improvement that methods are swapped automatically. @astupidmoose can you test it perhaps?

**Comment by NicolasDorier** [comment]
I think that later we should rather allow merchants to set which payments to activate by default.
But let's see how the feedback go for now.

**Comment by pavlenex** [comment]
@NicolasDorier I agree this should be default if the feedback we get is good, good idea.

**Pull request merged**
