### PR TITLE
Chivo mode for the checkout

### PR DESCRIPTION
**Pull request by NicolasDorier**

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Chivo support status:

BITCOIN:BECH32  :  N
BITCOIN:bech32  :  N
bitcoin:BECH32  :  N
bitcoin:bech32  :  Y

For lightning, it only support lowercase, without prefix.

**Comment by pavlenex** [comment]
Concept nack, we shouldn't da na fix, Chivo should follow the BIP entirely. "Chivo mode" also sounds quite bad.

**Comment by jquiros2** [comment]
Yes, Chivo should and name on tick could be changed.  At least for now we have the workaround but makes updates more difficult for inexperienced in git/docker.  A shame how sometimes in history govs fool with disguises as democracy.
Thanks for the impulse @NicolasDorier.

**Comment by pavlenex** [comment]
@jquiros2 Athena Bitcoin CEO [mentioned](https://twitter.com/EGravengaard/status/1445608970022916102?s=20) they'll fix this by the way, hence why we're closing it.

**Comment by jquiros2** [comment]
@pavlenex.  So koibanx.com are the ones doing the chivo wallet (algorand).  Athena is payment gateways and ATM's.  Really messed up implementation.  When you try to send BTC out of chivo, it mostly gets stuck, and discounted, then you need to call or email support and a few days later they reimburse with no explanation.  I've been trying to get some funds out of chivo.  I had sent to chivo as a test and for funding an lnd channel.  So far I 've tried three times and it keeps getting stuck).  Of course chivo is what people want to use b/c the gov gave $30 worth to ppl who use it.  Chivo-chivo if fine.  Tough for merchants who do not want to use chivo to accept payments.  Just giving the scoop as I think it is important for BTC community to know how it's going.  Hopefully will work soon!  Still nothing on chivo -https://github.com/btcpayserver/btcpayserver/issues/2110 .   By the way, absolutely FANTASTIC that we as a world have BTCPAY.  Thank you!  Now just tryong to sort through  the current lnd issues but that's something else.

**Comment by NicolasDorier** [comment]
@jquiros2 mentioned that Chivo 2.0 seems to be better with QR Codes and made this mode useless. :)

**Pull request closed without merging**
