### PR TITLE
Add labels for recent txs dashboard widget

### PR DESCRIPTION
**Pull request by Kukks**
It is not with the rich data for now, but a good start.

### CODE REVIEW

**Review by dennisreimann — APPROVED** [review]
tACK. Also added the rich info and reused the new component to display the transaction ID.

grafik

**Comment by Kukks** [comment]
> tACK. Also added the rich info and reused the new component to display the transaction ID.
> 
> grafik

Wow, that really pimped it up well

**Comment by dennisreimann** [comment]
We're kukksifying and d11nifying ALL THE THINGS!

**Review by dstrukt — APPROVED** [review]
ALL THE THINGS!

tACK - LGTM!

**Pull request merged**
