### PR TITLE
GreenField: Get Available Payment Types & Methods API

### PR DESCRIPTION
**Pull request by Kukks**
Helpful when configuring stores/wallets

### CODE REVIEW

**Comment by NicolasDorier** [comment]
mmh I would prefer that we have a more general call.
Like "Get Server Information" which give all information like the sync progress, what is supported, and all information that are public once you are logged in.

**Comment by Kukks** [comment]
ok how about 
`GET /api/v1/server/info`
returns 
```
{
  "paymentTypes": {
    "BTCLike": {
      "paymentMethods": {
        "BTC_BTCLike": {}
       }
    }
  }
}
```

**Comment by NicolasDorier** [comment]
I think the nesting sucks, should be string array.

**Comment by Kukks** [comment]
string array does not leave room to add props if we need to give additional info ( such as sync progress if we wanted to) 
how about
```json
{
  "paymentTypes": [
    {
      "id": "BTCLike",
      "paymentMethods": [
        {
          "id": "BTC_BTCLike",
          "x": 1,
          "y": 2
        }
      ]
    }
  ]
}
```

**Comment by NicolasDorier** [comment]
Payment methods is a merchant concept, node synching has nothing to do with it.
I was thinking something more like that
```json
{
   "status": {
     "fullySynched": true,
     "syncStatus": [
        {
            "cryptoCode": "BTC",
            "blockHeaders": 1029392,
            "progress": 0.99,
        }
      ]
   },
   "version": "1.0.4.1",
   "onion": "blah.onion",
   "supportedPaymentMethods": [ "BTC_OnChain", "BTC_OffChain" ]
}
```

**Comment by Kukks** [comment]
> 
> 
> Payment methods is a merchant concept, node synching has nothing to do with it.
> I was thinking something more like that
> 
> ```json
> {
>    "status": {
>      "fullySynched": true,
>      "syncStatus": [
>         {
>             "cryptoCode": "BTC",
>             "blockHeaders": 1029392,
>             "progress": 0.99,
>         }
>       ]
>    },
>    "version": "1.0.4.1",
>    "onion": "blah.onion",
>    "supportedPaymentMethods": [ "BTC_OnChain", "BTC_OffChain" ]
> }
> ```

I would leave out the onion and put it in a separate endpoint like 
`api/v1/server/services` where we list all the services available (p2p, rpc, hidden services, etc)

**Comment by NicolasDorier** [comment]
> api/v1/server/services

Also, but it should also be in status as those have different permission level.
The onion link is public information, not /v1/server/services.

**Comment by Kukks** [comment]
> 
> 
> Payment methods is a merchant concept, node synching has nothing to do with it.
> I was thinking something more like that
> 
> ```json
> {
>    "status": {
>      "fullySynched": true,
>      "syncStatus": [
>         {
>             "cryptoCode": "BTC",
>             "blockHeaders": 1029392,
>             "progress": 0.99,
>         }
>       ]
>    },
>    "version": "1.0.4.1",
>    "onion": "blah.onion",
>    "supportedPaymentMethods": [ "BTC_OnChain", "BTC_OffChain" ]
> }
> ```

**Pull request closed without merging**
