### PR TITLE
Update explorer to blockstream.info

### PR DESCRIPTION
**Pull request by grubles**
Title is pretty self-explanatory.

### CODE REVIEW

**Comment by Kukks** [comment]
What's the issue with the current explorer?

**Comment by NicolasDorier** [comment]
damn why this test is still running when not in master? @rockstardev any idea? I thought it was fixed.

**Comment by rockstardev** [comment]
@NicolasDorier we didn't implement that @Kukks PR fix... can do it now.

**Comment by NicolasDorier** [comment]
Personally I prefer blockstream.info, that said maybe a better idea is to all customization at the user's setting level.

**Comment by grubles** [comment]
@Kukks Blockstream releases the code for blockstream.info, unlike Smartbit (AFAICT, at least). https://github.com/Blockstream/esplora

Another notable difference is Blockstream.info supports browsing javascript-less via tor and through tor hidden services.

**Comment by britttttk** [comment]
ack - translated blockchain explorer

**Comment by NicolasDorier** [comment]
Make me think that later we should use the onion link if BTCPay is used on Tor Browser instead of the clearnet link.

**Pull request merged**
