### PR TITLE
Improve validation message spacing

### PR DESCRIPTION
**Pull request by dennisreimann**
Minor improvement I found while working on the login redesign in #1712.

Affects all validation items that contain text – the empty ones should be rendered without spacing.

## Before
before

## After
after

### CODE REVIEW

**Comment by bolatovumar** [comment]
Looking good.

**Comment by NicolasDorier** [comment]
conflict

**Comment by dennisreimann** [comment]
Resolved :)

**Comment by dennisreimann** [comment]
This is already in master, with the first login PR that got merged last week.

**Pull request closed without merging**
