### PR TITLE
Removing Baillie Gifford as BTCPay Foundation supporter

### PR DESCRIPTION
**Pull request by ConstantineGhost**
Removing BG as a supporter

Adressing Issue #6500

### CODE REVIEW

**Comment by rockstardev** [comment]
Hey @ConstantineGhost, let's keep 1 PR focused on 1 issue. Let's just do #6500.

Also, please ensure all the repositories are addressed, see my comment on: https://github.com/btcpayserver/btcpayserver/issues/6500#issuecomment-2551608865

**Review by rockstardev — CHANGES_REQUESTED** [review]
Hey @ConstantineGhost, let's keep 1 PR focused on 1 issue. Let's just do https://github.com/btcpayserver/btcpayserver/issues/6500. Please remove parts of #6501, @dennisreimann will do that separately.

Also, please ensure all the repositories are addressed, see my comment on: https://github.com/btcpayserver/btcpayserver/issues/6500#issuecomment-2551608865

**Comment by rockstardev** [comment]
@ConstantineGhost can you just directly link the issue itself so it has an index of PRs?

Like: https://github.com/btcpayserver/blog/pull/63 should start with:

`Resolves: github.com/btcpayserver/btcpayserver/pull/6500`

That way links are on the issue, not PRs, as I did with 6143
image

**Comment by ConstantineGhost** [comment]
Done!

**Review by dennisreimann — APPROVED** [review]

**Review by pavlenex — APPROVED** [review]

**Pull request merged**
