### PR TITLE
Adds social links to Layout

### PR DESCRIPTION
**Pull request by 1nF0rmed**
**Fixes**: #2884 

**Description:**
This removes the logo credits in the base Layout and adds the
links to Github, Mattermost and Twitter.

image

### CODE REVIEW

**Review by dennisreimann — CHANGES_REQUESTED** [review]
Hey, thanks for the contribution!

Can you remove the "Let's Get In Touch!" block from the homepage too? I think we can get rid of that with these changes.

We should also ensure this works good on mobile and I'd suggest stacking the links and the copyright in that case, instead of floating them.

The colors can also be optimized, let me know if I should assist with anything.

footer

**Comment by NicolasDorier** [comment]
Awesome! Way better to have it in the footer. I agree that the section can be removed.

**Comment by 1nF0rmed** [comment]
> Can you remove the "Let's Get In Touch!" block from the homepage too? I think we can get rid of that with these changes.

Sure, I'll add a commit for the same

> We should also ensure this works good on mobile and I'd suggest stacking the links and the copyright in that case, instead of floating them.

So, we would have 2 layers. One layer with the social links horizontally aligned and the second layer with the copyright information.
Would that be correct?

> The colors can also be optimized, let me know if I should assist with anything.

The text color seems to have decent contrast to be visible. The icons for Github and Mattermost right now can't be seen that well. Can I change it so it looks like how it would in dark mode?

**Comment by dennisreimann** [comment]
> So, we would have 2 layers. One layer with the social links horizontally aligned and the second layer with the copyright information.
> Would that be correct?

Yes, each link as a separate line and the copyright underneath the links on mobile, side by side (as currently) when it starts to fit. (might be the medium/MD breakpoint)

> The text color seems to have decent contrast to be visible. The icons for Github and Mattermost right now can't be seen that well. Can I change it so it looks like how it would in dark mode?

I can take care of that afterwards: I'd do some modifications in the design system to make the colors work and also add the icons to the icon sprite, so that we have them as proper SVGs.

**Comment by dennisreimann** [comment]
@1nF0rmed Can you give me access to your fork, so that I can push my updates? Finetuned it a bit and introduced the icons to the sprite.

**Comment by 1nF0rmed** [comment]
> @1nF0rmed Can you give me access to your fork, so that I can push my updates? Finetuned it a bit and introduced the icons to the sprite.

Done

**Comment by dennisreimann** [comment]
Thanks, pushed my changes -- ready to go now!

**Review by dennisreimann — APPROVED** [review]

**Comment by pavlenex** [comment]
@dennisreimann doesn't look visible enough in the dark mode (especially important info such as version?)

Screenshot 2021-09-23 at 13 17 50

**Comment by dennisreimann** [comment]
@pavlenex Fair enough, good catch! Good like that?

footer

**Review by pavlenex — APPROVED** [review]

**Pull request merged**
