### PR TITLE
Manual payment no network

### PR DESCRIPTION
**Pull request by Kukks**
This PR is based on top of #920 but removes the dependency of the Network for a payment metho

### CODE REVIEW

**Comment by NicolasDorier** [comment]
@Kukks is there a way you can isolate some stupid easy changes to review, this is 1300 lines :(

**Comment by NicolasDorier** [comment]
probably need to rebase

**Comment by NicolasDorier** [comment]
need rebase

**Comment by Kukks** [comment]
Will rebase after #1007

**Comment by jooray** [comment]
Any progress on this?

**Comment by Kukks** [comment]
> 
> 
> Any progress on this?
Need #1007  to be merged first

**Comment by Kixunil** [comment]
Tested that branch, I found a bug: when I click "Mark paid", it appears to do nothing. When I change the payment method, it shows as paid.

**Comment by Kukks** [comment]
Needs to be refactored a bit since it's been a while and rebased a few times without testing.

**Comment by Kixunil** [comment]
No problem, just letting you know.

**Comment by jooray** [comment]
Just that you know, it also breaks notifications for other payment types. When you refresh the page, the invoice shows as paid.

So even if I pick btc lightning and pay, the confirmation does not appear right away. Anyway, we are giving this branch a try, if you have any other version for testing, let us know.

**Comment by rockstardev** [comment]
This one will be reopened with new db migrations.

**Pull request closed without merging**
