### PR TITLE
Address issues in #606

### PR DESCRIPTION
**Pull request by bolatovumar**

### CODE REVIEW

**Comment by NicolasDorier** [comment]
@pavlenex can you check that it solves your issue on https://github.com/btcpayserver/btcpayserver/issues/606 ?

**Comment by NicolasDorier** [comment]
ping again @pavlenex

**Comment by pavlenex** [comment]
@NicolasDorier Sorry, a bit late to the party. The changes completely solve #606 
@bolatovumar You mentioned you want to add a few more changes, not sure if you [tackled everything you wanted.](https://github.com/btcpayserver/btcpayserver/issues/606#issuecomment-524262291)

**Comment by bolatovumar** [comment]
@pavlenex no, not everything is done yet (haven't had the time).

**Pull request merged**
