### PR TITLE
Fix: Warnings and view build issues during dotnet publish

### PR DESCRIPTION
**Pull request by NicolasDorier**
Without this, dotnet publish is creating executables without precompiled views, resulting in error 500 crash at runtime.

```
fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMIOMJKRR31K", Request id "0HMIOMJKRR31K:00000002": An unhandled exception was thrown by the application.
System.InvalidOperationException: The view 'APIKeys' was not found. The following locations were searched:
/Views/UIManage/APIKeys.cshtml
/Views/Shared/APIKeys.cshtml
/Pages/Shared/APIKeys.cshtml
```

This came from the `AdditionalFiles` in BTCPayServer.csproj. Strangely it was showing the problem during the build without failing it:

```
CSC : warning CS8785: Generator 'RazorSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentException' with message 'The hintName 'Components_StoreLightningBalance_Default_cshtml.g.cs' of the added source file must be unique within a generator. (Parameter 'hintName')' [/source/BTCPayServer/BTCPayServer.csproj]
```

Once fixed, it would work but dotnet publish will show the following warnings:

```
/source/BTCPayServer/Views/UIStores/_Nav.cshtml(18,198): warning CS0618: 'StoreNavPages.Integrations' is obsolete: 'Use StoreNavPages.Plugins instead' [/source/BTCPayServer/BTCPayServer.csproj]
/source/BTCPayServer/Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator/Components_StoreSelector_Default_cshtml.g.cs(580,224): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [/source/BTCPayServer/BTCPayServer.csproj]
/source/BTCPayServer/Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator/Components_StoreSelector_Default_cshtml.g.cs(603,224): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [/source/BTCPayServer/BTCPayServer.csproj]
```

So I addressed those warnings.
The `#pragma` is used as a workaround, since the warning is a bug still not fixed by microsoft https://github.com/dotnet/razor-compiler/issues/196

### CODE REVIEW

**Review by dennisreimann — APPROVED** [review]
We kept the `Integrations` one, because it might be used by plugins. I'll check this with Kukks/btcpayserver#6

**Comment by NicolasDorier** [comment]
@Kukks is it important to keep it here?

**Comment by dennisreimann** [comment]
The plugins might, but as I said, I'll check this for the PR on kukks' plugins repo.

**Comment by dennisreimann** [comment]
Just checked, kukks' plugins aren't using the `StoreNavPages.Integrations` anymore.

tACK for the build. There's one more warnign though:

`BTCPayServer.PluginPacker/Program.cs(75,30): warning CS0168: The variable 'e' is declared but never used`

**Comment by NicolasDorier** [comment]
Fixed the warning!

**Comment by dennisreimann** [comment]
Then LFG!

**Review by Kukks — APPROVED** [review]

**Pull request merged**
