### PR TITLE
Add payment link in checkout with payjoin indicator

### PR DESCRIPTION
**Pull request by Kukks**
This shows the BIP21 in the Copy tab in the invoice checkout. If the link is payjoin enabled, it shows the `user-secret` icon. Else, it shows the coin image.
image

### CODE REVIEW

**Comment by NicolasDorier** [comment]
seems good for me, I am unsure about the CSS change, if you need to change the css, it means this will not render correctly on other themes? @dennisreimann

**Comment by NicolasDorier** [comment]
Also I would say payment link should be below address.

**Comment by dennisreimann** [comment]
@NicolasDorier The checkout CSS is decoupled from the backend/admin CSS, that's also why @rockstardev and I could work in parallel on the theme updates.

Rest looks good to me and I like the proposal of moving the link below the address.

**Comment by Kukks** [comment]
moved it to below address

**Comment by NicolasDorier** [comment]
Ping @rockstardev do you see any problem with the change in CSS? I fear that it break on existing checkout themes.

**Comment by Kukks** [comment]
@NicolasDorier  just tried it

**Comment by dennisreimann** [comment]
@NicolasDorier I don't think it will be a problem, as the classes in the HTML are already used elsewhere and hence present in the CSS.

**Pull request merged**
