### PR TITLE
Increase Address max length to 512

### PR DESCRIPTION
**Pull request by sipsorcery**
Should solve #578 when deploying new BtcPay server instances with MySQL.

### CODE REVIEW

**Comment by Kukks** [comment]
You need to generate a new migration for this instead of editing an existing one. You need to annotate the c# model's property with this maxlength and generate the migration from there. 

With this, existing deployments won't notice the change and the new deployments wont get it because this only affects users who are on a version before this migration was created.

**Comment by NicolasDorier** [comment]
mmh

**Comment by NicolasDorier** [comment]
Actually I think this is fine.

**Comment by NicolasDorier** [comment]
So there is two way we can fix this:

1. Make sure we never put too much info in the Addresses column.
2. Changing the migration script (it won't break existing deployment, it will not fix current deployments, but we don't really care as they were not working anyway)

**Comment by NicolasDorier** [comment]
Also I think the problem is in the `HistoricalAddressInvoiceData`. `AddressInvoiceData` is now storing only the preimage of the payment.

**Comment by Kukks** [comment]
New deployments would use the snapshot migration as far as I remember and not the incremental ones. Can't we use data annotations like `[MaxLength(500)] ` and genertae a migration then

**Comment by NicolasDorier** [comment]
I like this one here because things working before will still work tomorrow. Your other solution might crash sqlite deployments. 

Also maybe it is better idea to either trunk the BOLT11 OR just use the payment hash

**Comment by Kukks** [comment]
closed my other pr

**Comment by Kukks** [comment]
@sipsorcery  Is it ok if I take over your PR? :)

**Comment by sipsorcery** [comment]
@Kukks sure of course. I'm a bit out of my depth with dotnet core ef any way.

**Comment by Kukks** [comment]
I think we should merge this in actually, @NicolasDorier  was right - this should work just fine. @ketominer currently has to do a bash script on nodl to fix this issue. I think he does a 1k char limit but 512 should be enough anyway

**Comment by NicolasDorier** [comment]
Will be part of https://github.com/btcpayserver/btcpayserver/issues/1224

Fixing that is actually became way harder.

**Pull request closed without merging**
