### PR TITLE
Fix Shopify parsing

### PR DESCRIPTION
**Pull request by Kukks**

### CODE REVIEW

**Comment by Giszmo** [comment]
Is this PR related to [my problems connecting with Shopify](https://github.com/btcpayserver/btcpayserver/discussions/2532)? Is there a hack around while waiting for the new release?

**Comment by NicolasDorier** [comment]
@Giszmo you are on 1.1.1 ? seems like a bug yes. I don't know yet if that's the issue this PR fix.

**Comment by NicolasDorier** [comment]
ping @Kukks maybe we broke something with shopify recently?

**Comment by Giszmo** [comment]
I'm on v1.1.1.0, yes.

What other information would be helpful to debug this?

I'll open an issue as requested on [the discussion.](https://github.com/btcpayserver/btcpayserver/discussions/2532).

**Comment by Kukks** [comment]
> Is this PR related to [my problems connecting with Shopify](https://github.com/btcpayserver/btcpayserver/discussions/2532)? Is there a hack around while waiting for the new release?

It is

**Comment by NicolasDorier** [comment]
@Giszmo I released the new version for you

**Comment by Giszmo** [comment]
Thanks for quick help! I see yellow stuff now :D
And had not sent this comment as I wanted to test it all and it all worked fine in the end.

**Pull request merged**
