### PR TITLE
Test fix

### PR DESCRIPTION
**Pull request by dennisreimann**
WIP to fix the annoying test issue on CI.

### CODE REVIEW

**Comment by dennisreimann** [comment]
The last remaining unit test failure is due to persisting problems with OkEX it seems. Shall we also exclude it and bring it back on once it's working again? I'd like to get these fixes in there, because all CI test are in a failing state right now.

@NicolasDorier @Kukks

**Comment by Kukks** [comment]
> The last remaining unit test failure is due to persisting problems with OkEX it seems. Shall we also exclude it and bring it back on once it's working again? I'd like to get these fixes in there, because all CI test are in a failing state right now.
> 
> @NicolasDorier @Kukks 

Ack

**Comment by gruve-p** [comment]
ping @eabz can polispay be removed from btcpayserver since you guys moved to polischain?

**Comment by eabz** [comment]
Yes, feel free to remove it. 
Sorry for the problems @gruve-p @dennisreimann.

**Pull request merged**
