### PR TITLE
 improve UX description

### LINKED ISSUE #5970: [Bug]: Can't import wallet file / Electrum and Sparrow
### What is your BTCPay version?

BTCPay 1.13.1

### How did you deploy BTCPay Server?

Docker

### What happened?

I Get this error when I try to import wallet file generated by Electrum or Sparrow :
"Import failed, make sure you import a compatible wallet format"

image

### How did you encounter this bug?

Select wallet file (generated by Electrum or Sparrow) then click on Continue

### Relevant log output

_No response_

### What browser do you use?

_No response_

### Additional information

_No response_

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

### PR DESCRIPTION
**Pull request by TChukwuleta**
Resolves #5970 

PR Improves wallet import instruction message

### CODE REVIEW

**Comment by NicolasDorier** [comment]
I tried 2fa, there is x1, x2 and x3. Why did you take x1?

**Comment by NicolasDorier** [comment]
I can't get the same address as electrum 2fa with this.

**Comment by TChukwuleta** [comment]
> I tried 2fa, there is x1, x2 and x3. Why did you take x1?

I took the x1 because it had extended private key value and the others didn't

**Comment by NicolasDorier** [comment]
I added a test from a wallet I exported from electrum. I can't parse is, let alone make sure it is deriving the right address.
Please look at my test

**Comment by NicolasDorier** [comment]
We support `Wallet with two factor authentication` ?

Need @dstrukt @dennisreimann quick check if it's clearer, and is showing nicely.

**Comment by TChukwuleta** [comment]
Nah.. Just standard Electrum wallet.

**Comment by NicolasDorier** [comment]
@TChukwuleta but the message says otherwise?

**Comment by TChukwuleta** [comment]
Yea, PR is now just handling the original concern which is to improve the import wallet instructions. 

Removed the 2FA implementation as it was generating a different address other than the expected receiving address

**Pull request merged**
