### PR TITLE
Use NBitcoin.BIP78 for Payjoin

### PR DESCRIPTION
**Pull request by Kukks**
Refactoring payjoin to use a separate library. This will prep the receiver side to enable batching and substitution capabilities in the future

### CODE REVIEW

**Comment by NicolasDorier** [comment]
don't break everything in 1 PR.
Preferrable approach would be to just focus on putting the client in a library in a first run, leaving all the rest as is.

Also, I would prefer if this library for now was under BTCPayServer org, like BTCPayServer.BIP78.

**Comment by NicolasDorier** [comment]
tests fail

**Comment by Kukks** [comment]
Will reopen when the sender part is merged in

**Comment by MaiHistoryCompanyLimited** [comment]
{#2145}

**Comment by Kukks** [comment]
Will revisit this later

**Pull request closed without merging**
