### PR TITLE
Tackle additional issues in #606

### PR DESCRIPTION
**Pull request by bolatovumar**
This PR tackles remaining issues in #606

### CODE REVIEW

**Comment by NicolasDorier** [comment]
@pavlenex can you give it a try?

**Comment by pavlenex** [comment]
@NicolasDorier tACK

**Comment by pavlenex** [comment]
@bolatovumar 
Any idea why the closing "X" always appears in the search even though I didn't enter search query? It should be there only if I enter the query.

https://imgur.com/a/9o8r5M0

Besides that, everything else looks good.

**Comment by bolatovumar** [comment]
@pavlenex it doesn't show up for me before i enter a query but i will take another look

**Comment by bolatovumar** [comment]
@pavlenex ok, I took a look and looks like the issue you are describing is also in the master branch and has been there for a while. If you enter a query then the X icon shows up. If you click on it, it clears the input field and disappears. However, if you manually clear out the input field the icon stays there. I can add this issue to the task list and fix it.

Also, your video has another issue. The icon is meant to appear within the input field and not below it. Looks like you are missing some CSS. I'm pretty sure I pushed updated CSS but I will double-check.

**Comment by bolatovumar** [comment]
@pavlenex alright, should be fixed now

**Comment by NicolasDorier** [comment]
@pavlenex can you test once again?

**Comment by pavlenex** [comment]
@bolatovumar it all looks good now, could be that my caching messed up with particular parts of css styling but the "x" no longer appears and is now inline.

My concern now (after clearing the cache) is that the sidebar is hidden until you click the cart icon. I'm not sure that's the best UX. 

imo, for desktop in particular it should be right away with PAY cta button, the icon click is not that intuitive and adds another step which is not really needed, what do you think? Should we:
- Show sidebar everywhere except on mobile
- Hide sidebar everywhere until icon is clicked

I'm nitpicking at this point, but it's not the UX I prefer.

**Comment by NicolasDorier** [comment]
I think the cart must be open by default as well

**Comment by NicolasDorier** [comment]
@pavlenex why you said on #606 that you don't want cart open by default on desktop and now say the reverse? :p

**Comment by pavlenex** [comment]
> 
> 
> @pavlenex why you said on #606 that you don't want cart open by default on desktop and now say the reverse? :p

Well I didn't say specifically I want it opened, I thought it would be good if it's `bigger` in size.

I misunderstood @bolatovumar's checkbox that said "Don't show cart in opened state on desktop (same as on mobile)"

**Comment by NicolasDorier** [comment]
Ok then waiting for this one to be fixed, then I will make a new version, BTCPay had tons of commits since the last one.

**Comment by NicolasDorier** [comment]
@bolatovumar can you just keep the cart open by default? I will to release new version as soon as I merge this one.

**Comment by NicolasDorier** [comment]
Merging that for now!

**Pull request merged**
