### PR TITLE
Adjust invoice pagination behavior

### LINKED ISSUE #1236: Inconsistent list pagination counts
**Describe the problem/bug**
When lists are empty (such as for invoices or payment requests) the counts on the top left don't always make sense.

**Your environment**
* Version of BTCPay Server: v1.0.3.146
* Deployment method: docker

**To Reproduce**
1. Install a fresh BTCPayServer instance
2. Click on Invoices, view counts
3. Click on Payment Requests, view counts

**Expected behavior**
Counts should display as "0 to 0 of 0"

**Actual behavior**
Counts display as "1 to 0 of 0" or "1 to 50 of 0"

### PR DESCRIPTION
**Pull request by bolatovumar**
fix #1236

### CODE REVIEW

**Comment by bolatovumar** [comment]
@NicolasDorier this should fix it. You will notice that I made more changes than strictly required to fix this bug. I made those changes because Rider kept complaining about these things in this file.

**Comment by bolatovumar** [comment]
@rockstardev makes sense, I can revisit this.

**Comment by bolatovumar** [comment]
@rockstardev alright, done. One thing I noticed is that we have similar pagination in two other places. Should we adjust those views as well to be in-line with this one?

> 1. If there are 0 results, we could go with empty string (or `0 results`, whatever looks better during implementating)

I'm showing nothing if there are 0 results

> 2. If there are less results than page size, just show `1-35`

I'm showing `1-n` if there are less than or equal to `n` number of invoices

> 3. If there are more results than page size, show `1-50, Total: 78`

Done

**Comment by rockstardev** [comment]
Sorry @bolatovumar... I was setting aside time to appreciate and comment your well implemented changes... but it's will of Emperor to yolo in. I guess you get more karma this way, so all good.

**Comment by NicolasDorier** [comment]
Sorry I have the trigger too easy. Gonna reach those pull request to 0 !

**Comment by NicolasDorier** [comment]
Should I revert that?

**Comment by rockstardev** [comment]
No, gotta reach those pull request to 0

**Comment by bolatovumar** [comment]
@NicolasDorier @rockstardev one question that's still standing here though is do we wanna standardize this behaviour on other pages which also have pagination? As it is now, this page has different pagination behavior from other pages with pagination.

**Comment by rockstardev** [comment]
@bolatovumar I would look into it - invoice page was obviously the biggest priority considering usage... if you proceed with refactoring other pages to fit standard I would be glad to review and merge.

**Comment by NicolasDorier** [comment]
I think making a custom taghelper for the pagination would be very useful.

**Comment by NicolasDorier** [comment]
relevant link https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/authoring?view=aspnetcore-3.1

**Comment by bolatovumar** [comment]
@NicolasDorier yes, I was thinking of making some reusable pagination component

**Pull request merged**
