### PR TITLE
fix file timezone and isDownload for local files temp urls

### LINKED ISSUE #834: File Storage Issues
**Describe the problem/bug**
- Timestamp of file upload is not my local time.
- Create temporary file link issues: 
    - expiry timer does not work properly
    - isDownload checkbox doesn't download the file

**Your environment**
* v1.0.3.103
* LunaNode
* FileSystem Storage Method

**To Reproduce**
1. Upload file
2. Get Temp Link > Generate

**Expected behavior**
1. Choose expiry time 10 seconds
2. isDownload box checked

**Actual behavior**
1. Link doesn't expire after 10 seconds
2. Doesn't download file when box is checked

### PR DESCRIPTION
**Pull request by Kukks**
closes #834

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Can you rebase and retrigger the test?

**Comment by britttttk** [comment]
The temp link still wasn't working for me in regtest but time and download works.

**Comment by Kukks** [comment]
temp link should download now but with local filesystem, I cannot generate links that expire

**Comment by NicolasDorier** [comment]
@Kukks maybe there should have an error if somebody attempt to create a temp link on filesystem ?

**Comment by britttttk** [comment]
Error would be good if possible... Otherwise i'm documenting this feature and can add a note there. @Kukks Can you please make the checkbox more user friendly like: "Download File" or "Download File Link" :)

**Comment by NicolasDorier** [comment]
Closing this, @Kukks would be great to have an actual error if temp file is not supported by provider though.

**Comment by Kukks** [comment]
I will work on a new PR that allow temp links for local filesystem option

**Pull request merged**
