### PR TITLE
Update lightning-charge to v0.4.19

### PR DESCRIPTION
**Pull request by kaloudis**
Changes the default units from mBTC to sats

### CODE REVIEW

**Comment by Kukks** [comment]
Can you test and see that it still works OK?

**Comment by Kukks** [comment]
This is only for our tests too though, you'll want to do it on the docker repo if you want everyone else to have this bump :)

**Comment by Kukks** [comment]
This is only for our tests too though, you'll want to do it on the docker repo if you want everyone else to have this bump :)

**Comment by NicolasDorier** [comment]
tests pass will update docker

**Comment by NicolasDorier** [comment]
done

**Pull request merged**
