### PR TITLE
[Refactor] Move SQL classes in their own assembly

### PR DESCRIPTION
**Pull request by NicolasDorier**
This PR attempt to move SQL classes in a separate assembly.

Entity Framework, for each migration, generate a snapshot of the database and generate more and more classes which never actually need to be recompiled.

If those classes are in BTCPayServer, then any change to a file to this project will trigger all the entity framework classes to be recompiled as well. This is a major waste of time which impact the coding/debug feedback loop.

I still have to check the impact of having changing the namespace of some types on migrations.

### CODE REVIEW

**Comment by Kukks** [comment]
This is going to kill my pull requests with conflicts lol

**Comment by NicolasDorier** [comment]
I don't think so, if you don't change the DB schema

**Comment by NicolasDorier** [comment]
if it is too much issue, I might just change the migrations, not the data classes.

**Comment by NicolasDorier** [comment]
Ok `13,277` less lines. @Kukks from now Entity Framework classes should be in this new assembly.

**Pull request merged**
