### PR TITLE
1.4.0 Final Polish

### PR DESCRIPTION
**Pull request by dstrukt**
I'm going to be updating this PR a bit more, but I wanted to get it up so @dennisreimann could potentially work in parallel.

Will post screenshots in a bit.

- Adds new icons on left sidebar
- Removes some icons from Account modal
- Updates "Apps" update title

Remaining things @dstrukt:
- [x] POS icon improvement
- [x] Store Icon improvement
- [x] Notification icon & size improvement

Few things left @dennisreimann to close out (https://github.com/btcpayserver/btcpayserver/issues/3180):
- [x] Add store icon to the StoreSelector dropdown
- [x] Add ellipses on long display App titles (see example below) for limited char length
image
- [x] Adjust "off" color state for the wallet/lightning, red to yellow for "pending", red only for error (see Figma)
- [x] Right align the Theme icon on the Account modal (see Figma), no worries if we don't do this one
- [x] Adjust "off" wallet/lightning state color to grey @dennisreimann 
- [x] Make the Payout top on-chain/off-chain buttons match the Lightning Setup pills
- [x] H2 header "Server Settings" with `mb-4` or `mb-5` padding above the tabbed navigation on three views: Server Settings, Account Settings, Store Settings

### CODE REVIEW

**Comment by dennisreimann** [comment]
@dstrukt I just rebased and force-pushed, so you should pull before continuing here. Also: Last three items of my TODO checked now :)

**Comment by dstrukt** [comment]
Fantastic updates! 

Going to do a bit of testing with this + my icon updates and we should be good to close this one.

**Comment by dstrukt** [comment]
Added some quick and simple Lightning + Lightning Settings formatting to make it a little more consistent.

**Comment by pavlenex** [comment]
Have we considered max width on larger screens for the final push?

**Comment by dennisreimann** [comment]
> Have we considered max width on larger screens for the final push?

I've now removed the max-width container, but we still need to go through the views to properly handle this now.

**Comment by dennisreimann** [comment]
@dstrukt rebased once more and checked all my TODOs.

But as I said we now still need to account for the removed max-width.

**Comment by dstrukt** [comment]
Will be able to address the remaining TODOs in (https://github.com/btcpayserver/btcpayserver/pull/3346) once we merge this PR.

Will get the icon asset wrapped so we can close.

**Comment by dstrukt** [comment]
I still like the current iteration of the P.O.S icon. 

I'll keep messing around and if I improve anything, it will be a tiny PR today or tomorrow.

This PR is GTG!

**Pull request merged**
