### PR TITLE
Added refund fields to invoice export

### PR DESCRIPTION
**Pull request by rustywave**
Draft-only, will wait for feedback before proceeding.

Notes:
- Only first refund is included, if available. There can be multiple refunds, however. See ticket for clarification.
- .IncludeRefunds not added into InvoiceQuery call because does not filter the list
- Added as strings; there are a mix of number and string for currency fields. Can change if needed
- Added to end of list in order to not break client-side integrations
- If no refunds, field will be empty instead of 0 to indicate no refund present

image

#3597

### CODE REVIEW

**Review by Kukks — CHANGES_REQUESTED** [review]
Good start, but:
* You need to also check the payouts inside the pull payment and see if the refund has been done. You can use 
```
var progress = pullPaymentHostedService.CalculatePullPaymentProgress(pp, DateTimeOffset.UtcNow);
 ```

 to get the amount refunded so far:  `var remaining = progress.Limit - progress.Completed - progress.Awaiting;`

**Comment by rustywave** [comment]
Good call -- I actually did it that way because it looks like the invoice is tagged with `Refund` on the list view as soon as a refund is issued. Should I add extra fields in the export to account for any of this? If not, I will proceed with what you have above. Also, left some comments on the ticket that may or may not need clarification.

**Comment by rustywave** [comment]
Okay I think I need to add the refunds as separate line items -- you can have multiple payments but currently only one refund per invoice. It kind of doesn't make sense to add the refund as a column because refunds are not tied to payments.  Will see what I can do here and reply back.

**Comment by Kukks** [comment]
This is indeed problematic. I think we need to rethink this.
The main problem is that the export is not of invoices, but of payments, so
refunds may not entirely make sense on that context. Perhaps a better
solution is a new export specifically around invoices

**Comment by rustywave** [comment]
I started down the road of adding refunds as a separate line item but then realized refunds have multiple payouts (from your suggestion)...I think it makes sense to list payouts out if we are listing payments out. But I agree with your point -- this isn't exactly an invoice export now and it's probably best to clarify what is desired for this.

**Pull request closed without merging**
