### PR TITLE
Fix bug with already used colors being used first for new tx labels

### LINKED ISSUE #2072: Unique wallet tx label colors
**Is your feature request related to a problem? Please describe.**
The default labels (app, payment-request, etc.) use certain colors for labels. When I make custom labels, it uses those colors again before creating new unique label colors. 

**Describe the solution you'd like**
When creating a new custom label for a tx, I would like it to use a color that is not in use for another label.

**Sketch/Image/Wireframe/Mockup**
image

**Additional context**
In the image above, I only get a new color on the third custom label. I wish it was on the first.

### PR DESCRIPTION
**Pull request by bolatovumar**
Close #2072.

# Before

When creating a new label sometimes an already used color is picked first before a new color is picked.

# After

New and previously unused color is always picked when creating a new label if it's available.

### CODE REVIEW

**Comment by Kukks** [comment]
I'm not sure if adding more hardcoded colors is the way to go. I wanted to try to generate a color deterministically from the label text but not sure if it would work in the real world

**Comment by pavlenex** [comment]
> 
> 
> I'm not sure if adding more hardcoded colors is the way to go. I wanted to try to generate a color deterministically from the label text but not sure if it would work in the real world

That's sounds overly complicated and not really necessary, if you guys really want different colors, adding a way to add color hex or color picker is way more simple and effective. The way GitHub labels work is good balance between usability and simplicity imo.

**Comment by bolatovumar** [comment]
> > I'm not sure if adding more hardcoded colors is the way to go. I wanted to try to generate a color deterministically from the label text but not sure if it would work in the real world
> 
> That's sounds overly complicated and not really necessary, if you guys really want different colors, adding a way to add color hex or color picker is way more simple and effective. The way GitHub labels work is good balance between usability and simplicity imo.

The way I extended the color list was to search for a list of the most contrasting colors and add the ones we do not already have. I made sure not to add any colors which didn't contrast enough with existing colors and the color of the text and the "x" icon.

**Comment by dennisreimann** [comment]
Regarding contrast: We need to ensure it also works in dark mode and, at least 8 and 9 might be a problem there. Another thing is the text color on light background: "invoice", 6 and 12 could use a dark font color instead.

**Comment by britttttk** [comment]
> I'm not sure if adding more hardcoded colors is the way to go.

I agree, I think that random would be better

**Comment by bolatovumar** [comment]
Alright, I removed the new colors. The only color change I kept is updating `#000000` to `#cdcdcd`.
Now all this PR does is fix the issue @britttttk was having.

**Review by dennisreimann — APPROVED** [review]

**Review by Kukks — APPROVED** [review]

**Pull request merged**
