### PR TITLE
Update HomeController.cs

### PR DESCRIPTION
**Pull request by Eskyee**
live share collaboration rockstardev channel fix

### CODE REVIEW

**Comment by NicolasDorier** [comment]
what does it fix

**Comment by Eskyee** [comment]
shows the user invoice entries in their local timezone.

**Comment by bolatovumar** [comment]
@Eskyee this patch doesn't seem to be actually doing that though

**Comment by Eskyee** [comment]
@rockstardev if u can remind me what this change  was On our live share session!! Since we made a few fixes !! On that session!! Cheers

**Comment by rockstardev** [comment]
@Eskyee timezone was in different file... when I have time I'll revisit and co-author you on commit if I fix.

**Pull request closed without merging**
