### PR TITLE
Re-add versioning for btcpay.js

### PR DESCRIPTION
**Pull request by dennisreimann**
As discussed with @Kukks – let me know if this works or I have overlooked something here.

### CODE REVIEW

**Comment by Kukks** [comment]
Does it work ok if the js is referenced without the version parameter

**Comment by dennisreimann** [comment]
As far as I checked it works for both cases, but please have a look as I don‘t know about everything that the script is supposed to do/scenarios to work in.

**Comment by NicolasDorier** [comment]
@Kukks, merge it when you are satisfied.

**Comment by Kukks** [comment]
I forgot but we actually have a selenium test that tests the modal so this is fine

**Pull request merged**
