### PR TITLE
 Improve recovery seed backup page

### PR DESCRIPTION
**Pull request by TChukwuleta**

### CODE REVIEW

**Comment by NicolasDorier** [comment]
can you make screenshots of the change

**Comment by TChukwuleta** [comment]
Hello @NicolasDorier 

I am currently working on this issue:
https://github.com/btcpayserver/btcpayserver/issues/4304

This was what was existing 
image

This is the updated page according to what is in the mock
image


However, the Selenium test is failing. Is there something I am doing that I am not meant to do?

**Comment by dennisreimann** [comment]
Sorry, I wanted to push some adjustments to your PR, but I messed it up and GitHub closed the PR :(

This has happened before and I think the reason is that it does not work well if PRs are opened from the master branch of the fork. Sorry for the hassle, I didn't intend to close this.

As I cannot push directly to your fork, I pushed it to mine: https://github.com/dennisreimann/btcpayserver/tree/wallet-recovery-improvement

Can you create a new branch on your fork, cherry-pick or merge the two commits (one by you and one by me) that are now rebased with main master, so that the tests should also work again? Let me know if I can assist — once more, sorry!

**Comment by TChukwuleta** [comment]
Thank you so much @dennisreimann , yea I was able to cherry-pick both commits and raise a new PR for it
https://github.com/btcpayserver/btcpayserver/pull/4793

All tests passed. Thank youu

**Pull request closed without merging**
