### PR TITLE
Bitnob rate provider

### PR DESCRIPTION
**Pull request by TChukwuleta**
#5699 

Implement Bitnob rate provider among other rate providers to expand support for African currencies

### CODE REVIEW

**Comment by NicolasDorier** [comment]
@TChukwuleta is there any currency where this exchange should be recommended? If so, you should also add it in `StoreBlob.RecommendedExchanges`.

**Comment by TChukwuleta** [comment]
Hey @NicolasDorier  


I can't say for the others, I have only done interaction with NGN, and even with that, BTC is usually benchmarked against USD and not NGN

**Comment by NicolasDorier** [comment]
@TChukwuleta so you don't think this should be the recommended exchange for NGN?

**Comment by TChukwuleta** [comment]
I probably misunderstood the question. Yea.. it should be

I'd add it to the recommendaed exchange and update the PR

**Comment by TChukwuleta** [comment]
@NicolasDorier added Bitnob as recommended exchange for NGN

**Pull request merged**
