### PR TITLE
Store branding: Unify public pages

### LINKED ISSUE #3842: Add support for logo white-labeling on Payment Requests, Invoices, Receipts, Pull Payments, etc...
- [ ] Payment Request
- [x] Checkout Invoices
- [x] Receipts (https://github.com/btcpayserver/btcpayserver/pull/4435)
- [ ] Pull Payments

As an admin... I'd like to be able to promote my brand with more than just my website, but with the POS front-end, Payment Requests, etc...

Ideally this functionality would enable an admin to upload their brand/store's logo in the `Store Settings > General` that we would then add to Invoices, Payment Requests, Pull Payments, and (now)Receipts .. and wherever potentially applicable, possibly as a default or a switch on/off functionality .. working this into mocks as well.

This Issue ties into the larger initiative of making files easier to manage as well, but after configuring your File system (would prompt if you haven't), you could simply upload your logo and we'll handle the rest.

We would still keep "Powered by BTCPay Server" at the bottom on all of these views.

Curious to hear other's thoughts.

### PR DESCRIPTION
**Pull request by dennisreimann**
Here we are applying the store branding introduced in #4527 across all the customer-facing views. We're also unifying them and applying the same header/footer/spacings across those views.  

Closes #3842.

# Invoice and Receipt

invoice

receipt

# Payment Request and Pull Payment

payment-request

pull-payment

# Point of Sale

pos-static

pos-cart

print

pos-keypad

# Crowdfunding

crowdfund

### CODE REVIEW

**Review by dstrukt — APPROVED** [review]
LGTM!

We'll polish up individual views and catch the few inconsistencies (pull payments, payment requests, etc..) as discussed in the design call.

**Comment by pavlenex** [comment]
Looking sexy! Concept ACK.

**Comment by dennisreimann** [comment]
Yeah, it's also a great validation of the design system efforts we made that users can achieve this with ~30 lines of CSS. 👍

**Comment by dennisreimann** [comment]
@Kukks Can you give this q technical review? Here are the key points:

- Extract CSS from checkout.css and make it available everywhere by putting it into site.css
- Introduce partials for the common store header and store footer
- Add `StoreName`, `BrandColor`, `CssFileId` and `LogoFileId` to the view models that need them
- Add `LayoutHeadStoreBranding` to the public views for `BrandColor` and `CssFileId` to take effect
- Unify the page wrapper and make those views at least 100% height, so that the footer sticks to the bottom

**Review by NicolasDorier — APPROVED** [review]

**Pull request merged**
