### PR TITLE
Add POS Data to Invoice UI

### PR DESCRIPTION
**Pull request by Kukks**
This PR adds basic displaying of the pos data in the invoice details screen.

### CODE REVIEW

**Comment by Kukks** [comment]
It passes now @NicolasDorier  :)

**Comment by NicolasDorier** [comment]
Can you hijack one test somewhere and use this and check against the resulting view model?

**Comment by Kukks** [comment]
added in a test

**Comment by NicolasDorier** [comment]
Can you call `Invoices()` and check against the view model. It will cover more.

**Comment by Kukks** [comment]
added some more @NicolasDorier

**Comment by NicolasDorier** [comment]
Never use `ContinueWith` there is no reason to do so, `async/await`  is always better.

**Pull request merged**
