### PR TITLE
Code analysis

### PR DESCRIPTION
**Pull request by jesterhodl**
Hi, this is my first PR to BTCPayServer. I decided to learn a bit about the code base by upgrading the old code analysis packages to the ones in .NET SDK, called NETAnalyzers.
This PR does two things:
- Removes obsolete analyzer packages
- Enables NETAnalyzers on the whole project (but keeps them silent)
   This allows the developers to effectively set <AnalysisMode> in the individual .csproj files to minimum, recomended or all to see CA findings. Or not, and keep it quiet
- Fixes:
  - [CA1834: Use StringBuilder.Append(char) for single character strings](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1834)
  - [CA1847: Use string.Contains(char) instead of string.Contains(string) with single characters](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1847)

If this is OK to do, We would have a good base for me and other devs to find good things to fix. Some of them performance related, some security, etc.

### CODE REVIEW

**Comment by jesterhodl** [comment]
Looks like changing interface names broke the build of the tests. Any advice on how to proceed with such a change?

**Comment by NicolasDorier** [comment]
@jesterhodl do not change interface names at this point. You can put some `#pragma` to ignore the warning I believe.

**Comment by jesterhodl** [comment]
Ok, I removed the interface name and put 2 other fixes from the performance category.
How's that?

**Review by dennisreimann — APPROVED** [review]
tACK

**Pull request merged**
