### PR TITLE
Add links to API documentation for better discovery

### PR DESCRIPTION
**Pull request by NicolasDorier**
image

### CODE REVIEW

**Review by Kukks — CHANGES_REQUESTED** [review]
I don't think the side navigation menu item fits, the other one is good though.

**Comment by NicolasDorier** [comment]
@Kukks please suggest something else then, the docs is currently hidden, that's worse.

**Comment by Kukks** [comment]
> @Kukks please suggest something else then, the docs is currently hidden, that's worse.

Maybe in the footer next to version number and also in Integrations page in the store?

**Comment by Kukks** [comment]
@pavlenex @dennisreimann any thoughts?

**Comment by NicolasDorier** [comment]
Nobody look at there... Ping @dstruck

**Comment by NicolasDorier** [comment]
Ping @dstrukt thoughts?

**Comment by Kukks** [comment]
> Nobody look at there...

Yeah but arguably, nobody will look at the User navigation to find the link for API docs. I think maybe under store navigation would work better if anything

**Comment by dennisreimann** [comment]
The way we do it everywhere else is with the help/question mark icons …

Bildschirmfoto 2020-12-11 um 09 08 30

Bildschirmfoto 2020-12-11 um 09 07 56

Bildschirmfoto 2020-12-11 um 09 08 13

If we just want to link to the docs, I think we should be conssistent here.

I don't fully get the issue though: Is it just that we need to provide the link or should we be offering more guidance/context for the users here? What sparked this issue?

**Comment by pavlenex** [comment]
The way to fix this imo is:

1. Have a tooltip - ACK.
2. Once we have a dashboard #1711 make it more prominent, I am not a fan of a sidebar display for a link.
3. We can display Integrations and API better in our docs on a homepage [#545](https://github.com/btcpayserver/btcpayserver-doc/pull/545) once we figure out how to improve search algo in docs but also on our website.

**Comment by dennisreimann** [comment]
So the quickfix would be to do it like on the Payment Request list (first screenshot): Keep the text and link to the docs via the icon and move the botton up to sit between the intro text and the list. :)

**Comment by NicolasDorier** [comment]
@dennisreimann @pavlenex I don't like the tooltip, this normally link to user readable documentation, not API. This would be confusing.

**Comment by dennisreimann** [comment]
But then again, what kind of problem are we trying to solve? Doesn't sound like just providing the link helps in that regard. I mean, we'd be throwing people to the API docs where they might feel lost too, because that's likely too technical.

**Comment by pavlenex** [comment]
@NicolasDorier Can we just make it more prominent in the API keys section and then add the links to website and docs. I assume people are more likely to find docs that way?

**Comment by NicolasDorier** [comment]
@dennisreimann the point we want to solve is that currently nobody know the Greenfield API exists, because there is no link to it.

**Comment by dennisreimann** [comment]
Ok, but then let's motivate the usage a bit more and offer an introduction paragraph, that explains the API and it's use case and links to the relevant docs:

The [BTCPay Server Greenfield API](https://docs.btcpayserver.org/API/Greenfield/v1/) offers programmatic access to your instance. You can manage your bTCPay Server (e.g. stores, invoices, users) as well as automate workflows and integrations (see some [use case examples](https://docs.btcpayserver.org/GreenFieldExample/). For that you need the API keys, which can be generated here. Find more information in the [API authentication docs](https://docs.btcpayserver.org/API/Greenfield/v1/#section/Authentication).

**Comment by NicolasDorier** [comment]
Removed from the navbar, added your text. We can improve the rest later.

**Comment by dstrukt** [comment]
I missed this one.

Will take note to make this more prominent in places where it makes sense as well, dashboard, etc..

Agree with the approach @dennisreimann recommended for the time being.

**Pull request merged**
