### PR TITLE
Add All time to the Time filter,  PlanB Assignment

### PR DESCRIPTION
**Pull request by jessmzp**
Improved filter iteration #5156:  

- [x] All Time should be added to the Time filter, it's the default, but you can't return back to it after an option has been selected

Work in progress: Clear All funtionality

Screenshot 2024-12-20 at 12 02 53 PM

All Time filter implementation is completed, Clear all funtionality is still in progress and could be a good starting point, due to time constraints I am submitting this work in progress, I am willing to continue working on it to contribute to the project.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Thanks! Can you cleanup the code in comments that you added?

**Comment by jessmzp** [comment]
@NicolasDorier I have updated it, and during the process, a question came up that I hadn't realized: At the beginning, when nothing has been selected, should _All time_ be selected by default when the dropdown opens, or should it stay unselected until an option is chosen? Thanks, I look forward to your response.

Also, in the near future, I hope to continue working on creating the _Clear All_ button for the filters and make it work correctly.

Screenshot 2024-12-22 at 8 00 47 PM

**Comment by NicolasDorier** [comment]
Rebased and added [f846a43](https://github.com/btcpayserver/btcpayserver/pull/6514/commits/f846a43beea9509049af84f39e955cf58f89a3d9) so it is shown toggled as default.

A Clear All button is a good idea, but better in different PR yes.

**Comment by NicolasDorier** [comment]
@jessmzp I am reverting this one, it seems @dennisreimann  isn't too on board with it, check https://github.com/btcpayserver/btcpayserver/pull/6519

**Pull request merged**
