### PR TITLE
Sign with NBX Seed

### PR DESCRIPTION
**Pull request by Kukks**
Builds on #1212 

This only shows if the metadata is available.
image

### CODE REVIEW

**Comment by pavlenex** [comment]
I approve the use-case, but I'm a bit scared with what we have in the UI for the `Sign with...` will get out of control at some point and is a bit too much for normies to handle. It's somehow getting unorganized and confusing.

This is not a comment on this PR in particular, but does anyone have an idea how we can better present this in the UI? Normie goes to wallet, wants to send and then sees bunch of options they don't understand and gets overwhelmed.

**Comment by Kukks** [comment]
@pavlenex  it does not show if the seed isn't available

**Comment by pavlenex** [comment]
Ah, I missed that one, though my comment is not directly related to the PR, but to how we handle the UX here in general, I'll open an issue if I have a better idea of how to display these, thanks for clarifying.

**Comment by NicolasDorier** [comment]
can you fix the conflicts?

**Pull request merged**
