### PR TITLE
Fix P2SH-P2WPKH case for Payjoin (Fix #1500)

### LINKED ISSUE #1500: Invoices tab incorrectly marks payjoin to p2sh-p2wpkh as non-payjoin
**Describe the problem/bug**
When performing payjoin with p2wpkh, Invoices tab marks it correctly. With p2sh-p2wpkh it says it is paidOver with the amount of my payjoin utxo. (See image below, each wallet started with 1 UTXO of 0.1337 BTC size and it shows payment for 0.1337 + the actual invoice value)

**Your environment**
* Version of BTCPay Server: Github commit 7adaa14

**To Reproduce**
1. Create invoice with store that has p2sh-p2wpkh hot wallet, at least one utxo, and payjoin enabled.
2. Perform payjoin to pay the invoice.
3. Open invoice tab
4. See it was paidOver and it was marked as paying utxo value extra.

**Expected behavior**
It should be marked as payjoin and not paidOver. (see p2wpkh example in image below)

**Actual behavior**
It is marked paidOver  (see p2sh-p2wpkh example in image below)

**Screenshots/Links**
範囲を選択_001

### PR DESCRIPTION
**Pull request by NicolasDorier**
Ping @Kukks you may want to add a happy path test if you want to support P2SH wrapped. This is not the only bug that did not get caught by the test suite for P2SH.

### CODE REVIEW

**Comment by junderw** [comment]
checking right now. Will get results if it fixes the problem in about 10-15 minutes

**Comment by junderw** [comment]
`InvalidOperationException: The psbt should be finalized with witness information`

```
fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HLV936V6SLKI", Request id "0HLV936V6SLKI:00000001": An unhandled exception was thrown by the application.
System.InvalidOperationException: The psbt should be finalized with witness information
   at BTCPayServer.Services.PSBTExtensions.GetInputsScriptPubKeyType(PSBT psbt) in /root/btcpayserver/BTCPayServer/Services/PayjoinClient.cs:line 23
   at BTCPayServer.Payments.PayJoin.PayJoinEndpointController.GetExpectedHash(PSBT psbt) in /root/btcpayserver/BTCPayServer/Payments/PayJoin/PayJoinEndpointController.cs:line 491
   at BTCPayServer.Payments.PayJoin.PayJoinEndpointController.Submit(String cryptoCode) in /root/btcpayserver/BTCPayServer/Payments/PayJoin/PayJoinEndpointController.cs:line 459
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /root/btcpayserver/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 77
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /root/btcpayserver/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 31
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by junderw** [comment]
newPsbt is made from newTx
newTx inputs' witness scripts are made empty.

```
            foreach (var input in newTx.Inputs)
            {
                input.WitScript = WitScript.Empty;
            }
```

**Comment by junderw** [comment]
I tried this and it got the same error.

https://github.com/junderw/btcpayserver/commit/7c766360e32f2ff0b732d2ca4135642856322cd7

**Comment by Kukks** [comment]
@NicolasDorier  added the test

**Comment by junderw** [comment]
This also did not work, same error as above:

https://github.com/junderw/btcpayserver/commit/acf1426aed53f9dcdb2ad18713fe7f8c08270702

**Comment by Kukks** [comment]
Fixed in PR #1502

**Pull request closed without merging**
