### PR TITLE
Fixed a typo in README.md.

### PR DESCRIPTION
**Pull request by Spixmaster**
Take my huge contribution.

### CODE REVIEW

**Review by dennisreimann — APPROVED** [review]

**Comment by dennisreimann** [comment]
Thanks for spotting and fixing this!

**Comment by Spixmaster** [comment]
Ich danke Ihnen, Herr Reimann.

**Comment by dennisreimann** [comment]
Please reopen, we need to merge it ;)

**Comment by Spixmaster** [comment]
@dennisreimann I needed to create a new pull request #2331.

**Pull request closed without merging**
