### PR TITLE
Add Stripe Support ( credit card )

### PR DESCRIPTION
**Pull request by xpayserver**

### CODE REVIEW

**Comment by mariodian** [comment]
Can't launch it (`dotnet run --launch-profile Bitcoin -p "BTCPayServer/BTCPayServer.csproj"`) even on a fresh install without existing data:

````
Configuration/BTCPayServerOptions.cs(6,20): error CS0234: The type or namespace name 'Common' does not exist in the namespace 'BTCPayServer' (are you missing an assembly reference?) [/Users/mariodian/Source/Bitcoin/btcpayserver-xpay/BTCPayServer/BTCPayServer.csproj]
Payments/PaymentTypes.cs(2,45): error CS0234: The type or namespace name 'Payments' does not exist in the namespace 'BTCPayServer.Services.Altcoins.Stripe' (are you missing an assembly reference?) [/Users/mariodian/Source/Bitcoin/btcpayserver-xpay/BTCPayServer/BTCPayServer.csproj]
Services/Altcoins/Stripe/StripeService.cs(6,20): error CS0234: The type or namespace name 'Common' does not exist in the namespace 'BTCPayServer' (are you missing an assembly reference?) [/Users/mariodian/Source/Bitcoin/btcpayserver-xpay/BTCPayServer/BTCPayServer.csproj]
Services/Altcoins/Stripe/StripeService.cs(12,45): error CS0234: The type or namespace name 'Payments' does not exist in the namespace 'BTCPayServer.Services.Altcoins.Stripe' (are you missing an assembly reference?) [/Users/mariodian/Source/Bitcoin/btcpayserver-xpay/BTCPayServer/BTCPayServer.csproj]
Services/Altcoins/Stripe/StripeService.cs(16,7): error CS0246: The type or namespace name 'Stripe' could not be found (are you missing a using directive or an assembly reference?) [/Users/mariodian/Source/Bitcoin/btcpayserver-xpay/BTCPayServer/BTCPayServer.csproj]
Services/Altcoins/Stripe/StripeService.cs(17,7): error CS0246: The type or namespace name 'Stripe' could not be found (are you missing a using directive or an assembly reference?) [/Users/mariodian/Source/Bitcoin/btcpayserver-xpay/BTCPayServer/BTCPayServer.csproj]
Services/Altcoins/Stripe/StripeService.cs(27,26): error CS0246: The type or namespace name 'StripePaymentMethodHandler' could not be found (are you missing a using directive or an assembly reference?) [/Users/mariodian/Source/Bitcoin/btcpayserver-xpay/BTCPayServer/BTCPayServer.csproj]
Services/Altcoins/Stripe/StripeService.cs(34,13): error CS0246: The type or namespace name 'StripePaymentMethodHandler' could not be found (are you missing a using directive or an assembly reference?) [/Users/mariodian/Source/Bitcoin/btcpayserver-xpay/BTCPayServer/BTCPayServer.csproj]
Services/Altcoins/Stripe/StripeService.cs(229,20): error CS0246: The type or namespace name 'StripePaymentData' could not be found (are you missing a using directive or an assembly reference?) [/Users/mariodian/Source/Bitcoin/btcpayserver-xpay/BTCPayServer/BTCPayServer.csproj]

The build failed. Fix the build errors and run again.
````

Is there something extra I need to do?

**Comment by pavlenex** [comment]
concept NACK. It's been discussed quite a few times that BTCPay Server is cryptocurrency payment processor and that adding any sort of fiat gateaway would defeat it's purpose. We had a discussion regarding PayPal as well.

Adding a TTP into the software is not something I am comfortable with.

**Comment by Eskyee** [comment]
Credit cards 💳 Don’t like this idea... & I agree with pav.

**Comment by mariodian** [comment]
I think CCs are fine especially when BTCPay supports tons of shitcoins already. It doesn't have to be enabled by default.

Also, I can see this could be beneficial for vendors that could save time and money dealing with integrations of numerous payment systems. It could also help with BTCPay adoption for the very same reason.

As an eshop owner, I'd gladly just run BTCPayServer with Stripe support over separate modules for each payment method. 

The question is what are the legal implications of supporting a banking payment system?

**Comment by NicolasDorier** [comment]
need to be rebased

**Comment by NicolasDorier** [comment]
After ETH integration, Stripe... you'll make me fired if you continue.

**Comment by mariodian** [comment]
> After ETH integration, Stripe... you'll make me fired if you continue.

I think bitcoin maxis prefer CCs over ethirium :P

**Comment by pavlenex** [comment]
I am really tired of "it's not by default" being the excuse for anything we're adding recently.

**Comment by Zaxounette** [comment]
For what it's worth, concept NACK on my part.

You need to imagine, on top of the other comments above, the legal implications.
Not only for an individual user using BTCPay Server, but also for a hosting provider if this is implemented.

KYC/AML and all that nasty stuff could be required just because one build of the possible builds includes a CC payment rail.

**Comment by NicolasDorier** [comment]
> Also this may be against Stripe ToS like it was in PayPal's case.

Probably true, but not our problem, that's merchant and stripe/paypal problem. If anything this will convince merchant to not use fiat.

**Comment by knocte** [comment]
IMO this is about positioning BtcPayServer as a payment solution at the same level as the others. If BtcPayServer is only a crypto-payment solution, it will be considered niche. If BtcPayServer is a payment solution that has similar feature sets as others in the market, plus cryptocurrency, it will start getting huge adoption.

Another matter is that BtcPayServer itself should encourage its users (merchants) to increase the price of the goods when CCs are used (which could be masquerade as a "discount" when paying with crypto).

**Comment by pavlenex** [comment]
TTP should not be introduced in a software of decentralized and trust-less nature. It would be a shame if this gets merged. Merchants already have various gateaways for fiat, there's no need to pollute the software and introduce a security/privacy risk.

**Comment by Eskyee** [comment]
https://en.m.wikipedia.org/wiki/Stripe_(company)   😂 Satoshi would laugh 😆 about this.  Banks are dinosaurs

**Comment by britttttk** [comment]
concept nack - IMO this feature is better suited for a fork. [Looks like there already is one](https://xpayserver.com/apps/2bpouNtWkK5CcnBm7H3Ej3FPZuoA/pos). Stripe is closed source, kyc, that [lists bitcoin under restricted business activity?](https://stripe.com/restricted-businesses). Maybe I'm reading their "terms" incorrectly but accepting stripe with btcpay for a few merchants who want to run the altcoin build doesn't really make btcpay any less niche IMO.

Not enabled by default doesn't mean that users will not blame btcpay when things are broken or insecure. Average users don't know what separate build means.. I think it's actually a bit cool I just think it's kind of a sellout move.

**Comment by knocte** [comment]
So let me get this straight, you guys think that Kraken getting a banking license is a bad thing? Sometime you need to work from within the system to be able to blow it up.

If BtcPayServer doesn't integrate this officially, Strike will eat its lunch; there's a reason they are having success: they want non-bitcoiner's dollars too (which you could convert to crypto with an exchange gateway).

**Comment by britttttk** [comment]
I would support this feature if the following things existed:
- How do existing merchants switch their build. Please document it. I won't be doing it and users are [already confused](https://github.com/btcpayserver/btcpayserver/issues/1904). 
- BTCPay merchants can [collect more information than customer email](https://github.com/btcpayserver/btcpayserver/issues/863). If this is something that a btcpay user needs to develop as a custom solution, then surely they are technically capable to develop their own fiat payment integration.
- There is a way for customers to [contact the merchant](https://support.stripe.com/questions/refund-requests-for-a-purchase-made-through-a-business-using-stripe#:~:text=Stripe%20is%20unable%20to%20issue,out%20to%20the%20business%20directly.) when this payment method is available. I will not respond to users asking about chargeback and fraud and I have no intention of ignoring users looking for help. 
- Explanation on how it's secure and adding this information to the PR and or documentation for users to be able to make informed decisions about the safety of the software for themselves and their customers providing sensitive data to a site using btcpay. Telling users it's safe and secure to pay a Bitcoin address shown by btcpay is completely different than telling users it's safe to give your credit card information to anyone with a btcpay (looking) invoice. Hence my fork comment. 

Like I said I think it is quite a COOL FEATURE and easy for merchants to pair with stripe and can simplify things but whatever happened to forking projects when you want to rebrand them?

>you guys think that Kraken getting a banking license is a bad thing? 

you think that allowing people to pay with visa, mc & amx in btcpay is going to cause the system to be able to blow it up.?

**Comment by pavlenex** [comment]
> So let me get this straight, you guys think that Kraken getting a banking license is a bad thing? Sometimes you need to work from within the system to be able to blow it up.
> 
> If BtcPayServer doesn't integrate this officially, Strike will eat its lunch; there's a reason they are having success: they want nocoiner's dollars too (which you could convert to crypto with an exchange gateway).

How is Kraken getting a banking license related to BTCPay Server? How is having a separate fiat-fiat gateway "working within the system"?

> lists bitcoin under restricted business activity?.

The fact that Bitcoin is against Stripe's ToS speaks a lot. Merchants enabling this integration probably won't know this and there may be a big risk of getting their funds frozen by a TTP.

**Comment by nvk** [comment]
ACK, retailers need to get paid.

**Comment by knocte** [comment]
> The fact that Bitcoin is against Stripe's ToS speaks a lot. Merchants enabling this integration probably won't know this and there may be a big risk of getting their funds frozen by a TTP.

Actually, if I was a merchant, this would indeed concern me. Then maybe the best approach is integrate credit-card payments but only when converting directly to crypto after the purchase, maybe integrating Strike or Breez for this.

**Comment by dstrukt** [comment]
While I understand the arguments, it's a conceptual NACK from me.

Better suited for a fork or something maintained by others.

**Comment by Giszmo** [comment]
BtcPayServer originally went on a mission to make BitPay obsolete and accomplished that mission. Does BitPay accept CC? Wonder why not.
Screenshot from 2020-09-18 23-52-13

That said, as a user I wouldn't be offended by an option being available to activate some TTP. If it's controversial it should be available as a module.

**Comment by justinmoon** [comment]
I ran a business on BTCPay for a year and having to build two integrations sucked. Many customers wouldn't spend BTC for tax reasons, so I had to offer dollar payments or lose sales.

It would help me as a merchant if it were easier to add both BTC and fiat payments to my site.

> it's kind of a sellout move for BTCPay Server the self-hosted, open-source cryptocurrency payment processor that is secure, private, censorship-resistant and free

I'm sympathetic to this idea, too. But as a merchant I just want you to make my life easier.

Don't have time to dive into the details of the PR but wanted to give my perspective as someone who had to build similar functionality myself.

**Comment by NicolasDorier** [comment]
@xpayserver I think third party integration is quite controversial, and I don't care enough Stripe bottom line too much. Most merchant wanting Credit Card support already have access to a wide range of plugins.

Very often those third party integration necessitate maintenance as they change their API. We ended up removing coinswitch, changelly and shapeshift integration because of that.

Though, if you plan to integrate that into your fork, I think this is a good idea for some merchants.

**Comment by NicolasDorier** [comment]
>  If it's controversial it should be available as a module.

I think it is an idea, but we don't have plugin system right now in BTCPay Server.

**Comment by prayank23** [comment]
Concept NACK

> IMO this feature is better suited for a fork

Agree. Btcpayserver should avoid such things. There are lot of things related to BTC that we can add to improve BTCPay instead of adding legacy payments. Example: support of assets issued on Liquid, ways to integrate BTCPay in a website that wants to use subscriptions, improve btcTransmuter, add ways to convert BTC to stablecoin in a trustless way, etc.

**Comment by NicolasDorier** [comment]
> support of assets issued on Liquid

This is done already.

**Comment by prayank23** [comment]
I had read this doc: https://docs.blockstream.com/liquid/liquid-integrations.html?highlight=swap#use-l-btc-with-btcpay-server which mentioned -

> The Liquid feature in BTCPay Server allows online merchants to accept payment in L-BTC, USDt, and a **few other Liquid assets**

And and the link to list of assets currently available for integration by BTCPay Server deployments: https://docs.btcpayserver.org/Altcoins/ only mentions LBTC and USDt

So I thought not every asset issues on liquid can be accepted for payments using BTCPay

**Comment by caiofaustino** [comment]
Would this be precedent to add other payment providers later?

**Comment by NicolasDorier** [comment]
@caiofaustino that's a good point. I think that if it is done, it should be done with a plugin system. Not similar to shitcoin integration, but more similar to something like wordpress plugins. Sadly, we don't have the architecture to support that yet. I say it is not possible without massive complication, but @Kukks  swear to me that I was wrong, and left to his coding cave.

**Comment by Kukks** [comment]
See you in a few weeks 
image

**Comment by bolatovumar** [comment]
@astupidmoose wants to accept CC payments I bet

**Comment by astupidmoose** [comment]
> @astupidmoose wants to accept CC payments I bet

No. Who are you? Stop tagging me.

**Comment by bolatovumar** [comment]
> > @astupidmoose wants to accept CC payments I bet
> 
> No. Who are you? Stop tagging me.

I'm the lead developer of Argoneum. You reached out to me a while back about accepting Argoneum on shitcoincards dot com or something.

**Comment by knocte** [comment]
I'm glad that a shitcoiner recognizes that he's a shitcoiner but guys can you please stop the spam/offtopic.

**Comment by Eskyee** [comment]
Umar moves like a snake 🐍 🧐

**Comment by Eskyee** [comment]
> I'm glad that a shitcoiner recognizes that he's a shitcoiner but guys can you please stop the spam/offtopic.

What are you doing here... shit talking ??  No work ??

**Comment by Kukks** [comment]
Well, the competition beat this PR to it
image

Considering how much controversy came around this PR (and this is not me nacking this PR), I think this should be better focused on making a comeback as an addition to #1925. 

I urge you to push to get #1925 merged so you can build these stuff without the main codebase growing exponentially

**Comment by xpayserver** [comment]
@Kukks what need to do for extension?

**Comment by Kukks** [comment]
> @Kukks what need to do for extension?

#1925 

I'll close for now

**Comment by knocte** [comment]
> #1925

This has been merged already.
Can I bribe someone to convert this PR into an extension?

**Pull request closed without merging**
