### PR TITLE
Dashboard: Add Lightning balances and services

### LINKED ISSUE #3663: Add lightning to the dashboard
Since we have a wallet balance in the dashboard, we should consider at least adding lightning balance. 

There are many tricky things for this to be implemented, so opening this one for discussion and as a tracker for 1.6.0 or a release in between.

### PR DESCRIPTION
**Pull request by dennisreimann**
Closes #3663.

Things to be discussed and edited:
- Size and responsive behaviour of the tile
- Is there more info to display?

ln-tile

### CODE REVIEW

**Comment by dstrukt** [comment]
Nice!

Still exploring mocks, have quite a few suggestions here that will change this view :) 

But from a data POV, only other immediate things:

Lightning:
- Node Alias
- Number of Peers
- Number of (Active) Channels .. could eventually show other channel states

On-Chain:
- Unconfirmed Balance?
- Reserved Balance?

**Comment by dennisreimann** [comment]
> On-Chain: Unconfirmed Balance? Reserved Balance?

If it is more than zero it will be displayed, otherwise we are omitting it. (less noise)

**Comment by dstrukt** [comment]
ACK!

**Comment by dennisreimann** [comment]
As discussed in yesterdays design meeting: The balance and services tiles are now two separate things.

## Mobile

ln-mobile

## Tablet

ln-tablet

## Desktop

ln-desktop

**Comment by dstrukt** [comment]
Hell yeah, will review this in a few hours!

**Comment by dstrukt** [comment]
Conceptual:

- [ ] I think the `Wallet Balance` may need to be updated to `On-Chain Balance` to make the distinction clearer with the `Lightning Balance` underneath .. thoughts?

Functional nit:

- [ ] If no balance on either, "show details" should be hidden, doesn't do anything

Suggestions:

`Manage` for the Lightning Services links to the Lightning tab or a place to configure .. or the way to configure, as if you don't have them configured, the services link to a 404 .. then I don't know where to go to resolve.

`Show Details` does the same, and `Node Info` is just moved over to the other card.

Screen Shot 2022-06-10 at 11 49 21 PM

Otherwise, looks great, excellent work!

**Comment by pavlenex** [comment]
> I think the Wallet Balance may need to be updated to On-Chain Balance to make the distinction clearer with the Lightning Balance underneath .. thoughts? cc @pavlenex

I don't think it's needed, people using Lightning at this stage probably have good understanding. Plus it's structured so it say's "lightning balance" then on-chain below. I wouldn't change on-chain wallet wording for now.

**Comment by dennisreimann** [comment]
> it currently links you to a 404

That's because these services are fake in the dev env.

>  If no balance on either, "show details" should be hidden, doesn't do anything, regardless of which direction we go (see below)

Updated. 

For the rest I'd say the current version is good as it is and the headlines don't seem ideal, as you noted. Right now we have "BTC in channels" and "BTC on-chain", which is clearer imho. We can ship and see if people get confused here, maybe this isn't a big problem and they'll notice that theis refers to the Lightning balance, because it is part of the Lightning balance tile ;)

**Comment by NicolasDorier** [comment]
so nice.
I think we'll need eventually to refactor the Dashboard so it get refreshed in the background, or maybe asynchronously via some JS. We are requesting lot's of things sequentially, and this add up quick.

**Comment by dennisreimann** [comment]
@NicolasDorier agreed, there's already an endpoint for the data fetching of the wallet balance tile – this can be done for the other tiles as well. 

We'd need some kind of loading state then, ideally so that the tiles already have the correct size and the dashboard doesn't look shaky once the data starts coming in. 

Separate PR imho.

**Review by dstrukt — APPROVED** [review]

**Comment by gruve-p** [comment]
Works fine for GRS:
image

**Pull request merged**
