### PR TITLE
added View App button to POS settings

### PR DESCRIPTION
**Pull request by radWorx**
updated POS settings form group buttons to match Crowdfund settings from group buttons, addressing #854

### CODE REVIEW

**Comment by radWorx** [comment]
Yes!

**Comment by NicolasDorier** [comment]
look good to me, @radWorx you want to add what @britttttk suggest in this PR or separate?

**Comment by radWorx** [comment]
I can do that.

**Comment by radWorx** [comment]
> look good to me, @radWorx you want to add what @britttttk suggest in this PR or separate?

I'll add it.

**Pull request merged**
