### PR TITLE
Improve Payout View

### PR DESCRIPTION
**Pull request by dstrukt**
There's still quite a bit I want to do with this view, but just made a few small aesthetic changes for the time being as it's becoming a more prominent view in the latest 1.4.0 update.

- Improve the empty state view to hide options if there are no entries.
- Change the tabbed view
- Moved the "actions" selector above the tab view, but would like to incorporate the action with the tab view, but might need help with this (will provide a basic mock)
- Removed the backgrounds of the tab lists

Screen Shot 2022-01-06 at 4 54 34 PM
Screen Shot 2022-01-06 at 5 00 09 PM

Edit: @dennisreimann Open to whatever else you want to improve, but I'd be comfortable merging this.

Edit: Fixed the alignment issue.

### CODE REVIEW

**Comment by pavlenex** [comment]
Concept ACK.

**Comment by dstrukt** [comment]
Fixed a row/column issue, should be good to go barring a code review.

**Review by dennisreimann — APPROVED** [review]
Updtaed it, so that the filters are present, regardless of the list of payouts being populated. As the `Model.Payouts` are only representative of the current filter, we'd otherwise use the ability to change the filter in case the current list is empty.

**Comment by dstrukt** [comment]
Ooo, nice catch, much cleaner!

Updated a spacer above below the tabbed nav, we should be good to go.

**Review by dstrukt — COMMENTED** [review]
Can we keep the `mb-4`? It looks better imo, unless there was a particular reason you wanted to use `mb-3`.

**Comment by dennisreimann** [comment]
The item below had a negative margin of 1, which pulled it up. I removed it, so that the math fits again :)

**Comment by dennisreimann** [comment]
`CanUseTorClient` failure is unrelated. Good to go, imho!

**Comment by dstrukt** [comment]
Ahhh I see, beautiful.

Sned it!

**Pull request merged**
