### PR TITLE
Allow sounds and animation colors in crowdfund to be  configured

### LINKED ISSUE #652: Crowdfund: Configurable Sounds & animation colors
- Allow sounds to be configurable
- Allow animated background colors to be configurable

### PR DESCRIPTION
**Pull request by Kukks**
closes #652

### CODE REVIEW

**Comment by pavlenex** [comment]
Great change. Custom sounds can be a great use-case in the music industry. I already have an idea.

Is there a way we can make adding of the format a bit clearer?

We can add a tooltip that directs to docs or maybe just standardize the format and somehow explain what kind of file/links required.

sound


Lots of DJ's use SoundCloud, etc but if that does not work, we can find a workaround and explain it in a tutorial. With the voting feature enabled, their fans can even vote for songs. Though we'd have to then have sounds in perks.

**Comment by Kukks** [comment]
it has to be direct music files that are supported in web browsers. With docs links , we can add it with next release once we write it up :)

**Comment by pavlenex** [comment]
I see. I agree, we'd have to explain that through documentation somehow with examples.

I've tested this and everything works as expected when you add the appropriate direct download file link.

**Comment by Kukks** [comment]
(protip:  you can use `red` `green`, etc in the colors)

**Pull request merged**
