### PR TITLE
Remove replace hardcoded BTC string to default network

### PR DESCRIPTION
**Pull request by NicolasDorier**

### CODE REVIEW

**Comment by dennisreimann** [comment]
Yay, good point!

**Comment by gruve-p** [comment]
Thanks for this PR.
Unfortunately it does not solve the issue that the balance is wrong (and the charts are not working) on the dashboard for GRS:

mainnet:
image

testnet:
image

**Comment by gruve-p** [comment]
It seems the dashboard only populates BTC and not for altcoins

**Comment by dennisreimann** [comment]
@gruve-p Thanks for reporting that, it's addressed in #3876.

**Pull request merged**
