### PR TITLE
attempt fix pos css grid

### LINKED ISSUE #674: CSS Grid Layout problem in PoS
**Describe the problem/bug**
The layout in Point of Sale app looks weird on small screens. It should be equal and not 3-1-3-1 (grid boxes) 
[Live example ](https://mainnet.demo.btcpayserver.org/apps/3utBTfSKkW4gK7aQMd2hW5Bh9Fpa/pos)I tried on my 13-inch laptop

**Your environment**
* Version of BTCPay Server: v1.0.3.83

**Screenshots/Links**

**Additional context**
Probably introduced in #598 #651

### PR DESCRIPTION
**Pull request by Kukks**
fixes #674

### CODE REVIEW

**Comment by pavlenex** [comment]
Looks much better. Tested in Chrome and I haven't found any problems.
Would it be possible to align price for all boxes, would it make sense at all? 
PointOfSale

I'm just thinking, if someone was managing the PoS, may be interested to quickly find the prices? Don't know how that works, maybe it makese sense?

**Comment by Kukks** [comment]
my biggest issue so far is the non cart version and using the custom amount option. Can you check it out and let me know what you think of that one?

**Comment by pavlenex** [comment]
To me it looks okay, I don't see anything that's wrong.
Is there anything particular that worries you?

The only thing that looks bad is when the custom field is alone, it shouldn't look like this
pos only

Normally it looks like this
Capture

**Comment by Kukks** [comment]
try it with other items in as well

**Comment by pavlenex** [comment]
I have, I just don't see how it can be fixed. Maybe centrally aligning. allign middle it or?

pos 1 mobile
pos 1
pos 2 items
pos 4 item

**Comment by NicolasDorier** [comment]
[Kukks debugging css](https://i.imgur.com/e16qOEj.gif)

**Comment by Kukks** [comment]
https://media3.giphy.com/media/1BXa2alBjrCXC/giphy.gif?cid=3640f6095c879dd8346657313696b0cb

**Comment by Kukks** [comment]
fixed it all up. :)

**Comment by NicolasDorier** [comment]
@pavlenex can you give a try? don't worry about tests not passing, this is because of me

**Comment by pavlenex** [comment]
@Kukks @NicolasDorier Looks great now, tested ACK.

**Pull request merged**
