### PR TITLE
UI: Header and navigation improvements

### PR DESCRIPTION
**Pull request by dennisreimann**
Center aligning the main menu and giving the items and active state, as proposed by @dstrukt in #2364.

We can adjust the colors once we get the Bootstrap 5 migration done, as this will include the updated color palette.

mobile

light

dark

casa

### CODE REVIEW

**Comment by dstrukt** [comment]
😍 Lookin good!

Should we add "server settings" to the end of the list in this instance? 

Additionally, I've always wondered if it should be an icon and moved to the right, but I figured there might be some context around that one.

I have some additional suggestions for our mobile view, but will mock those up for a later time.

**Comment by dennisreimann** [comment]
I tend to agree, though I see the need for having it displayed prominently for the initial setup. Once that's done I can understand why having it as an icon (similar and next to the account settings) would make sense. Let's discuss this one :)

**Comment by dstrukt** [comment]
Sounds good -- will add it to the list for the next design meeting.

**Comment by pavlenex** [comment]
Concept ACK for the header menu being centered.

For Server Settings re-position/icon, I don't feel it's a good idea to change it at this time, as it would require a significant change in the documentation and simply will be odd for the users who're already used to it being first.

**Comment by dstrukt** [comment]
I'm happy to leave it for now, but this might not be the last time you hear from me on that issue :)

**Review by pavlenex — APPROVED** [review]
tACK. Great change 🚀 🚀

**Comment by dennisreimann** [comment]
I got #2362 almost done. As it builds on this: Do we want to include it here or first merge this and do it as a separate PR? I'd prefer the latter …

**Comment by pavlenex** [comment]
Let's do a separate PR @dennisreimann since that's what you prefer 🏗️

**Comment by dennisreimann** [comment]
Rebased and good to go :)

**Review by pavlenex — APPROVED** [review]
tACK

**Comment by dennisreimann** [comment]
Rebased. Once this gets merged after the upcoming release, I'll send the PR for #2362, which is based on this one.

**Pull request merged**
