### PR TITLE
Edit view for Pull Payments

### PR DESCRIPTION
**Pull request by daviogg**
https://github.com/btcpayserver/btcpayserver/issues/3878

### CODE REVIEW

**Comment by dennisreimann** [comment]
Good work and thanks for the contribution!

I've added [three more commits on my fork](https://github.com/dennisreimann/btcpayserver/commits/enhancement/edit-pull-payment) for things I came across while reviewing. Normally I'd note them in the suggestions, but some of it was a bit more involved, so I figured it might be best to do the changes as separate commits:

- To keep the store context, we need to have the `storeId` in the edit URL — otherwise the navigation will be empty for the edit page.
- The links and redirects got edited to match the behaviour of the payment requests

You can either add me as a collaborator to your fork or integrate my changes by cherry-picking the commits. With the former I could just push them here — whatever way you prefer.

Thanks again!

**Review by dennisreimann — APPROVED** [review]
tACK.

@daviogg Can you test it with the changes I did? If you want to, you can also add a simple Selenium test that checks the editing of the description for example.

**Comment by daviogg** [comment]
The test it is to be placed within the file `SeleniumTests.cs` right? Or we need to create a specific class for PullPayments tests?

**Comment by dennisreimann** [comment]
You van put it into an existing case if that exists. Or add a new one in the Selenium Tests.

**Comment by daviogg** [comment]
I did selenium tests but some tests are broken, seems external to this PR

**Comment by dennisreimann** [comment]
Yes, the test failures are again unrelated. Thanks for providing the test case! Good to go now :)

**Review by Kukks — APPROVED** [review]

**Pull request merged**
