### PR TITLE
Store Branding: Refactoring and logo as favicon

### PR DESCRIPTION
**Pull request by dennisreimann**
- Encapsulates store branding properties into their own view model
- Uses the logo as favicon on public pages

### CODE REVIEW

**Comment by NicolasDorier** [comment]
@dennisreimann does this PR will also use the logo when you add the app to the home screen of your phone? This would be very useful.

**Comment by pavlenex** [comment]
Oh nice idea @dennisreimann!

**Comment by dennisreimann** [comment]
@NicolasDorier Now it does, thanks for the pointer!

**Review by NicolasDorier — APPROVED** [review]

**Review by dstrukt — APPROVED** [review]
tACK - LGTM as far as I can tell (Payment Requests / Pull Payments / POS & CF), but will submit a bug if I find anything else.

**Comment by dstrukt** [comment]
I was having issues making a new store though, so used existing stores I had, but might not be related to this PR...?

**Review by Kukks — APPROVED** [review]
This may break plugins that have used the StoreHeader partial?

**Pull request merged**
