### PR TITLE
GreenField: Invoices: Add Refund Email endpoint

### PR DESCRIPTION
**Pull request by Kukks**
This reverts commit 709b06baa330fc670b2e4358dc69ecdb7b6aa4e5.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
The reason why we removed that is that I don't want to consider Refund Email in a different way than any data that can be in the Metadata.
I would prefer having a method to change Metadata in general.

**Comment by Kukks** [comment]
> The reason why we removed that is that I don't want to consider Refund Email in a different way than any data that can be in the Metadata.
> I would prefer having a method to change Metadata in general.

Hmmm, I am scared of the implications of making the metadata mutable. Thoughts?

**Comment by NicolasDorier** [comment]
I am not scared about that, this is just a dumb data store for merchant.
What I am scared of is that the metadata is inside the blob, and this blob might get updated at same time of the metadata change, losing one of the change.

I need to check better what is the risk.

**Comment by Kukks** [comment]
> I am not scared about that, this is just a dumb data store for merchant.
> What I am scared of is that the metadata is inside the blob, and this blob might get updated at same time of the metadata change, losing one of the change.
> 
> I need to check better what is the risk.

We should probably do some sort of queue service like we have for pull payments. I think it is an excellent way to avoid concurrency issues.

**Comment by Kukks** [comment]
Hmm, would it make sense to:
* Add an invoice log when the metadata changes
* Create an IPN when data changes
* Store a history of all states the metadata had?

**Comment by Kukks** [comment]
Keep in mind that OrderId is also stored there, changing that midway through an invoice payment could have consequences of integrations with ecommerce plugins.

**Comment by Kukks** [comment]
Moreover is that the metata invoice update would require authentication. The current email update doesnt need any auth in the Checkout UI. This would mean you cannot recreate the checkout UI entirely elsewhere as is?

**Comment by Kukks** [comment]
No consensus on this. closing.

**Pull request closed without merging**
