### PR TITLE
Fix: Payment request redirects to non-existing (404) URL after paymen…

### LINKED ISSUE #1479: Payment request redirects to non-existing (404) URL after payment completed
**Describe the problem/bug**
I create a payment request, pay it and then the payment request is redirected to a non-existing URL within btcpayserver.

Tried with Bitcoin Lightning and Monero, seems to be independent of the payment method.

Happens everytime, with different URL that's 404, so it is not a rare bug, I can reproduce it everytime.

**Your environment**
* Version of BTCPay Server: 1.0.4.0
* Deployment method: docker

**Logs (if applicable)**
Basic logs can be found in Server Settings > Logs.

**Screenshots/Links**
Screencast:
https://www.screencast.com/t/SMh8tclC

### PR DESCRIPTION
**Pull request by Kukks**
fixes #1479

### CODE REVIEW

**Comment by britttttk** [comment]
@Kukks it uses the correct path/ID now when you try to view the payment request from invoices. But in local dev it still fails on redirect. I can't remember if that's expected or not in local dev.

**Comment by Kukks** [comment]
Can you try with a fresh payment request? I've tried creating invoices both from the payment request UI and from the `/pay` endpoint and it worked

**Comment by britttttk** [comment]
Actually @Kukks i just updated Chrome and it fixed it

**Comment by britttttk** [comment]
Sorry I didn't get a good screenshot before update but it was saying something like OP's error about X-Frame-Options = Deny
image

**Comment by britttttk** [comment]
@Kukks I thought it was just a localhost issue because it looks like this. If I refresh the page it will show the payment request fine. 
image

**Comment by NicolasDorier** [comment]
Merging, I guess it is a localhost issue because it could not even connect.

**Comment by Kukks** [comment]
Yeah, I think it is because you are using http and that can cause some mess sometimes with websockets

**Pull request merged**
