### PR TITLE
Wallet setup finetuning

### PR DESCRIPTION
**Pull request by dennisreimann**
List of TODOs that need to be addressed before we can ship the wallet setup redesign done in #2164. 
For previous discussion see #2277.

Technical refactorings:
- [x] Remove old flow code (Stores.BTCLike Controller)
- [x] Code flow cleanups like @Kukks mentioned [here](https://github.com/btcpayserver/btcpayserver/pull/2164#discussion_r572023048)

Design and copy: 
- [x] Better icons for the create wallet options
    - [x] Icons from @dstrukt
- [x] Improve information display on xpub import (the long table)
    - [x] Input from @pavlenex and @dstrukt
- [x] Improve the wording of the explanations 
    - [x] Input from @pavlenex
- [ ] Incorporate [Nicolas' feedback on RPC import](https://github.com/btcpayserver/btcpayserver/pull/2164#issuecomment-777357793)
- [ ] Combine setup and modify page - see #2276

### CODE REVIEW

**Comment by dennisreimann** [comment]
@NicolasDorier @Kukks How can we better communicate the benefit of the RPC import? Right now the wording is …

> Each address generated will be imported into the node wallet and you can view your balance through the node.
> When this is enabled for a hot wallet, you are also able to use the node wallet to spend.

**Review by 0racl3z — APPROVED** [review]

**Comment by dennisreimann** [comment]
@Kukks replied to me with this explanation for the RPC import:

> I think the best way to explain it is that it does exactly what some of these other wallets have been doing lately. Like, Umbrel, FullyNoded, (specter?), etc in that they only build a UI but dont do the blockchain processing and simply hook up to the bitcoin core rpc where they handle the wallet through it.
The BTCPay import rpc feature does this:
> - Every time a new address is reserved for an invoice on that wallet, it gets imported into the bitcoin full node wallet as a watch only wallet. This means you'll be able to send an rpc to the node getaddressinfo xxx and it will tell you the balance for it.
> - If the hot wallet is also selected, it not only imports the address but also its private key. This means you can use the bitcoin rpc sendtoaddress or any other spending rpc and it will be able to use the balance on those imported addresses

**Comment by NicolasDorier** [comment]
I'd like to merge this for next release as well. Let me know when I can.

**Comment by dennisreimann** [comment]
@Nicolas We're having the design meeting today where we decide on what's left to change and what to do. Hopefully it'll be ready next week.

**Comment by pavlenex** [comment]
##  Improve the wording of the explanations 

Great work, I have 3 notes:
1. I suggest restructuring the text on generating a new wallet for hot vs watch-only wallet. (Though in all fairness, watch-only can be signed via PSBT or HWI not just manual input, though I don't think people generating a new wallet will have HWI or know what PSBT is).
2. When the wallet is `removed` we have a warring page. However, we don't have one when it's `replaced`. We should do it since it bears the same risk,
3. Regardless of `hot` or `watch-only` wallet, the warning page provides the same text saying `hot-wallet`. We should distinguish those. For watch-only we should perhaps say: 
```
Please note that this is a watch-only wallet!

Do not remove the wallet if you have not backed it up or imported into an external wallet. If you no longer have access to your private key (recovery seed), immediately replace the wallet.
```

**Comment by dennisreimann** [comment]
Included the feedback from @pavlenex. On the modify page I've added the "type", so that you can check if this is a hot or watch-only wallet

## Modify 
type-hot-wallet
type-watch-only


## Replace
replace-hot-wallet
replace-watch-only

**Comment by 0racl3z** [comment]
you all are the best

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by NicolasDorier** [comment]
For fixing tests, you may want to rebase on master.

**Comment by NicolasDorier** [comment]
The last test failing is also fixed on master

**Comment by NicolasDorier** [comment]
This is the last PR (maybe with the wallet API of @Kukks ) for next release. It is getting big.

**Comment by dennisreimann** [comment]
I'll rebase this, but please don't merge it yet – I'll have a session with @dstrukt tomorrow where we do the final touches for this to be ready for release.

**Comment by dennisreimann** [comment]
The Selenium test failure is unrelated, but I'll push at leats one more commit tomorrow here.

**Comment by 0racl3z** [comment]
Thx🙂

**Comment by dennisreimann** [comment]
Updated the icons – there might be another update coming with new icons for hot/watch-only wallets:

start

generate

Updated the recommendation labels on the import page:

import

import-mobile

**Comment by dennisreimann** [comment]
Makes the address types example table a bit less scary, will be revised in future updates though …

x27BWeoyhY

**Comment by pavlenex** [comment]
@NicolasDorier This one is ready to be reviewed.

**Comment by gruve-p** [comment]
Is there a possibilty to enable hardware wallet also for GRS ?

**Comment by Kukks** [comment]
> Is there a possibilty to enable hardware wallet also for GRS ?

Only if you can get BTCPay Vault to work with GRS.

**Comment by gruve-p** [comment]
https://github.com/Groestlcoin/GRSPayServer.Vault/releases

**Pull request merged**
