### PR TITLE
Crowdfund finetuning

### PR DESCRIPTION
**Pull request by dennisreimann**
WIP to address #3461. Requires input from @dstrukt to continue.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
still draft?

**Comment by dennisreimann** [comment]
Yes, @dstrukt wants to do some more changes here. I'm just keeping the PR rebased and alive :)

**Comment by dstrukt** [comment]
Working on this today, so might be updating

Items: 
- [ ] Utilize new currency selector here to, for the "Currency" input, if applicable & possible
- [ ] Turn off animations by default as well.. does this strip away too much of the personality, thoughts?

- [ ] Fix base URL for sounds (https://github.com/btcpayserver/btcpayserver/issues/3745)

- [ ] Featured Image should be extracted from Additional Options > Custom CSS and put under the "description" .. would be nice to improve the upload form + ease of use to upload & manage assets ton the server, but likely should be a larger effort
- [ ] Label should be Featured Image Url, at least for the time-being

- [ ] Improve the Recurring Goal section

- [ ]  Improve perks modal (updating)

**Comment by pavlenex** [comment]
>  Turn off animations by default as well.. does this strip away too much of the personality, thoughts?

Actually this is good, animations are bad for performance, page usually takes forever to load.

**Comment by dstrukt** [comment]
Interesting .. I've never done any analysis on the page load, but agree I do recall it takes a while sometimes .. that's the animations? If so, definitely agree we should turn off by default, and address that on the next round of revisions in the future.

**Comment by pavlenex** [comment]
> Interesting .. I've never done any analysis on the page load, but agree I do recall it takes a while sometimes .. that's the animations? If so, definitely agree we should turn off by default, and address that on the next round of revisions in the future.

Yeah, the animations, it's fun but I've noticed couple of folks complained on the load time, haven't done any tests on it tbh.

**Comment by dstrukt** [comment]
@dennisreimann Updated this ticket to consolidate what's probably reasonable for 1.6.0.

**Comment by dennisreimann** [comment]
Rebased and finished the remaining points. Ready for review now.

**Comment by dstrukt** [comment]
Beautiful, will review in a few hours!

**Review by dstrukt — APPROVED** [review]
LGTM! 

There's 1-2 last little visual modifications I want to make, but don't need to happen on this PR or use up any more of your time @dennisreimann. Will do a follow up PR.

As usual, thank you, and send it!

**Comment by dennisreimann** [comment]
Go ahead and make them here, no need to hurry merging this.

**Comment by dstrukt** [comment]
Sounds good, will try to sort my build issue so I can make the changes on your branch!

**Comment by dstrukt** [comment]
Screen Shot 2022-06-24 at 11 39 12 AM

Just wanted to do a spacer, like Start/End between these two. 

Otherwise, we're good!

**Comment by dennisreimann** [comment]
Also updated the background color of the datepicker.

grafik

**Comment by dstrukt** [comment]
YES! Looks great.

The date picker change makes me happy.

Thank you!

**Pull request merged**
