### PR TITLE
Policies: Add warnings for certain options

### LINKED ISSUE #5546: Add a warning when `server admin` enables certain settings in `policies`
No matter how clear we are in communicating things, even linking to our documentations, users are sometimes going to enable things just because they can. 

To ensure users are well-informed about potential risks certain options are, we should provide a warning when certain checkboxes are checked.

I am unsure how this should be done UX-wise and if we're doing it on other places, I'll leave that to @dstrukt and @dennisreimann, but here are copy suggestions.

1. If checkbox `Disable new user registration on the server` is unchecked, we should show:

Caution: Enabling public user registration means anyone can register to  your server and may expose your BTCPay instance to potential security risks from unknown users.

2. If checkbox `Disable non-admins access to the user creation API endpoint` is unchecked show:

Caution: Allowing non-admins to have access to API endpoints may expose your BTCPay instance to potential security risks from unknown users.

3. `Allow non-admins to create hot wallets for their stores`   and `Allow non-admins to import hot wallets for their stores ` are checked 

Caution: Enabling this option, may simplify the onboarding and spending for third-parties but carries liabilities and security risks associated to storing private keys of third parties on a server.

### PR DESCRIPTION
**Pull request by dennisreimann**
Closes #5546.

policies

Also unified the display of those messages we have in other places as well, e.g. 

0conf

### CODE REVIEW

**Comment by pavlenex** [comment]
Looks a bit odd with yellow text on white background? 
Screenshot 2023-12-12 at 15 24 11
Screenshot 2023-12-12 at 15 24 40


@Kukks can you jump in on this one please?
So if enabled, third-parties will be able to receive payments to your store ,but not spend it? Should we provide any warring here?
Screenshot 2023-12-12 at 15 27 51

**Comment by dennisreimann** [comment]
@pavlenex I adjusted the Lightning policy text and font color for warning text on light background. 

grafik

**Comment by Kukks** [comment]
> Looks a bit odd with yellow text on white background? 
> Screenshot 2023-12-12 at 15 24 11
> Screenshot 2023-12-12 at 15 24 40
> 
> 
> @Kukks can you jump in on this one please?
> So if enabled, third-parties will be able to receive payments to your store ,but not spend it? Should we provide any warring here?
> Screenshot 2023-12-12 at 15 27 51
> 

The copy on that one is wrong. This option allows non admins to configure their stores lightning payment method to the internal node, but will never allow them to withdraw until they become server admins. The concept is to allow uncle Jim model where server admin manages balances and payouts manually.

**Comment by dennisreimann** [comment]
> The copy on that one is wrong.  

I adjusted it to "Caution: Enabling this option, may simplify the onboarding for third-parties but carries liabilities and security risks associated with sharing the lightning node with other users."

**Review by NicolasDorier — APPROVED** [review]

**Review by Kukks — APPROVED** [review]

**Pull request merged**
