### PR TITLE
Remove bitpay translator

### PR DESCRIPTION
**Pull request by NicolasDorier**
@pavlenex told me that bitpay does not force this anymore, so we can remove it.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
https://twitter.com/kristapsk/status/1337642254413025280?s=20

**Comment by kristapsk** [comment]
Yes, can confirm, it does not.

**Comment by NicolasDorier** [comment]
> Yes, can confirm, it does not.

Now that's a confusing sentence.

**Comment by kristapsk** [comment]
> Now that's a confusing sentence.

Yes, can confirm, it does not [force this anymore]. :)

**Pull request merged**
