### PR TITLE
Add hardware support via BTCPayServer Vault

### PR DESCRIPTION
**Pull request by NicolasDorier**

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Ping @rockstardev @Kukks @bolatovumar I was wondering if I should not make use of async/await feature in the javascript.

I don't want to introduce a dependency like nodejs for developers in this project, but the waterfall of callback is really not super cool to read.

async/await seems supported by modern browsers.

**Comment by NicolasDorier** [comment]
I am referring to the cascade https://github.com/btcpayserver/btcpayserver/pull/1152/files#diff-057004722b99872931b30b06d3f6a969R138

**Comment by Kukks** [comment]
I would introduce async await only if you have a transpiler hooked up (Babel, typescript).  Truth is even if modern browsers support it, many users take forever to update( or in some scenarios arent able to)

**Comment by Kukks** [comment]
We' ve had issues for example with small usages of `const` and `let` in the js breaking a few users

**Comment by NicolasDorier** [comment]
`transpiler hooked up (Babel, typescript).` I don't want to add any new dev time dependency, so this is not an option.

**Comment by bolatovumar** [comment]
@NicolasDorier I guess it's pretty safe to use async/await if you don't care about IE 11 (you probably don't). See support stats here: https://caniuse.com/#search=async

Overall it has 91.5% support globally.

**Comment by NicolasDorier** [comment]
Well if `We' ve had issues for example with small usages of const and let in the js breaking a few users` I guess I should not even try with async/await :(

**Comment by bolatovumar** [comment]
@NicolasDorier I'm wondering if in this case lack of support in IE 11 and some very old browsers is less of an issue because it's an internal page that's only available after you login. IE 11 is the only browser without async/await support that has any significant usage.

**Comment by NicolasDorier** [comment]
Well @Kukks said some users complained because of const, which is itself more compatible than async/await.

**Comment by NicolasDorier** [comment]
@bolatovumar @Kukks so with the new themeing feature coming, we are using named variable which is supported at 93% versus 91% for async await.

I think to show a popup warning page in case the user have outdated browser and just use async.

**Comment by Kukks** [comment]
Yeah code the latest spec and then we can add a warning or a polyfill

**Comment by bolatovumar** [comment]
@Kukks you can't really polyfill async/await easily without introducing a transpilation step.

**Comment by NicolasDorier** [comment]
Still lot's of things to improve, but that will be for another day.

**Pull request merged**
