### PR TITLE
Fix payment request template

### PR DESCRIPTION
**Pull request by bumbummen99**
This will prevent the page from being vertically too small for the screen. Right now the footer will cut off and the screen will continue with the body bg on big screens. With this patch the main section will take grow vertically if space is available.

### CODE REVIEW

**Comment by dennisreimann** [comment]
For context: This sticks the footer to the bottom instead of having it right after the last container

Before … 

before

After …

after

@pavlenex @dstrukt What are your thoughts? I'd be fine with this. If so, we should also do it like this in the Pull Payment view.

**Comment by bumbummen99** [comment]
@dennisreimann It seems in your template the footer has no background. The default light theme has a green background on the footer.

**Comment by pavlenex** [comment]
LGTM, don't mind the new way of displaying it.

**Comment by NicolasDorier** [comment]
ping @dennisreimann should we merge this?

**Comment by dennisreimann** [comment]
@NicolasDorier yeah we could, but it should be the same for the pull payment view then. 

@bumbummen99 Can you also update the pull payment view?

**Comment by dstrukt** [comment]
I'm okay with the fixed "powered by" footer for the empty state, and agree, it should be consistent.

**Review by dennisreimann — CHANGES_REQUESTED** [review]
Please rebase (test fixes) and update the pull payment view.

**Comment by dennisreimann** [comment]
@bumbummen99 Can you give my access to your fork so that I can take over the missing pieces if you don't have the time? It's almost done :)

**Comment by dennisreimann** [comment]
Thanks, rebased the PR and unified the templates – thanks for the swift reaction!

**Pull request merged**
