### PR TITLE
Checkout v2: Display and copy addresses

### LINKED ISSUE #4442: [Checkout V2] Add Copy Address support
- [ ] Show address(es)
A) Via Copy button
Screen Shot 2022-12-21 at 12 00 32 AM
B) Dumping the payment URL under the QR
Screen Shot 2022-12-21 at 1 08 20 AM

- [ ] Shows addresses / relevant payment details as a modal on `Copy` button click for >1

### PR DESCRIPTION
**Pull request by dennisreimann**
Opted for the simplest variant and displaying the info right away — imho this works best for the case in which one wouldn't want to copy, but just see and confirm the addresses. This also makes it one click less for copying.

I left out the payment method icon and copy button to have more space for the info (mostly relevant for the Bitcoin address) and because it felt kind of redundant for the >1 cases.  

Also to be discussed: Where do we want to have the CTA button? I left it at the botton, because I felt the text underneath the QR explains the functionality of the then following addresses better, but I can also see why one would like to have it right undernath the QR.

Closes #4442.

## Separate payment methods

copy-address

## Unified

unified

### CODE REVIEW

**Comment by dennisreimann** [comment]
Maybe we can even omit the full payment link as this isn't really meant for copying and the "Pay in Wallet" button triggers the action.

**Comment by dennisreimann** [comment]
Updated it. Much better.

## Bitcoin and Lightning

copy-address


## Unified

unified

**Comment by dstrukt** [comment]
The latter is much nicer!

I do like the idea

**Comment by dennisreimann** [comment]
Ok, what about this? 

* Removed the explanation text underneath the QR, as it isn't necessary anymore if we have those explicit buttons
* Added the payment method icon to the QR (optional, but I remember someone mentioned it'd be good to have it back)

grafik

**Comment by dstrukt** [comment]
Liking the direction more!

### Payment Method Icon

Agree with the payment method icon being an optional toggle in the admin settings .. makes me wonder if we want to any kind of border, some quick explorations to help decide if it's worth doing, e.g:

Screen Shot 2022-12-31 at 5 48 07 PM

Otherwise, I might also scale up the (bitcoin) icon by like 5% if it's 40px to 48px or 56px to 64px if we can afford that space, something like that.

### Copy Address 

Not sure I love the `Copy` button, so did some text only and icon explorations for alternatives.

Exploration:
Screen Shot 2022-12-31 at 5 42 51 PM

**Comment by dennisreimann** [comment]
> Agree with the payment method icon being an optional toggle in the admin settings

I didn't mean it to be a setting and I wouldn't do it like that. I meant I inserted it as an optional thing we could go with — so I'd say either we have it or we don't, but not make it configurable. I also wouldn't bump up the size too much, as it takes space from the QR data and it might be tricky with the unified one especially. So maybe we should just omit it for now and reevaluate if users really want it.

> Not sure I love the Copy button, so did some text only and icon explorations for alternatives.

Ok, will update it and also adjust colors and font weights (semibold?) for the labels and addresses.

Let me know which variant to go with — icons or text? We should then maybe also unify it across the app, as we aren't consistent in that regard right now.

**Comment by dennisreimann** [comment]
Updated and also checked that the unified QR still works with this icon size. I really like it this way and in conjunction with #4459 it also leaves the option to remove the icon via custom CSS.

grafik

**Comment by dstrukt** [comment]
> I didn't mean it to be a setting and I wouldn't do it like that. I meant I inserted it as an optional thing we could go with — so I'd say either we have it or we don't, but not make it configurable. I also wouldn't bump up the size too much, as it takes space from the QR data and it might be tricky with the unified one especially.

Ahhh I see, let's roll with it enabled, and collect feedback, it's more clear imo. I also like the circular border - looks great! Sounds good w.r.t the size, esp. considering we added the border.

> Ok, will update it and also adjust colors and font weights (semibold?) for the labels and addresses.

I think the label here looks great considering we're not using the input borders, and realize this is all a little inconsistent for for the rest of the app, but that might be acceptable...

Screen Shot 2023-01-01 at 10 02 10 PM

> Let me know which variant to go with — icons or text? We should then maybe also unify it across the app, as we aren't consistent in that regard right now.

Hmmm I'm still a little uncertain which variant I prefer, but agree we should make it as consistent as possible.

Will co-ordinate with you on Mattermost so we can get this sorted and merged.

Otherwise, everything looks great!

**Comment by Craw69699** [comment]
What do I do

**Comment by dennisreimann** [comment]
If the only thing left is the copy icon vs. text matter, let's go with the text as that's what we use in most places — there are a few outliers that use the icon, but reviewing and unifying those should be done separately anyways.

We should then also consolidate those "labels" as we use them in the other public pages as will, e.g. for amounts in payment requests and pull payments iirc.

**Comment by dstrukt** [comment]
> If the only thing left is the copy icon vs. text matter, let's go with the text as that's what we use in most places — there are a few outliers that use the icon, but reviewing and unifying those should be done separately anyways.

Sounds good, let's just go with the text for now, can collect some feedback, or switch it in the future if it makes sense.

> We should then also consolidate those "labels" as we use them in the other public pages as will, e.g. for amounts in payment requests and pull payments iirc.

Yeah I'm debating if we should just use the standard "label" that we are currently and consolidate at a later point, as our current label is sufficient. I do like the uppercase label, and think in this instance it looks better than it might in other places, but i'd need to poke around in Figma before making that call.

Do you have a preference?

**Comment by dennisreimann** [comment]
> Do you have a preference?

I'm fine either way — we'll keep it consistent with the rest once we get to the other public pages in #4114 and #3842.

**Review by dstrukt — APPROVED** [review]
Sounds good - let's roll with what we have then, as it's perfectly sufficient, and we can do some minor consistency modifications in the near future!

**Pull request merged**
