### PR TITLE
Improve Lightning node info view

### PR DESCRIPTION
**Pull request by dennisreimann**
Added the store name, which I really missed :)

Cleaned up the UI and also the HTML – this unifies the JS/non-JS version.

Include minor code cleanups as well.

dark

light

### CODE REVIEW

**Review by Kukks — CHANGES_REQUESTED** [review]
Is the Vue App needed at all in this UI? I think we can handle most of the UI stuff with just the razor syntax  + the clipboard utility js script

**Comment by dennisreimann** [comment]
The QR code is a Vue component, I guess that's the main point here. In LNbank I'm [generating the QR codes server-side](https://github.com/dennisreimann/btcpayserver-lnbank/blob/master/LNbank/Controllers/QrcodeController.cs) – I think we should switch to that as well so that we can offer a good fallback for non-JS cases.

**Comment by Kukks** [comment]
> The QR code is a Vue component, I guess that's the main point here. In LNbank I'm [generating the QR codes server-side](https://github.com/dennisreimann/btcpayserver-lnbank/blob/master/LNbank/Controllers/QrcodeController.cs) – I think we should switch to that as well so that we can offer a good fallback for non-JS cases.

We should make a view(not vue) component for QR codes

**Comment by Kukks** [comment]
Will merge this for now as it's a whole other thing to switch to that

**Pull request merged**
