### PR TITLE
Ellipsis when there is lots of info, preserving responsive tables

### PR DESCRIPTION
**Pull request by lepipele**
Ref: https://github.com/btcpayserver/btcpayserver/issues/133

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Is there a way to fix the first column length? 

image

**Comment by lepipele** [comment]
We can set fixed width for first column so they align. You wanna do that?

**Comment by NicolasDorier** [comment]
yes I think this would look better

**Comment by lepipele** [comment]
Ready for review @NicolasDorier

**Comment by NicolasDorier** [comment]
This is magic, it works!

**Pull request merged**
