### PR TITLE
Pay Button Alert: Add missing alert-link classes

### PR DESCRIPTION
**Pull request by dennisreimann**
## Before

before

## After

after

### CODE REVIEW

**Review by dstrukt — APPROVED** [review]

**Comment by NicolasDorier** [comment]
doesn't seems like this is clickable though

**Comment by dennisreimann** [comment]
Agreed. We should adapt the styles of the `alert-link` class, because this is used in multiple places. @dstrukt

**Comment by dstrukt** [comment]
Agreed, I've wanted to address the stylings for the alerts .. will add it to the design system list.

**Comment by dennisreimann** [comment]
Update the alert link styles:

image

**Pull request merged**
