### PR TITLE
Make main menu show text instead of icons when on small screens

### PR DESCRIPTION
**Pull request by Kukks**
before
image

after
image

### CODE REVIEW

**Review by dennisreimann — APPROVED** [review]

**Review by bolatovumar — APPROVED** [review]
Great improvement for mobile. Not sure why we haven't thought of this improvement up until now.

**Comment by britttttk** [comment]
Concept ACK

**Comment by dennisreimann** [comment]
@NicolasDorier I think this could also be included in the upcoming release.

**Comment by dennisreimann** [comment]
Let's merge this one, so that I can do @dstrukt's header improvements based on it :)

**Comment by dstrukt** [comment]
Agreed.

Great improvement on mobile!

**Pull request merged**
