### PR TITLE
Test improvement exposing failing test

### PR DESCRIPTION
**Pull request by dennisreimann**
@Kukks This test case actually didn't work before - the check picked up the `#badUrl` alert from the layout, which isn't what's desired here. Can you help fix the use case?

### CODE REVIEW

**Comment by NicolasDorier** [comment]
The lightning pull payment tests were completely broken. It wasn't testing at all if the payout succeeded.

**Comment by NicolasDorier** [comment]
Last test failing is the flakyness of the save button for lightning settings... Will try to sovle this separately.

**Comment by dennisreimann** [comment]
> Last test failing is the flakyness of the save button for lightning settings... Will try to sovle this separately.

Didn't this help? d555d2f3f60bd333896d8a0f81a9a547448b545e

**Comment by NicolasDorier** [comment]
Probably a bit, but not enough: https://github.com/btcpayserver/btcpayserver/commit/70bb6d999e4bd376eb9deef0a2ec5871b4c1fd9a

**Pull request merged**
