### PR TITLE
Pos experimental card deck

### LINKED ISSUE #598: Equalize card height in POS
As seen on https://twitter.com/ideaslikeflames/status/1095019294923112448

### PR DESCRIPTION
**Pull request by Kukks**
Closes #598 

@mariodian  @pavlenex 
Can you review/test?

### CODE REVIEW

**Comment by pavlenex** [comment]
I think it looks better and tidier. Haven't seen anything wrong with it. The layout looks good on the desktop and on smaller screens. Mario's earlier concerns about having layout being broken with cart seem to be addressed.
pos

**Comment by Kukks** [comment]
also try non cart mode plox

**Comment by pavlenex** [comment]
I tested that one as well just didn't post the image. Looks better.

pos

**Comment by NicolasDorier** [comment]
Ready to merge?

**Pull request merged**
