### PR TITLE
Fx pos data additional info

### LINKED ISSUE #6162: [Bug]: Additional Information from posData is .NET
### What is your BTCPay version?

BTCPay Server v1.13.5+30d91d0bd

### How did you deploy BTCPay Server?

Docker compose

### What happened?

I'm seeing ``System.Collections.Generic.Dictionary`2[System.String,System.Object]`` in the dashboard `/invoices/<ID>` route.

image

### How did you encounter this bug?

1. Generate any invoice in the Point of Sale app
2. Open the generated invoice in the dashboard

### Relevant log output

_No response_

### What browser do you use?

_No response_

### Additional information

_No response_

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

### PR DESCRIPTION
**Pull request by TChukwuleta**
Fixes #6162 

Displays the actual details of the post data as against .Net code (System.Collections.Generic.Dictionary2[System.String,System.Object])

### CODE REVIEW

**Review by dennisreimann — APPROVED** [review]
tACK

**Comment by NicolasDorier** [comment]
NACK, this code is full of code injection vulnerabilities. You need to walk on eggshell everytimes you use `Html.Raw`.

Actually you should never use it unless you are 100% sure that what is inside can't be injected by a malicious actor.

You also did string concatenation for building HTML. As `Html.Raw` this should never be done.
You need to wrap everything that is provided by the user by `@Safe.Raw`

**Comment by NicolasDorier** [comment]
The tests are broken as well.

**Comment by dennisreimann** [comment]
@NicolasDorier Updated it, it should be good now, as it is mostly like before. Extracted the individual entry part and reused that.

**Pull request merged**
