### PR TITLE
Fix Summernote XSS possibility

### PR DESCRIPTION
**Pull request by dennisreimann**
Addresses #2856, which is related to summernote/summernote#3782.
As this is an open issue on the Summernote repo, I tried fixing the bug by patching it directly in our code. 

If this work, we might propose it as a fix for summernote/summernote#3934 too, which isn't directly part of the other mentioned issue but also still ongoing.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
strange, build is broken but I don't see errors.

**Comment by NicolasDorier** [comment]
Ah yes, there are errors. It is the bundler doesn't understand your syntax.

**Comment by dennisreimann** [comment]
Build fixed, integration test is failing because HitBTC isn't available right now.

**Comment by dennisreimann** [comment]
Shall we close this now? imho it might still make sense to include the changes, @NicolasDorier

**Pull request merged**
