### PR TITLE
Add mnemonic phrase color CSS variable

### LINKED ISSUE #1456: Mnemonic seed not visible when generating a hot wallet
**Describe the problem/bug**

**EDIT: This happens on every theme not just dark theme as I originally reported.**

When someone uses dark theme and tries to generate a hot wallet, the mnemonic is not that visible and it's hard for user to even notice there's a seed there, which can be quite dangerous.

**To Reproduce**
1. Go to Store > Derivation Scheme > Modify
2. Click on `Import from` ...`new/existing seed`
3. Enable hot wallet 
4. Generate a wallet.
5. See error

**Expected behavior**
User should clearly see, possibly emphasized in danger color his seed and should be aware that they need to back it up.

**Actual behavior**\
The seed is barely visible

**Screenshots/Links**
seed

mnemonic

Happens on light theme as well

light

### PR DESCRIPTION
**Pull request by bolatovumar**
fix #1456

### CODE REVIEW

**Comment by dennisreimann** [comment]
I‘d rather apply the `alert-link` class to the `code` tag (like we did with the API Key) than introduce a new variable for this single use case. The `alert-link` class gives it the correct text color. What do you think @kukks?

**Comment by Kukks** [comment]
Let's stay consistent with the rest of the codebase

**Comment by bolatovumar** [comment]
@dennisreimann @Kukks ok, done.

**Comment by dennisreimann** [comment]
@bolatovumar thanks! 👌🏻

@Kukks do we have the same problem in the tests as with the API key?

**Comment by Kukks** [comment]
Most likely, will fix

**Comment by Kukks** [comment]
fixed conflict and test i think

**Comment by NicolasDorier** [comment]
@Kukks that's still failing.

**Comment by NicolasDorier** [comment]
will fix tests

**Pull request merged**
