### PR TITLE
Improve design to be more sober

### PR DESCRIPTION
**Pull request by clintnetwork**
Hi make a little change about CSS, I think it's better now, have an hard background-shadow is not very beautiful.

Best regards

Before:
old

After:
new

### CODE REVIEW

**Comment by britttttk** [comment]
I like previous dark shadow better. Perhaps there is something in between? New version is a bit light for me. :)

**Comment by clintnetwork** [comment]
Hmm, something like this ?
image

**Comment by clintnetwork** [comment]
I would like to add something: the trends is light / sober, watch by example https://now.sh :)

**Comment by britttttk** [comment]
Sorry I've never heard of sober, but I like the original shadow best. It makes the invoice stand out more for me, in my opinion. :)

**Comment by clintnetwork** [comment]
So we need poll :p

**Comment by pavlenex** [comment]
Thanks for your PR, unfortunately I think you're trying to fix something that is not broken. Instead I suggest you take a look at this issue #433 and try to tackle it.

The current design makes invoice stand out which can be helpful for QR code scanning, especially on older phones.

**Comment by clintnetwork** [comment]
First I don't have tried to fix a problem but improve an existing design.

Secondly if you love

**Comment by britttttk** [comment]
@clintnetwork yes can you help with 443? :) it's been open a very long time!

**Comment by clintnetwork** [comment]
You see bitpay has understanded the concept of design 💃 

image

**Comment by pavlenex** [comment]
Hey @clintnetwork, luckily we're not trying to be BitPay.

We base our design based on feedback from community and merchants and not based on what we think looks pretty, so functional over pretty for now :)

As I mentioned earlier, there are many other issues concerning design which are a priority at this moment, if you want to help out, you can join us on our [Mattermost chat](https://chat.btcpayserver.org/) to discuss with developers, or just let's discuss what we can improve with functional design.

To be honest with you in my personal opinion, BitPay's recent changes in design are to decrease customers support for them, not make the shopping experience better for the buyers.

**Comment by mariodian** [comment]
I agree with @clintnetwork here. In the era of flat designs the current shadow is way too dark and I would say for no apparent reason.

On the other hand the whole invoice page needs a major redesign (including the mentioned #433). For example, I don't see a reason why the invoice element would be so narrow as if it was viewed on a mobile when viewed on a PC. Also I don't think we need to display BTCPay logo to save some space for mobiles to display more important info etc. I'll likely draft something for the distant future.

**Pull request closed without merging**
