### PR TITLE
dashboard widget priority ordering

### PR DESCRIPTION
**Pull request by TChukwuleta**

### CODE REVIEW

**Review by Kukks — COMMENTED** [review]
What's the reasoning for this change? Did anyone request it?

**Comment by TChukwuleta** [comment]
> What's the reasoning for this change? Did anyone request it?

It was mentioned here #5191 that  the wallet balance, transactions, lightning balance widgets should always sit first, hence the reason for the re-ordering and the changes

**Comment by dennisreimann** [comment]
Ideally we make it so, that the users can reorder and prioritize themselves. Otherwise tgis will always be subjective and limited.

**Comment by Kukks** [comment]
Let's not reorder this until we actually have widget customization support.
I want users to notice plugin specific features on the dashboard faster

**Comment by Kukks** [comment]
closing in favor of #5742

**Pull request closed without merging**
