### PR TITLE
add enviroment configuration to issue template

### PR DESCRIPTION
**Pull request by pavlenex**
This PR adds `cat /etc/profile.d/btcpay-env.sh` in the bug report issue template that will help us better with deployment issues. I've noticed it's important info we often ask people to provide.

Unsure if wording was the best here so if there are better ideas, let me know.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
mmmh I don't know if that's the best, because there is some private info here (say a xpub from eps)

**Comment by pavlenex** [comment]
Should I add "Obscure any private information"?

**Comment by NicolasDorier** [comment]
The best is that they run `. btcpay-setup.sh -i` then copy the logs, we show all variable there, but people need to make sure to remove sensitive info like xpub

**Comment by pavlenex** [comment]
@NicolasDorier should be good now I think.

**Pull request merged**
