### PR TITLE
Update UpdateStore.cshtml

### PR DESCRIPTION
**Pull request by radWorx**
Lightning shows enabled in the UI, confusing users that aren't admins. #944
Lightning enabled for ServerAdmin only.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
sorry for some reason this PR did not show up in my notifications, taking a look

**Comment by NicolasDorier** [comment]
So users that are not admin can use lightning if they have a node hosted by themselves.

**Comment by radWorx** [comment]
Got it. Thanks

**Comment by NicolasDorier** [comment]
Fixed by https://github.com/btcpayserver/btcpayserver/commit/42d7ad02b0329b909aad9a02165493d470f5502a

**Pull request closed without merging**
