### PR TITLE
bump ms aspnet packages

### PR DESCRIPTION
**Pull request by Kukks**

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Can you bump the dockerfile sdk and runtime as well?

**Comment by pavlenex** [comment]
On a dev call yesterday we agreed @NicolasDorier will do the bumps and merge this PR.

**Comment by NicolasDorier** [comment]
Some bump of docker file were missing

**Comment by Dezzj** [comment]
> Can you bump the dockerfile sdk and runtime as well?

**Pull request merged**
