### PR TITLE
CoinSwitch depositAmount issue

### PR DESCRIPTION
**Pull request by amitasaurus**
We have encountered an issue with BTC Pay integration of CoinSwitch that to_amount is always fed as 1.025 because of this commit 
screenshot
https://github.com/btcpayserver/btcpayserver/commit/1d18965a264f1fdec1bac3b711aeac54646e0b64
The bug seems to be in the following line 
`coinswitchAmountDue: function() {
                return this.srvModel.coinSwitchAmountMarkupPercentage
                    ? (1 + (this.srvModel.coinSwitchAmountMarkupPercentage / 100))
                    : this.srvModel.btcDue;
            }
`
Fix is in the PR, please review and merge at the earliest.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
@Kukks ?

**Comment by NicolasDorier** [comment]
@amitasaurus seems to be a conflict? Can you solve?

**Comment by amitasaurus** [comment]
> @amitasaurus seems to be a conflict? Can you solve?

I cannot see the conflict

**Comment by amitasaurus** [comment]
Thanks @NicolasDorier

**Comment by amitasaurus** [comment]
@NicolasDorier @Kukks We found out about this issue from a client, what do clients need to do from their end to get the latest fixes?

**Comment by Kukks** [comment]
Once merged, it'll be in the next release. They then just need to update their btcpay to latest

**Comment by Kukks** [comment]
Thank you for the fix and contribution! :)

**Comment by NicolasDorier** [comment]
Making a new release now, I actually need something myself.

**Comment by amitasaurus** [comment]
@NicolasDorier Please let me know once it is released. We need to inform our clients.

**Comment by NicolasDorier** [comment]
@amitasaurus done `1.0.3.117`

**Pull request merged**
