### PR TITLE
Adding job to rebuild docs (swagger api) on new tag.

### PR DESCRIPTION
**Pull request by ndeet**
Ping @NicolasDorier @dennisreimann as discussed [here](https://chat.btcpayserver.org/btcpayserver/pl/3rqehaz1abn9fbcx9kgj976qra) 

Tbh just followed patterns I saw on the example of transmuter, no clue if I did it right, please check. Also if not already there the `$GH_PAT` env variable needs to be set on the repo.

### CODE REVIEW

**Comment by dennisreimann** [comment]
LGTM!

**Comment by NicolasDorier** [comment]
Ping @Kukks what is GH_PAT?

**Comment by dennisreimann** [comment]
@NicolasDorier It's a GitHub Personal Access Token, so that the action can get triggered from outside.

**Comment by NicolasDorier** [comment]
from which repo?

**Comment by dennisreimann** [comment]
It isn't repo based, it has to be a personal access token ([details](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token)), because we are using it from outside of GitHub.

**Review by Kukks — APPROVED** [review]

**Comment by ndeet** [comment]
@NicolasDorier seems this does not trigger, is the GH access token in place? The recent changes from #3170 are not reflected on https://docs.btcpayserver.org/API/Greenfield/v1/#operation/StoreOnChainWallets_GetOnChainWalletReceiveAddress

Can you maybe trigger it manually once as the api docs are really outdated with quite some fixes the last few months?

**Pull request merged**
