### PR TITLE
Set Buyer email to refund email if not set

### LINKED ISSUE #941: Add refund email to invoice export
**Is your feature request related to a problem? Please describe.**
I use pure crowdfunding app without woocommerce integration. The problem is that in invoice view, I cannot see and especially export the refund email address field, which is the only contact information for customer that I have.

**Describe the solution you'd like**
I'd like to have an option to easily export the list of paid invoices with the selected perk and e-mail address that they gave during payment.

**Describe alternatives you've considered**
Running:

```
docker exec -it c59817c0f6fe psql -U postgres btcpayservermainnet

select "CustomerEmail" from "Invoices" where "OrderId" like 'crowdfund-app%' and "Status"='complete'  order by "Created";
```

### PR DESCRIPTION
**Pull request by Kukks**
#fixes #941 (i think)

### CODE REVIEW

**Comment by NicolasDorier** [comment]
I don't like changing the blob, the blob is meant to be read only.

**Comment by NicolasDorier** [comment]
It should be fixed at the export level, not UpdateInvoice.

**Comment by Kukks** [comment]
The problem is that it is a bit inconsistent: When you create an invoice
with a pre-existing buyer email, it sets both refund and blob email but
when you set the refund, it does not set the buyer. That would mean on
export, we would need to add 2 columns for possible emails, which is a bit
of a mess
ᐧ

**Comment by NicolasDorier** [comment]
@Kukks I think just showing the RedundMail is enough.

**Comment by Kukks** [comment]
For me, I need the buyer email to be set as the refund email is not available through the current API. One example of this use-case is the ticketing system we used for BTCPayDay  where I needed the invoice email to send the ticket. I did not care if it was a refund email or a buyer email, as long as it was the recipient.

One solution is to make the get invoice  method populate the buyer email from the refund email on load instead of mutating the data upon refund email being set. This solves it for the Bitpay API and for exports in one go

**Comment by NicolasDorier** [comment]
`One solution is to make the get invoice method populate the buyer email from the refund email on load` I think this is good yes.

**Pull request closed without merging**
