### PR TITLE
Design updates

### PR DESCRIPTION
**Pull request by dennisreimann**
Includes update from:

- btcpayserver/btcpayserver-design#10
- btcpayserver/btcpayserver-design#13
- btcpayserver/btcpayserver-design#20
- btcpayserver/btcpayserver-design#9
- btcpayserver/btcpayserver-design#15
- btcpayserver/btcpayserver-design#21
- btcpayserver/btcpayserver-design#26
- btcpayserver/btcpayserver-design#27

### CODE REVIEW

**Comment by dstrukt** [comment]
Some Notes:

Checkboxes:
- The top & bottom margins should be updated on the `.form-check`
`margin-bottom: 1rem;`
`margin-top: 1rem;`
- The hover transition feels a bit fast compared to the `input` fields, ideally they should be the same.
- The padding between the checkbox element and the label text should be a minimum of `0.5rem` but `0.75rem` could also work ... was playing around with the padding/margin and `2.25rem` for the offsets on `.form-check-input` and `.form-check` seems to be a nice balance.
Screen Shot 2022-04-06 at 4 30 22 PM

[STILL AUDITING, WILL LIKELY UPDATE]

**Comment by dennisreimann** [comment]
@dstrukt Addressed your points and also added btcpayserver/btcpayserver-design#26.

> I'm liking the drop-shadow seeing it implemented, but I'm also debating if it's too much in context with everything .. hmmm, what do you think?

I think it's good :)

**Comment by dennisreimann** [comment]
@dstrukt Let's wrap it up here and tackle the other things in a new PR after v1.5. 🙌

**Review by dstrukt — APPROVED** [review]
LGTM, we'll tackle more in the next PR.

**Review by pavlenex — APPROVED** [review]
Nice updates, tACK

**Pull request merged**
