### PR TITLE
Make sure navbar looks good on smaller screen sizes

### PR DESCRIPTION
**Pull request by bolatovumar**
Addresses #1458

### CODE REVIEW

**Comment by Kukks** [comment]
I'll leave this one to @dennisreimann  to review, I'm not sure if the hard-coded light/dark check is good since we can have other darker themes.

**Comment by Kukks** [comment]
I am thinking this needs to be fixed in their respective theme files where:
 `*-dark` styles are light on dark themes
 `*-light` styles are dark on dark themes
vice versa for light themes

**Comment by dennisreimann** [comment]
Yes, as @Kukks said I think we should refrain from using the light/dark-classes offered by Bootstrap. Instead we should use something more intention revealing.

I'll take a closer look later today.

**Comment by Kukks** [comment]
superseded by #1466

**Pull request closed without merging**
