### PR TITLE
Wallet: Label filter dropdown

### LINKED ISSUE #5722: Unusual positioning of the filter and clear filter button UI for wallet  labels
On mobile the positioning of the labels looks awkward mostly due to the clear button and filter who take majority of the screen.
This issue shouldn't be tackled until discussion happens on design meeting and mockup is posted.

image

### PR DESCRIPTION
**Pull request by dennisreimann**
Uses a dropdown component for the label filter, which also work on mobile. Closes #5722.

mobile

filter

label

### CODE REVIEW

**Review by dstrukt — APPROVED** [review]
`From Mom` :joy:

tACK - LGTM

**Comment by pavlenex** [comment]
Something is off, basically generated a bunch of transaction via cheatmode on a newly initiated stores and behaviour is quite inconsistent a) wallet label color isn't applied, filter button doesn't exist c) export button is on the left. https://staging.streamable.com/9u1a64

**Comment by dennisreimann** [comment]
> a) wallet label color isn't applied, filter button doesn't exist 

The Filter option is only present when there are labels, the cheat mode does not assign any label. The label color isn't applied on label creation, but it's present afterwards.

> c) export button is on the left

Fixed.

**Comment by pavlenex** [comment]
I am aware cheat mode doesn't assign a label, check the video, I generated labels by hand and the experience is just off to what it normally is.

**Comment by dennisreimann** [comment]
As discussed in yesterday's dev meeting, the behaviour here (no label color when adding) is inline with the behaviour before this PR. So we could improve that as well, but that's beyond the simple fix we're aiming for here.

**Pull request merged**
