### PR TITLE
Allow POS to redirect invoices automatically after paid

### LINKED ISSUE #730: PoS - redirect to main screen a few seconds after payment
**Is your feature request related to a problem? Please describe.**
In a public Point of Sale, a customer should always see the main screen. 
Currently, if a customer make a payment and doesn't return to the main screen manually, the next customer will not see the main screen but will be presented with the receipt of the previous customer (which is terrible UX).  

**Describe the solution you'd like**
In a PoS app, it should redirect automatically to the main screen a few seconds after a successful payment

### PR DESCRIPTION
**Pull request by Kukks**
closes #730

### CODE REVIEW

**Comment by NicolasDorier** [comment]
You are on fire today. I think this should be a store property in checkout experience though.

**Comment by Kukks** [comment]
I ragequit Shekiro as well 🗡

**Comment by Kukks** [comment]
> You are on fire today. I think this should be a store property in checkout experience though.

I don't fully agree. I can imagine this only being wanted on a POS app for a physical location but not on their online store or their online POS which would cause people to create multiple stores to get around it

**Comment by NicolasDorier** [comment]
image

With the settings at app level being "Yes/No/Same as store settings"

**Comment by NicolasDorier** [comment]
added `bool? RedirectAutomatically` to invoice type of NBitpay

**Comment by Kukks** [comment]
changes done and tested @NicolasDorier

**Pull request merged**
