### PR TITLE
Editor: Use offcanvas for all breakpoints

### LINKED ISSUE #6436: Improve products editor UX
### Discussed in https://github.com/btcpayserver/btcpayserver/discussions/6431

<div type='discussions-op-text'>

<sup>Originally posted by **jaonoctus** November 25, 2024</sup>
Right now, If i have a big list of products in the POS app, I have to scroll all way up to edit the product I just clicked.

This box should be a drawer, a popup/modal or at least a sticky element in the screen.

image

image

</div>

### PR DESCRIPTION
**Pull request by dennisreimann**
Avoids scrolling the editor out of the viewport. Closes #6436.

Done for the POS/Crowdfund editor, as well as the Forms one.

### CODE REVIEW

**Comment by pavlenex** [comment]
Hm, I am not sure I understood how this implementation resolves user problem.

To make sure we're on the same page, the user said here https://github.com/btcpayserver/btcpayserver/discussions/6431#discussioncomment-11377818

>  If i have a big list of products in the POS app, I have to scroll all way up to edit the product I just clicked

The implemented solution looks like this, which I don't mind, execept it looks kinda shrinked, but I don't understnand how it addresses the original problem, it actually blanks out scrollable items and doesn't address the scroll. Perhaps it's my browser (Safari) @dennisreimann ?

https://github.com/user-attachments/assets/6f3b7b5e-4798-4ca2-8d40-24f0ea7d0dca

**Comment by pavlenex** [comment]
@jaonoctus perhaps you want to test it locally to ensure it resolves the issue?

**Review by jaonoctus — APPROVED** [review]
@pavlenex I'm happy with the proposed solution by @dennisreimann

Concept ACK

**Comment by jaonoctus** [comment]
@pavlenex If you don't mind, could you drop a link on how to test it? Would be a matter of just checkout this branch? 

_I have the docker installation running on a proxmox vm_

**Comment by jaonoctus** [comment]
tACK

image

**Review by jaonoctus — APPROVED** [review]
tACK now 😎 

## desktop view

image

## mobile view

[Update-Point-of-Sale.webm](https://github.com/user-attachments/assets/0bd85557-c99a-4fef-95c2-2c1e0f792438)

**Comment by jaonoctus** [comment]
@dennisreimann d87b5cb7c71a58388c64cc595a00272960b1506b unverified commits?

**Pull request merged**
