### PR TITLE
Mentioning Zapier in readme

### PR DESCRIPTION
**Pull request by woutersamaey**

### CODE REVIEW

**Review by pavlenex — COMMENTED** [review]
Let's not try to pick favourites when it comes to integrations. Instead, let's add Zapier to docs and Btcpayserver.org. Not many people pay attention to readme, if we add Zapier we'd have to add a bunch more.

**Comment by woutersamaey** [comment]
Understood, except this is generally useful to everyone as opposed to an integration like Woocommerce that's only for people who run Woocommerce. That was my reasoning.

**Comment by woutersamaey** [comment]
If you feel this is picking favorites, we can add a section "Integrations" and link to the other repos. Sure, why not?

**Review by Kukks — CHANGES_REQUESTED** [review]
This belongs on the website and docs not the readme.

**Comment by woutersamaey** [comment]
Ok, I will aim to add to the docs and on the website instead.

**Pull request closed without merging**
