### PR TITLE
New default theme

### LINKED ISSUE #1429: Default theme coloring re-design
After redesign of the invoice re-design and login page (#1428) it would be good if we can make colors consistent in our default theme, without doing anything fancy but color changes, to avoid breaking changes for users using default theme.

We can either leave classic theme as a legacy and keep new one as default, that's something that we should discuss.

Unfortunately, we do not have mockups available for it yet, but it should be done like @dennisreimann did for the #1137 Casa theme. 

Design guidelines are available [here](https://www.figma.com/file/C7Xyq0FlxgFW8vaBr8ht1z/BTCPAY?node-id=0%3A1), and should be consistent with what we have [here](https://www.figma.com/file/C7Xyq0FlxgFW8vaBr8ht1z/BTCPAY?node-id=25%3A0). 

If time allows of course a dark theme on top would be great, if not we can do that in the future.

### PR DESCRIPTION
**Pull request by dennisreimann**
Based on the discussion in the [accompanying issue](/btcpayserver/btcpayserver/issues/1429). Closes #1429.

Helpful for reviewing: Use the [kitchensink page](http://127.0.0.1:14142/_bootstrap_kitchensink.html?theme=default) to see all design permutations – especially regarding the light/dark theme.

### CODE REVIEW

**Comment by pavlenex** [comment]
Great work so far Dennis. I'll only comment on the visuals, until we perfect that, then we'll talk with @rockstardev to see how we can tie all this together.

## Modern Theme

1.. I'm not sure if this will be called modern theme, or simply became the new default.

2. I suggest we change the color  of header and footer to match colors & font on our new upcoming site. Just a quick demo of what I'm thinking.
clean (We'd have to figure out fonts and how to handle the logo, I'd personally also increase footer font a bit while we're there)

3. We intend to remove that long-term for sure, but it would be cool if we can somehow make it to at least match the colors, it stands out way too much the way it is set up now.

4. I suggest we don't change the size of H1,H2,H3,H4 compared to our "classic theme".

**Comment by dennisreimann** [comment]
Current state.

light

dark

**Comment by pavlenex** [comment]
Some more feedback:

- Hover text on the header menu is still white for me
- I'd keep the text size standard and the same as in the older theme (except for the footer where font seems perfect now) since it can break some layouts (see wallet buttons example.
header
WALLET

- We should handle logo for the point of sale app the same way we did for the header
POS

- [Not really big deal] Some text is blue for this theme, I'm not bothered by it, but perhaps would be cool to standardize it with green, though perhaps the intention of that text was to stick out? @NicolasDorier 
Invoices filter help

**Comment by dennisreimann** [comment]
@pavlenex Decreased the font-size to 14px (matches the classic theme) and had to fiddle around with the colors to fix some things on the POS page. 

Regarding the code/fixed-width font: I'd advise to keep it like that to make it stick out.

**Comment by dennisreimann** [comment]
Worked with @pavlenex on this directly and here's the current state of the home page. Put the pages side by side to give a better impression of the coloring: 

home-light

home-dark

**Comment by NicolasDorier** [comment]
wow awesome, is it ready to merge?

**Comment by britttttk** [comment]
@dennisreimann how do you turn on the dark mode of the default theme? I only saw the light mode.

**Comment by pavlenex** [comment]
@NicolasDorier Not yet, we have some more testing to do today, but should be ready in few hours.
@britttttk it auto-detects your system preference, if you select dark mode on Windows you can see it.
@dennisreimann I wanted to suggest we add dark mode toggle or users, at least as a drop down, while auto-detect is awesome, people may have different preferences and someone using light mode for the system may want to use dark theme on BTCPay. Makes sense, right?

**Comment by dennisreimann** [comment]
Made the theme selection explicit now, so that we do not use the system preferences but offer choosing light (which is the default) or dark now. In addition to these there are still the CLassic and Casa themes.

From my point of view it's done now, please test and let me know what might still need changing.

**Comment by Kukks** [comment]
image
Are we sure we dont want to remove the rounded borders? The lighter color makes the soft edges a bit much imo

I really dislike the different color in footer compared to the rest:
image

**Comment by Kukks** [comment]
When adding a label to a transaction, it gets a bit weird
https://i.imgur.com/uXYq6tr.gifv

**Comment by Kukks** [comment]
Expanding invoice details looks a bit disorganized without any borders

image

**Comment by Kukks** [comment]
Coin selection for selected utxos is off
image

**Comment by Kukks** [comment]
Dark mode border color is wrong in send wallet (both for coin selection and when doing multiple destinations)
https://i.imgur.com/6JAJnJ8.png
image

**Comment by Kukks** [comment]
same issue with borders in add api key about dark mode and borders

**Comment by dennisreimann** [comment]
> Please don't hate me :) 

Awesome, thanks for all the things you brought up – will fix them later today!

**Comment by dennisreimann** [comment]
@Kukks 

> I really dislike the different color in footer compared to the rest

Updated, it now uses the darker color so that it also matches the new website's footer.

> Are we sure we dont want to remove the rounded borders? The lighter color makes the soft edges a bit much imo

Buttons are as defined on Figma – we might finetune them later (same goes for the the footer color).

> When adding a label to a transaction, it gets a bit weird
> leaving a comment behaves the same

This is addressed in #1440.

Will address the rest later today or tomorrow.

**Comment by dennisreimann** [comment]
> Expanding invoice details looks a bit disorganized without any borders

I've increased the inset to make it clearer.

classic

default

**Comment by NicolasDorier** [comment]
tests don't pass, you must have broken something

**Comment by dennisreimann** [comment]
@Kukks Dark theme border colors are fixed now. The Coin Selection form had several tiny improvements, which I separated out into #1443.

@NicolasDorier I don't think that the `BTCPayServer.Tests.PayJoinTests.CanUseBIP79Client` failure is related to my changes as I also saw it [failing on master](https://app.circleci.com/pipelines/github/btcpayserver/btcpayserver/2837/workflows/1f3d87e0-3c80-4bda-b7c8-17e2c632ad6d/jobs/6851).

I don't know what to do about the `401 Unauthorized` errors in the [integration tests](https://app.circleci.com/pipelines/github/btcpayserver/btcpayserver/2838/workflows/27b7e0a5-9b4f-4e91-9f89-5da65ad55d14/jobs/6855/parallel-runs/0/steps/0-102), to me this also seems unrelated. Let me know if there is something I can do and I'll try to fix these :)

**Comment by dennisreimann** [comment]
Closing this in favor of #1447 (and me being foolish).

**Pull request closed without merging**
