### PR TITLE
Content Consistency Updates (1.4.0)

### PR DESCRIPTION
**Pull request by dstrukt**
Might make sense to merge this after @dennisreimann's latest changes.

These are just aesthetic changes, header sizes, paddings, etc... to make things consistent, been a lot easier to spot with the latest updates.

A few minor tweaks I'd like to improve with this PR, but I need some help with:

- [x]  Fix active state when "Account" is selected + sub-navigation @dennisreimann 
- [x]  "Profile" -> "Account" on Account tabbed navigation
- [x]  Change "General Settings" to "General" in Store Settings & make it the first tab
- [x]  "Email Server" -> "Email" in Server Settings in tabbed menu, change the content title from "Email" -> "Email Server"

The first item will close out one of the issues (https://github.com/btcpayserver/btcpayserver/issues/3180).

Added "Language" section:
Screen Shot 2022-01-15 at 4 28 34 PM

Moves API Key CTA to top right:
Screen Shot 2022-01-15 at 5 45 45 PM

### CODE REVIEW

**Comment by pavlenex** [comment]
To answer questions, I agree with all except these two:

> Move "Language" section in "Checkout Appearance" to "General" in Store Settings

No, because this isn't a store language it's the language of the checkout page, so it's appropriate where it is.

> "Checkout Appearance" -> "Checkout" in Store Settings tabbed menu

I don't think we should change it, it communicates what it really is, the appearance of your checkout page. If we do `checkout` it may confuse people thinking it's payment method setting or something else.

**Comment by dstrukt** [comment]
Ahh good call on the Language, thought this was App wide, noted.

That's a good point, I think I just took issue with it because there were multiple types of modifications, not just Appearance, but maybe it's just because that word doesn't feels like it captures everything, but I have no alternative suggestions, so will drop the issue.

**Comment by NicolasDorier** [comment]
This probably break something in the CanSetupMail test ping @dennisreimann

**Comment by dstrukt** [comment]
Oh, wow the account text switch was more simple than I anticipated, thought more would be involved.

**Review by dennisreimann — APPROVED** [review]
All TODOs done now :)

The failing link check is unrelated - this one should be merged next, I'll then finish #3323 based on this.

**Pull request merged**
