### PR TITLE
Implement topup invoices

### PR DESCRIPTION
**Pull request by NicolasDorier**
Implement idea on https://github.com/btcpayserver/btcpayserver/discussions/2659

There is still a bug on top-up invoices with payjoin that I need to solve. I also need to add a test for this.

An invoice with an amount of 0 now has a special meaning: The first payment to it will change its amount to the amount of the payment.

### CODE REVIEW

**Comment by Kukks** [comment]
> Implement idea on #2659
> 
> There is still a bug on top-up invoices with payjoin that I need to solve. I also need to add a test for this.
> 
> An invoice with an amount of 0 now has a special meaning: The first payment to it will change its amount to the amount of the payment.

Please change it from amount `0` to `null`. There are other use-cases for 0 amount invoices today

**Review by Kukks — COMMENTED** [review]
I am surprised that this did not break all sorts of things in the system

**Comment by NicolasDorier** [comment]
> Please change it from amount 0 to null. There are other use-cases for 0 amount invoices today

What use case? a 0 invoice is instantly confirmed.

**Comment by NicolasDorier** [comment]
There is a use case for 0 invoice: To implement "free product". So I need to use `-1`, or do it properly with a flag.

**Comment by NicolasDorier** [comment]
supersede by #2730

**Pull request closed without merging**
