### PR TITLE
Add Supporters section to readme

### PR DESCRIPTION
**Pull request by pavlenex**
This PR:
- Removes the list of mentioned altcoins (looked like a distraction) and instead provides the exteral link to the list.
- Adds SquareCrypto Logo
- Adds Supporters section

This is an early attempt to structure supporters, so if anybody has better ideas how to present the sponsors, let me know.

Update: The appearance after modifications.
Screenshot 2019-11-05 at 23 12 43

### CODE REVIEW

**Comment by rockstardev** [comment]
I would move Supporters section after Introduction, before Table of Contents. Once that's done, I would go for merge.

**Comment by pavlenex** [comment]
@rockstardev I don't feel good about putting the supporters there. Simply, once someone reads through the features and stuff, there's a CTA at the bottom on how to support the project. I think there's way too much stuff going on in the above the fold, that supporters icons would be something people would easily scan through and ignore.

Opened to see what others think about this, I'd personally leave it at the bottom.

**Comment by pavlenex** [comment]
There's some excessive spacing on the SquareCrypto logo, please hold back merging this until I double-check.

**Comment by pavlenex** [comment]
After applying svg, it now looks like this
Screenshot 2019-11-06 at 09 42 48

**Pull request closed without merging**
