### PR TITLE
LN Settings: Show only node host name

### LINKED ISSUE #4923: [Bug]: Minor Security Issue - Please Mask LNDHub Credentials in Lightning Settings Page
### What is your BTCPay version?

 v1.9.2

### How did you deploy BTCPay Server?

Docker

### What happened?

I exposed my LNDHub (Alby) credentials to co-admins of my testing server.

### How did you encounter this bug?

1. Setup Your LNDHub Lightning Wallet and save the settings
2. In the left menu navigate to Wallets - Lightning
3. Behind "Custom Node" the Login String including username and password is visible

Imho there is no need to expose existing login details of a node at this place. As the Wallet owner I should be able to retrieve this  info from my wallet provider.

### Relevant log output

```shell
none
```

### What browser do you use?

Firefox

### Additional information

none

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

### PR DESCRIPTION
**Pull request by dennisreimann**
That information is enough for the overview. Closes #4923.

grafik

### CODE REVIEW

**Comment by pavlenex** [comment]
@petzsch can you test this PR?

**Comment by petzsch** [comment]
This PR  only changed it for the Lightning Settings page:
grafik

on the regular Lightning (overview) it's still visible:
grafik

Can we change that page as well? @dennisreimann

**Comment by dennisreimann** [comment]
@petzsch thanks for the pointer, done

**Comment by dennisreimann** [comment]
@petzsch yes we cannot redact it there.

**Review by dstrukt — APPROVED** [review]
Great catch @petzsch 

LGTM in those two instances

**Review by Kukks — APPROVED** [review]

**Pull request merged**
