### PR TITLE
Add LNbank plugin

### PR DESCRIPTION
**Pull request by dennisreimann**
Based on #2410 and WIP -- most of the general app migration is done, but there are still some errors and things to be discussed.

### CODE REVIEW

**Comment by dennisreimann** [comment]
Rebased on the current state of #2410 -- basics are working now :)

**Review by Kukks — CHANGES_REQUESTED** [review]
Can you somehow move all code changes related directly to BTCPay into a dedicated commit (and also a branch + pull request) and then rebase this branch on top of it?

**Comment by dennisreimann** [comment]
Yup, will try -- that should be mainly what's separated in 108162909da33f4f2226ce49ca776752c67d6c84 already.

**Comment by dennisreimann** [comment]
Will rebase and update once #2715 and #2716 are merged.

**Comment by dennisreimann** [comment]
> Can you somehow move all code changes related directly to BTCPay into a dedicated commit (and also a branch + pull request) and then rebase this branch on top of it?

@kukks Done ✅

**Comment by jaonoctus** [comment]
image

yay!

**Comment by jaonoctus** [comment]
Tips for who also wants to test in regtest:

1. generate an address for merchant: `./docker-merchant-lightning-cli.sh newaddr`
2. send funds to merchant: `./docker-bitcoin-cli.sh sendtoaddress "merchant_addr_here" 1`
3. generate an address for customer: `./docker-customer-lightning-cli.sh newaddr`
4. send funds to customer: `./docker-bitcoin-cli.sh sendtoaddress "customer_addr_here" 1`
5. generate some blocks: `./docker-bitcoin-generate.sh 100`
6. fund channels between customer and merchant: `./docker-lightning-channel-setup.sh`
7. pay the invoice generated via LNBank tab: `./docker-customer-lightning-cli.sh pay invoice_here`

And Voila!

```json
{
   "destination": "02c1254783f731b6034941e1ed753cb354cc4f1456b6feb03f96aa6e037d486d5d",
   "payment_hash": "4d195eaf3f6dbd1b289050390eff5c2e4c4d1642d593848a68f20fc4dda10832",
   "created_at": 1630181650.284,
   "parts": 1,
   "msatoshi": 21000,
   "amount_msat": "21000msat",
   "msatoshi_sent": 21000,
   "amount_sent_msat": "21000msat",
   "payment_preimage": "def5b0cd416480add5b40de25b1429a43dd78319400597f7fed73fbebc6f492e",
   "status": "complete"
}
```

image

**Comment by jaonoctus** [comment]
@dennisreimann quick question, 

Is it possible to link the wallet created via LNBank with the store?

**Comment by dennisreimann** [comment]
Yes, it will be: you'll be able to add an LNbank wallet as your stores custom LN node. This way the admin can open up an instance's LN node and share it with the instance users.

**Review by jaonoctus — APPROVED** [review]
@dennisreimann YOU'RE THE GOAT! 🐐

**Comment by dennisreimann** [comment]
Thanks for your detailed guide on how to test the workflow! 
I've automated the setup via script (using Greenfield API) already, can share that in the Tests subproject.

**Comment by pavlenex** [comment]
@dennisreimann  I managed to crash it 😄 

```
NullReferenceException: Object reference not set to an instance of an object.
BTCPayServer.Services.BTCPayServerEnvironment.get_ExpectedProtocol() in BTCPayServerEnvironment.cs
+
        public string ExpectedProtocol => httpContext.HttpContext.Request.Scheme;
AspNetCore.Views_Shared__Layout+<>c__DisplayClass53_0+<<ExecuteAsync>b__1>d.MoveNext() in _Layout.cshtml
+
                <span>BTCPay is expecting you to access this website from <b>@(Env.ExpectedProtocol)://@(Env.ExpectedHost)/</b>. If you use a reverse proxy, please set the <b>X-Forwarded-Proto</b> header to <b id="browserScheme">@(Env.ExpectedProtocol)</b> (<a href="https://docs.btcpayserver.org/FAQ/FAQ-Deployment/#cause-3-btcpay-is-expecting-you-to-access-this-website-from" target="_blank" class="alert-link" rel="noreferrer noopener">More information</a>)</span>
Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
AspNetCore.Views_Shared__Layout.ExecuteAsync() in _Layout.cshtml
+
<html lang="en"@(Env.IsDeveloping ? " data-devenv" : "")>
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, bool invokeViewStarts)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable<int> statusCode)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable<int> statusCode)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0<TFilter, TFilterAsync>(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext<TFilter, TFilterAsync>(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|27_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in BTCpayMiddleware.cs
+
            await _Next(httpContext);
Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in HeadersOverrideMiddleware.cs
+
            await _Next(httpContext);
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

To repro, do not create a store or wallet inside BTCPay, and try to generate invoice with LNBank.

**Comment by pavlenex** [comment]
Also @dennisreimann What kind of access is needed so a non-admin can use LNBank? What is needed on admin side?

**Comment by pavlenex** [comment]
@dennisreimann I am very reliable able to replicate.
1. Deploy in regtest.
2. Go to LNBank
3. Create a wallet
4. Go to receive
5. Enter amount
6. Create invoice

Note that nor store or wallet have been set up in the store settings.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Services.BTCPayServerEnvironment.get_ExpectedProtocol() in /Users/p/Downloads/btcpayserver/btcpayserver/BTCPayServer/Services/BTCPayServerEnvironment.cs:line 42
   at AspNetCore.Views_Shared__Layout.<>c__DisplayClass55_0.<<ExecuteAsync>b__1>d.MoveNext() in /Users/p/Downloads/btcpayserver/btcpayserver/BTCPayServer/Views/Shared/_Layout.cshtml:line 112
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
   at AspNetCore.Views_Shared__Layout.ExecuteAsync() in /Users/p/Downloads/btcpayserver/btcpayserver/BTCPayServer/Views/Shared/_Layout.cshtml:line 22
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /Users/p/Downloads/btcpayserver/btcpayserver/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 94
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /Users/p/Downloads/btcpayserver/btcpayserver/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 29
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by MaxHillebrand** [comment]
super useless comment - but this is looking amazing! Keep up the great work all :black_heart:

**Comment by dennisreimann** [comment]
@Kukks Your former change request has been addressed and the tests are fixed now, let's finish this! :D

**Comment by dennisreimann** [comment]
Once btcpayserver/BTCPayServer.Lightning#41 is merged, this plugin is good to go :rocket: 

Now the Lightning setup page also features a neat way of connecting LNbank wallets directly, instead of using connection strings.

lnbank

Also improved the settings overview, so that it shows the relevant details instead of the raw connection string.

connection-settings

**Comment by dennisreimann** [comment]
@Kukks How shall I progress here to publish the plugin once the Lightning PR is merged? This PR won't be merged here from what I understood and I saw you also added a script to pack the plugin.

**Review by Kukks — CHANGES_REQUESTED** [review]
Please extract any changes youve done to BTCPay in a separate PR as this one is not mant to be merged.

**Comment by Kukks** [comment]
> @Kukks How shall I progress here to publish the plugin once the Lightning PR is merged? This PR won't be merged here from what I understood and I saw you also added a script to pack the plugin.

* You pack the plugin
* You open a PR with the output of the packing script to https://github.com/btcpayserver/btcpayserver-plugins

**Comment by dennisreimann** [comment]
@Kukks Alright, extracted the non plugin related changes.

Will pack the plugin and submit a PR once the Lightning PR is done.

**Comment by johnsBeharry** [comment]
Hey, this is really exciting! Would love to get some more details on how this works.

1. Is lnbank connected to one or more stores for the current user?
2. Is it possible for a single user to have multiple banks?
3. Also is it using the same invoice creation API or does it have its own? Related: Does it support lightning address and lnurl as the new stores/invoices do?

**Comment by Kukks** [comment]
> Hey, this is really exciting! Would love to get some more details on how this works.
> 
> 1. Is lnbank connected to one or more stores for the current user?
> 2. Is it possible for a single user to have multiple banks?
> 3. Also is it using the same invoice creation API or does it have its own? Related: Does it support lightning address and lnurl as the new stores/invoices do?

Lnbank uses the specified internal node that btcpay is provided on startup. 

Every user on btcpay can create multiple Lnbank wallets.

Any Lnbank wallet can be integrated into any btcpay store. 

From an api point of view, everything is the same. Consuming the api does not require additional knowledge around Lnbank - it just works.

 This means if the internal lightning node supports lnurl, it will all work. 

The most interesting part is that you can use Lnbank wallets on other btcpay instances. You can one up this and even specify an Lnbank wallet as the internal wallet for a whole btcpay instance, which in turn can have Lnbank installed there too and provide sub lnbank wallets for that lnbank wallet!

**Comment by iBobik** [comment]
Nice plugin, will help a lot in my use-case.

Just a question from user pov:
Will it be compatible with another LND UIs supporting multiwallets like ThunderHub, LNDHub or LNbits? In a way that I can manage the same wallets - e.g. receive payments by BtcPay into LNbank wallet and then for the same wallet issue LNURL-Withdraw voucher in ThunderHub?

**Comment by otech47** [comment]
Hi nice plugin it came very close to fitting my use case so wanted to leave this feedback:

I am trying to set up a sort of team disbursements system for my company using BTCPayServer

The company has a BTCPayServer set up with its own private company on-chain/off-chain funds and manages channels/liquidity

I tried to create LNBank wallets for each team member and at the end of each month I would like to be able to "deposit" some sats into each LNBank wallet

Then I would create BTCPayServer users (non-admin) for each team member in the company so they can access their LNBank wallet and use the Send function to move the funds out to non-custodial or to make purchases via LN

I tried playing with creating a Store as well either shared by all team members or maybe 1 store per team member so they could create their own on-chain hot wallets if they want.

Couldn't quite accomplish this and not sure what the exact solution might be but some key points:

1. LNBank Wallets are not shared across BTCPayServer users so I can't deposit funds into an LNBank Wallet that another BTCPS user can see when they login
2. The one-store-per-team-member idea could work nicely so they can also make their own an on-chain hot wallet as well but the core use case is not necessarily to provide them all of the extra store functionality so just a nice-to-have.. but maybe dumb unworkable idea
3. Ideally would be able to make sure only 1 company admin user can see all LNBank wallets and other non-admins can just see their own wallets but not Send from wallets that aren't theirs...

Where exactly is the source for this plugin? For v1.2.0.0?

Maybe can try to build this myself but also may be willing to contract someone to help (my .NET skills are not great if that's what the plugin is written in)

Or if more APIs for LNBank were exposed I could work with that too

Thanks for all the work!

**Comment by otech47** [comment]
Hi nice plugin it came very close to fitting my use case so wanted to leave this feedback:

I am trying to set up a sort of team disbursements system for my company using BTCPayServer

The company has a BTCPayServer set up with its own private company on-chain/off-chain funds and manages channels/liquidity

I tried to create LNBank wallets for each team member and at the end of each month I would like to be able to "deposit" some sats into each LNBank wallet

Then I would create BTCPayServer users (non-admin) for each team member in the company so they can access their LNBank wallet and use the Send function to move the funds out to non-custodial or to make purchases via LN

I tried playing with creating a Store as well either shared by all team members or maybe 1 store per team member so they could create their own on-chain hot wallets if they want.

Couldn't quite accomplish this and not sure what the exact solution might be but some key points:

1. LNBank Wallets are not shared across BTCPayServer users so I can't deposit funds into an LNBank Wallet that another BTCPS user can see when they login
2. The one-store-per-team-member idea could work nicely so they can also make their own an on-chain hot wallet as well but the core use case is not necessarily to provide them all of the extra store functionality so just a nice-to-have.. but maybe dumb unworkable idea
3. Ideally would be able to make sure only 1 company admin user can see all LNBank wallets and other non-admins can just see their own wallets but not Send from wallets that aren't theirs...

Where exactly is the source for this plugin? For v1.2.0.0?

Maybe can try to build this myself but also may be willing to contract someone to help (my .NET skills are not great if that's what the plugin is written in)

Or if more APIs for LNBank were exposed I could work with that too

Thanks for all the work! @dennisreimann

**Comment by pavlenex** [comment]
@otech47 Good feedback, thanks. Just to make sure this doesn't get unnoticed, I'm pinging @dennisreimann but he's afk for a few days. 

The source can be found here https://github.com/btcpayserver/btcpayserver-plugins/tree/master/LNbank as with all plugins, we have a `plugins` repo for it. 

Would be great if you could contribute to the efforts :)

**Comment by dennisreimann** [comment]
Hey @otech47, thanks for the feedback and insights on how you'd like to use the plugin!

> LNBank Wallets are not shared across BTCPayServer users so I can't deposit funds into an LNBank Wallet that another BTCPS user can see when they login

Yes, LNbank wallets are currently per user. I think for your use case it would require the admin to have access to the wallet, at least to generate invoice that then could get paid by the admin. Note that since v1.2.0 of LNbank, each wallet has it's own LNURL, which could also be used to achieve what you are looking for: The LNURL is static and could be paid by the admin without needing access to each users wallet.

Another way to tackle that would be to allow users to grant access to their wallets to other users as well. I haven't had that as a feature request until now, but I'll keep it in the back of my head. 

By the way, I track feature requests and bug reports for LNbank here: https://github.com/dennisreimann/btcpayserver/issues

That repo is also where the plugin code lives: https://github.com/dennisreimann/btcpayserver/tree/plugins/BTCPayServer.Plugins.LNbank

**Pull request closed without merging**
