### PR TITLE
Improve "Pull payments" table look

### PR DESCRIPTION
**Pull request by bolatovumar**
Before:
Screen Shot 2020-07-11 at 8 54 12 PM

After:
Screen Shot 2020-07-11 at 8 52 06 PM

Updated version after feedback from @britttttk and @dennisreimann:

Screen Shot 2020-07-12 at 12 46 40 PM

Screen Shot 2020-07-12 at 12 47 13 PM

Screen Shot 2020-07-12 at 12 46 18 PM

Screen Shot 2020-07-12 at 12 47 28 PM

### CODE REVIEW

**Comment by pavlenex** [comment]
Closes #1732

**Comment by britttttk** [comment]
@bolatovumar looks awesome!

Can you also left align the create and remove copy for tooltip in this issue so we can close the issue as @pavlenex mentioned, if not I think it should not close it.

**Comment by pavlenex** [comment]
@britttttk I assume you're referring to #1726? As the issue closes #1732 already imo.

**Comment by dennisreimann** [comment]
Nice! Just one nit comments: To be consistent with most of what I've recently seen, can you please right align the action column?

**Comment by bolatovumar** [comment]
> Nice! Just one nit comments: To be consistent with most of what I've recently seen, can you please right align the action column?

Will do



> @bolatovumar tACK, looks awesome!
> 
> Can you also left align the create and remove copy for tooltip in this issue so we can close the issue as @pavlenex mentioned, if not I think it should not close it.

Yeah, can do.

**Comment by bolatovumar** [comment]
Looks like tests are failing because https://www.okcoin.com is down.

Screen Shot 2020-07-12 at 12 58 11 PM

Screen Shot 2020-07-12 at 12 59 46 PM

**Comment by rockstardev** [comment]
Tests are good, I've fixed the problem causing x here in #1734

**Pull request merged**
