### PR TITLE
Update license

### PR DESCRIPTION
**Pull request by yahiheb**

### CODE REVIEW

**Comment by dstrukt** [comment]
couldn't this be solved with a dynamic {current_year} output vs. a manual update to the date? maybe there's something i'm not aware of, disregard if so.

cc @dennisreimann

**Comment by dennisreimann** [comment]
I haven't found a canocical resource on this, but from what I've read (e.g. [here](https://opensource.stackexchange.com/questions/5778/why-do-licenses-such-as-the-mit-license-specify-a-single-year) and [here](https://opensource.stackexchange.com/questions/1522/what-should-be-written-in-mit-license-year-full-name) it should be OK to have only the year of the original publication. 

If necessary, let's just [automate this](https://github.com/marketplace/actions/license-year-updater) tedious task.

**Comment by dstrukt** [comment]
Agree @dennisreimann.

Sounds like we could get away with the singular year after a quick read, but if ya'll didn't interpret it the same and we're still not certain, let's just automate the range.

**Review by dennisreimann — APPROVED** [review]

**Review by Billiej88 — COMMENTED** [review]
Changes

**Pull request merged**
