### PR TITLE
UI: Store setup finetuning

### PR DESCRIPTION
**Pull request by dennisreimann**
Incorporate @dstrukt's improvement feedback from [this comment](https://github.com/btcpayserver/btcpayserver/pull/2011#issuecomment-735909927).

Also improved the mobile version, which did not wrap.

## Light

light-1

light-3

## Dark

dark-1

dark-2

## Mobile

light-2

### CODE REVIEW

**Review by bolatovumar — APPROVED** [review]

**Review by Kukks — APPROVED** [review]
Did you remove the hints completely? If so, we should clean the Blob objects from it

**Comment by dennisreimann** [comment]
The hints are still presented as long as the wallet or lightning isn't set up yet. On the store setup page they aren't displayed as warnings anymore though – see e.g. the wallet hint in the first screenshot.

The warning sign gets displayed on the [list view](https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/Controllers/UserStoresController.cs#L138). This still relies in the `Hints` in the blob being present, but only checks for the on chain wallet.

I now tried to remove the hints from the blob and switch the checks to use the actual data like this:

```csharp
vm.HintWallet = vm.DerivationSchemes.Any(ds => ds.Enabled) == false;
vm.HintLightning = vm.LightningNodes.Any(ln => ln.Enabled) == false;
```

That works well on the store details page as the `DerivationSchemes` and `LightningNodes` data is already present. That's not the case for the list view, where this would need to be gathered. 

How do we want to proceed?

**Comment by dstrukt** [comment]
Looking good! Will get an updated mobile version (hadn't planned for the additional details).

**Review by pavlenex — APPROVED** [review]
tACK.

**Comment by Kukks** [comment]
> The hints are still presented as long as the wallet or lightning isn't set up yet. On the store setup page they aren't displayed as warnings anymore though – see e.g. the wallet hint in the first screenshot.
> 
> The warning sign gets displayed on the [list view](https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/Controllers/UserStoresController.cs#L138). This still relies in the `Hints` in the blob being present, but only checks for the on chain wallet.
> 
> I now tried to remove the hints from the blob and switch the checks to use the actual data like this:
> 
> ```cs
> vm.HintWallet = vm.DerivationSchemes.Any(ds => ds.Enabled) == false;
> vm.HintLightning = vm.LightningNodes.Any(ln => ln.Enabled) == false;
> ```
> 
> That works well on the store details page as the `DerivationSchemes` and `LightningNodes` data is already present. That's not the case for the list view, where this would need to be gathered.
> 
> How do we want to proceed?

Created a new issue from that comment. Let's merge

**Review by Kukks — APPROVED** [review]

**Comment by dstrukt** [comment]
(Also posted on the MM)

We should determine how important including the "Wallet" text on mobile is.

Here are some variations, the first being probably the most informative and least disruptive, second more minimal, third with everything included, but I don't love it, and if we decide this direction is the one to go in, I want to explore one last thing.

Screen Shot 2020-12-02 at 5 58 14 PM

**Pull request merged**
