### PR TITLE
(Not Completed) Arabic language

### PR DESCRIPTION
**Pull request by kemoantemo**
as i said on slack the arabic checkout page not good if there is no rtl style for the checkout page i maked the translation but i need help in the rtl display problem.
@rockstardev

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Can you resolve the conflicts?

**Comment by kemoantemo** [comment]
> Can you resolve the conflicts?

done

**Comment by kemoantemo** [comment]
still need rtl support

**Comment by NicolasDorier** [comment]
Anybody knows about it ? Can you do it ?

**Comment by NicolasDorier** [comment]
if we merge this, is it totally unusable? I am tempted to merge this for now and fix rtl in separate PR if that is kind of usable.

**Comment by kemoantemo** [comment]
some words go in other places that it shouldn't english will be better for arabian than that.

**Comment by britttttk** [comment]
@kemoantemo I moved your translation to [Transifex](https://www.transifex.com/btcpayserver/btcpayserver/). You can finish translating any remaining strings which have been added since you opened this PR. 

At this point, this PR is completely outdated and should be closed. 
I opened this as an issue #444

**Comment by Kukks** [comment]
I'm glad you realized I was too lazy to do it as soon as i created the language in transifex @britttttk  :P

**Comment by kemoantemo** [comment]
closed will go and work on transifex ty guys

**Pull request closed without merging**
