### PR TITLE
Document miscallenous features in the swagger doc

### PR DESCRIPTION
**Pull request by NicolasDorier**
We have some discovery issues with some hidden feature in BTCPay Server.
I decided to document them in the swagger docs

image

### CODE REVIEW

**Comment by pavlenex** [comment]
@NicolasDorier Just a note BitPay translator would be a good use for a plugin as discussed here #1923, in that case I'm not sure if it makes sense to add it now, just a thought.

**Comment by NicolasDorier** [comment]
we can remove it later if needed.
I am sad there are some hidden feature for now nobody can discover.

**Comment by pavlenex** [comment]
BitPay doesn't really force BIP70 so Translator itself may not be that widely used. Alright once we make it a plugin hopefully we can remove it, just wanted to tie the two issues so we don't loose context there.

**Comment by NicolasDorier** [comment]
if they do not force it we can remove it entirely then.

**Comment by NicolasDorier** [comment]
Will remove it entirely after this PR then

**Pull request merged**
