### PR TITLE
Rename PaymentData to PaymentDetails

### PR DESCRIPTION
**Pull request by collins-okafor**
This PR resolves `Rename PaymentData to PaymentDetails` task on the [BTCPay Server 2.0: Megathread](https://github.com/btcpayserver/btcpayserver/issues/5899#top)

### CODE REVIEW

**Comment by NicolasDorier** [comment]
What need to be renamed isn't the table, but the the types that are used as Payment Details in the PaymentData's Blobs.

**Comment by collins-okafor** [comment]
Hi @NicolasDorier pls, i couldn't find the PaymentData blob. I could really use some more clarification.

**Comment by NicolasDorier** [comment]
I think this issue is a bit too difficult for new comers, it's more difficult for me to explain than to do it.

**Comment by collins-okafor** [comment]
Pls can you recommend other new-comer issues for me

**Pull request closed without merging**
