### PR TITLE
Remove Ethereum support

### PR DESCRIPTION
**Pull request by NicolasDorier**
Ethereum support was added by @xpayserver .

I decided we remove it because it is unusable for several reason:

1. It use one account per invoice, but no wallet in ethereum support HD accounts, so you need to rely on a sweeper program, that isn't really available and documented.
2. Using one account per invoice means that the merchant need to do one transaction per invoice to sweep back to an exchange. At current ETH fee (>50 USD per transactions for months), it isn't economically viable. Need to use instead some smart stuff, so called "dynamic proxy " if I remember how it is called. But if we do that, better start from scratch.

If one day somebody add eth again, he can probably make his life easier by looking the code I removed in this PR.

### CODE REVIEW

**Comment by pavlenex** [comment]
Concept ACK. Looking at things this is most likely to happen with Doge and Dash in the future due to #3156. Hopefully in the long run these all become plugins that we can nuke from the main codebase. LFG

**Comment by NicolasDorier** [comment]
@pavlenex DOGE/Dash aren't that much an issue. We rely on NBitcoin for support, so removing support for it will remove at most 200 lines. But ETH code modifications are spread all around.

**Comment by woutersamaey** [comment]
The changes you are making here will likely help identify which parts would need to be refactored should we want to switch to plugins for payment methods.

**Review by dennisreimann — APPROVED** [review]
tACK

**Pull request merged**
