### PR TITLE
UI: Fix custom-select glitch

### LINKED ISSUE #1816: UX/UI - Visual bug in crowdfund creation page
**Describe the problem/bug**
A visual bug is present in the crowdfund creation screen.

**Your environment**
* Version of BTCPay Server: v1.0.5.4
* Deployment method: Lunanode
* Browser: Chrome, latest build.

**Setup Parameters**
NA

**To Reproduce**
1. Go to 'Apps'
2. Click on 'Create new app (Crowdfund)'
3. Scroll down to 'Reset goal every'
4. See the ticker and the drop-down icons that are intertwined

**Expected behavior**
Only keep the dropdown icon, as it makes sense to have it since multiple choices are offered.
Delete the validating ticker since it's usefulness is questionable ?

**Actual behavior**
Ticker and the drop-down icons are intertwined

**Screenshots/Links**
Screenshot_82
Screenshot_83

**Additional info**

This is visible in Chrome, latest build.
Checked the BTCPay Server themes, just in case: It's visible in both Default, Classic and Casa themes.

### PR DESCRIPTION
**Pull request by dennisreimann**
I could not reproduce it, as it works for me on macOS Chrome 84.0.4147.105. 

But this should potentially fix #1816 – can you verify, @Zaxounette or @Eskyee? Thanks!

### CODE REVIEW

**Comment by Eskyee** [comment]
> I could not reproduce it, as it works for me on macOS Chrome 84.0.4147.105.
> 
> But this should potentially fix #1816 – can you verify, @Zaxounette or @Eskyee? Thanks!

ok! testing dennisreimann:fix-1816 now!!

**Comment by dennisreimann** [comment]
The `CanUseTorClient` test seems to be flaky.

**Comment by Eskyee** [comment]
ok first I build dennisreimann :fix-1816 BTCPayServer v1.0.5.3 Environment: Development Build: Debug 
and I. still found the problems, as before.

as well as that RTL bug, on my local Mac. RTL docker container not starting.

Screenshot 2020-08-06 at 21 50 28

Screenshot 2020-08-06 at 21 46 47

**Comment by Eskyee** [comment]
sorry I just test old branch not dennisreimann :fix-1816 I trying now with safari and chrome 
 @dennisreimann

**Comment by dennisreimann** [comment]
🐛🔫 thanks for testing 💚👍

**Pull request merged**
