### PR TITLE
New register form

### PR DESCRIPTION
**Pull request by NicolasDorier**
Related PR about login: https://github.com/btcpayserver/btcpayserver/pull/876

After:
image

Before:
image

### CODE REVIEW

**Comment by pavlenex** [comment]
What exactly is `is administrator`?
The tickbox should be inline before `is administrator anyway`
is administrator

**Comment by NicolasDorier** [comment]
Note: The "Is administrator" only appear in tests.

**Comment by pavlenex** [comment]
Yeah was a bit worried about that. In that case tACK for this one, looks nice.

**Comment by NicolasDorier** [comment]
I inlined

image

**Pull request merged**
