### PR TITLE
Support wasabi file format input

### PR DESCRIPTION
**Pull request by Kukks**
This adds support to importing the wasabi file format which seems to be used more for imports by Wasabi,ColdCard,BlueWallet & Cobo Vault (and way better than electrum anyway)

### CODE REVIEW

**Comment by Kukks** [comment]
Tested on mainnet and seems to work  correctly btw

**Comment by NicolasDorier** [comment]
Add a test for it like I did for electrum.

**Comment by Kukks** [comment]
@NicolasDorier  done

**Comment by NicolasDorier** [comment]
awesome, need to add to changelog

**Pull request merged**
