### PR TITLE
Improve domain mapping constraint

### PR DESCRIPTION
**Pull request by dennisreimann**
- Fix potential double assignment to appId, leading to an [exception](https://pastebin.com/j8dhtcTE)
- Add port to redirect, which makes it work in dev env

### CODE REVIEW

**Comment by jaonoctus** [comment]
Looking forward to this fix.

I'm using `/btcpayserver/btcpayserver-docker`, Is there a way to help you test it @dennisreimann ?

**Review by jaonoctus — APPROVED** [review]
utACK

**Comment by 20tatiana23** [comment]
dum., 12 feb. 2023, 20:58 João Dias ***@***.***> a scris:

**Comment by NicolasDorier** [comment]
Should we make a release for this one?

**Comment by jaonoctus** [comment]
@NicolasDorier yes please

**Comment by NicolasDorier** [comment]
will do today

**Comment by NicolasDorier** [comment]
fixed in 1.7.11

**Comment by jaonoctus** [comment]
I can confirm that this PR fixed the issue.

Thank you @dennisreimann @NicolasDorier

**Pull request merged**
