### PR TITLE
Design system and icon updates for 2.0

### LINKED ISSUE #5485: Consolidate and improve iconography across app
Will fill in later.

### PR DESCRIPTION
**Pull request by dennisreimann**
WIP, will update this in an ongoing manner as we progress with 2.0 and the app.

Closes #5485.

### CODE REVIEW

**Comment by dstrukt** [comment]
iconography reference issue: https://github.com/btcpayserver/btcpayserver/issues/5485

**Comment by dstrukt** [comment]
Documenting as I work through everything. Might have more comments, will add them as I go.

Few suggestions and nits:

- [ ] rename `nav-invoice` to `nav-receipt`
- [ ] `nav-explore` could be more specific `nav-explore-plugins`?
- [ ] `nav-settings` to `nav-store-settings`

- [ ] do we really want to distinguish `nav-back` (don't remember where we use explicitly) vs. just using the `back` icon?
- [ ] same for `nav-close`?

- [ ] we don't have a invite accepted notification icon specifically
- [ ] add `caret-left` and `caret-right`

**Comment by dennisreimann** [comment]
This one is ready for now, let's try to integrate it soon. Can you give it a review, @dstrukt?

**Review by NicolasDorier — APPROVED** [review]

**Comment by NicolasDorier** [comment]
Code ACK, didn't visually checked though

**Comment by dstrukt** [comment]
Have a few last icons for you that won't change up the code, but yes - will get this reviewed/merged asap!

**Comment by dennisreimann** [comment]
Replaced more icons, e.g. on the HWW screen:

vault


Font Awesome icons are almost replaced, there are only these remainders:

- fa-sort + fa-sort-desc
- fa-sort-alpha + fa-sort-alpha-desc
- fa-spinner

**Comment by dstrukt** [comment]
Shouldn't this be the `X` not the `...`? 

Otherwise, sent the remaining icons via DM. Will get my review in here shortly!

**Comment by dennisreimann** [comment]
The dots are for the "waiting" states, like waiting for the connection or user inout. It was a "?" before, but I think the dots work better here.

**Review by dstrukt — APPROVED** [review]
tACK! Changes LGTM, assuming there will be no issues with the latest icon additions, and can always apply a patch if there's any strange errors that arise.

The only regression I've noticed is on the app side, with the invoices tab being changed to the other document looking icon, instead of the below (which is what it should be):

Screen Shot 2024-05-16 at 9 48 54 PM

**Comment by dennisreimann** [comment]
Ok, now everything is replaced and Font Awesome is removed 🎉

**Comment by dstrukt** [comment]
final tACK

this is satisfying

Screen Shot 2024-05-18 at 12 34 52 PM

**Pull request merged**
