### PR TITLE
Update docker dev env charge

### PR DESCRIPTION
**Pull request by Kukks**
There seem to be ARM images for this version of Charge

### CODE REVIEW

**Comment by pavlenex** [comment]
Still getting this one when trying to bring docker-compose up 

```
Creating btcpayservertests_lightning-charged_1   ... error

ERROR: for btcpayservertests_lightning-charged_1  Cannot start service lightning-charged: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "tiny": executable file not found in $PATH: unknown

ERROR: for lightning-charged  Cannot start service lightning-charged: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "tiny": executable file not found in $PATH: unknown
ERROR: Encountered errors while bringing up the project.
```

😭

**Comment by NicolasDorier** [comment]
Run `docker run -ti --rm shesek/lightning-charge:0.4.22-standalone-arm64v8` and let me know

**Comment by NicolasDorier** [comment]
So `docker run` directly on the arm64 image does not work. I reviewed @shesek repo and it seemed ok.

Tried to build myself, @pavlenex  can you try  `docker run -ti --rm nicolasdorier/temp`

**Comment by NicolasDorier** [comment]
@pavlenex after reviewing @shesek dockerfile, I don't see why it would not work.

Will use my hack0 to try to debug this.

**Comment by shesek** [comment]
The fix was released in Lightning Charge v0.4.23 and is up on Docker Hub.

**Comment by NicolasDorier** [comment]
fixed by 7dfce5e3061d5e0ada87ede81960f0a50d86615d

**Pull request closed without merging**
