### PR TITLE
Fix LN address store orphan fix

### LINKED ISSUE #3596: Lightning Address doesn't get deleted when deleting store
On v1.4.7.0 I noticed that deleting a store, does not delete it's coresponding Lightning Addresses. After recreating another store and trying to add the same Lightning Address, I get an error that it already exists: Though I have no mean of finding it anymore.

I guess this is a missing FK constraint with cascading delete missing. Hope it can be fixed easily. (+perhaps a migration script that deletes orphaned Lightning Address)

### PR DESCRIPTION
**Pull request by Kukks**
Fixes #3596

### CODE REVIEW

**Comment by pavlenex** [comment]
@Kukks We already have a PR for this? https://github.com/btcpayserver/btcpayserver/pull/3603

**Comment by Kukks** [comment]
> @Kukks We already have a PR for this? #3603

That's what I get for coding over the Atlantic ocean :(

**Comment by bolatovumar** [comment]
@Kukks feel free to merge whichever PR you think is more robust.

**Comment by NicolasDorier** [comment]
I don't think using plugin infrastructure for that is good idea, it's not a plugin. I would rather use the event aggregator.

**Comment by NicolasDorier** [comment]
Actually @Kukks can you remove all those hacks and instead just having a new table for LN Address with just a DELETE ON CASCADE? That way it will just work.

**Comment by NicolasDorier** [comment]
Closing in favor of https://github.com/btcpayserver/btcpayserver/pull/3638

**Pull request closed without merging**
