### PR TITLE
Wallet: Generate receive address automatically

### PR DESCRIPTION
**Pull request by dennisreimann**
This circumvents landing on a blank page with only the "generate address" button and automatically generates a new address, unless the Unreserve action was used.

This was discussed in yesterdays design meeting.

### CODE REVIEW

**Comment by dstrukt** [comment]
Nice!

Will try to get some testing in today.

**Review by dstrukt — APPROVED** [review]
tACK - Works as expected!

**Comment by NicolasDorier** [comment]
It seems a bit weird to me that you can click on "Unreserve" then have the screen without QR Code.

What about either of those?
1. Would it be better to just redirect to the transaction list with a success alert
2. Just remove the "Unreserve" feature.

I am not super sure Unreserve is really needed.

**Comment by dstrukt** [comment]
Fair.

Unless there's a reason I might not aware of, seems like option 2, removing the Unreserve feature would make the most sense?

**Comment by dennisreimann** [comment]
I'm fine with both, I just didn't want to remove it straight away and if @NicolasDorier thinks this would be fine too, we can remove it.

**Comment by dstrukt** [comment]
Will re-review the latest changes this evening.

**Review by dstrukt — APPROVED** [review]
tACK - LGTM!

**Pull request merged**
