### PR TITLE
Add support for Chia

### PR DESCRIPTION
**Pull request by greimela**
This pull request integrates support for the Chia blockchain ([chia.net](https://www.chia.net)) into BTCPayServer.

It uses polling instead of a websocket connection, since the Chia daemon websocket forces TLS 1.3, which is not yet supported on MacOS .NET.

It doesn't require a full node at the moment, but connects to the Chia SPV light wallet.

A docker fragment to run the Chia light wallet next to BTCPayServer can be found here: https://github.com/btcpayserver/btcpayserver-docker/pull/842

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Thanks for this, however, we will move the altcoins integration in plugins, which mean you will need https://github.com/btcpayserver/btcpayserver/pull/5331 in the next 1.12.0 version.

The reason why we will soon move altcoins integration to plugin is because we found out that having altcoin integration in the core source code put the burden of maintenance over our shoulder.

Most of the code you wrote should just work as is in plugins. But you need to wait next 1.12.0 version.

**Comment by greimela** [comment]
Sure, no problem, I'll take a look at #5331 to see what needs to be adapted.

**Comment by greimela** [comment]
Going to close this for now, and reopen it as a plugin after 1.12 lands.

**Comment by gentoosys** [comment]
Hi @greimela ! Thank you for your work! 
I want to test Chia payments in btcpay, and can't understand how to install it in 1.12 docker version. I tried to put Chia folder in /root/.btcpayserver/Plugins in btcpayserver's docker container, but plugin not detected. Please help me run your code

**Comment by gentoosys** [comment]
Hi. I installed your build. But can't see where to add XCH wallet. No any settings in UI...

**Comment by greimela** [comment]
Hi @gentoosys!
This build expects the Chia wallet to run next to the BTCPayServer, so you only specify the CHIA_ROOT in order to connect to it.
You can find a fragment on how to do that in my fork of btcpayserver-docker:
https://github.com/mintgarden-io/btcpayserver-docker/blob/master/docker-compose-generator/docker-fragments/chia.yml
Feel free to reach out to me via Discord (acevail) if you need more support

**Pull request closed without merging**
