### PR TITLE
Update Maintenance.cshtml

### PR DESCRIPTION
**Pull request by pavlenex**
This PR does a minor case-sensitive fix on `BTCPay server` to `BTCPay Server` and `docker` to `Docker`.

#### Before
Screenshot 2021-06-17 at 10 54 47

#### After 
Screenshot 2021-06-17 at 10 58 38

### CODE REVIEW

**Comment by pavlenex** [comment]
Also addresses the error message on the page. `BTCPayServer` to `BTCPay Server`
Screenshot 2021-06-17 at 11 01 21

**Comment by pavlenex** [comment]
Also addresses the text on the Pay Button 

Before
Screenshot 2021-06-17 at 11 13 22

After
Screenshot 2021-06-17 at 11 22 14

**Comment by pavlenex** [comment]
This had `customers` not everyone have customers.

Before

Screenshot 2021-06-17 at 11 30 47

After
Screenshot 2021-06-17 at 11 32 45

**Review by dennisreimann — APPROVED** [review]
Nice!

**Pull request merged**
