### PR TITLE
POS: Align Keypad centered vertically

### LINKED ISSUE #4682: POS Keypad view - pull elements to the center
This is on desktop on `master` https://github.com/btcpayserver/btcpayserver/commit/02e50fadaecc796fc225ef9c30341a1699dfd54a

Screenshot 2023-02-22 at 10 33 11

### PR DESCRIPTION
**Pull request by dennisreimann**
Improves the UI on Desktop and tablet. Closes #4682.

Made it so that the space for the calculation and discount/tips UI is taken if they can appear potentially. This way the UI items don't change places if something (dis)appears.

grafik

desktop

### CODE REVIEW

**Comment by dstrukt** [comment]
Will take a look here shortly!

Screenshots look great though.

**Review by dstrukt — APPROVED** [review]
LGTM!

I might explore removing the borders around the numbers as a variant to see if we like the way it looks more, still something I'm not 100% certain I love, but it's an easy enough adjustment we can explore when we get more feedback, and can easily address if/when we have to deal with the multi-step Tip functionality.

**Comment by dennisreimann** [comment]
@pavlenex Can you also give this a final check? We can then merge and include it.

**Review by pavlenex — APPROVED** [review]
tACK. Let's get it merged. 🚀

**Pull request merged**
