### PR TITLE
Crowdfund public UI re-design

### LINKED ISSUE #2783: Crowdfunding page re-design
**Describe the bug**
Unlike the rest of our pages, the crowdfunding page really needs some re-design love.

Proposed CSS improvements:

This is a portion of CSS we used during one of the crowdfunding campaigns, to make multiple visual improvements to it.

```
body {
    background: #c3e4ee;
}

/* IMAGE FIX */
div#crowdfund-body-description img {
    max-width: 100%!important;
}

/* APP CONTAINER */
#app > .row > .card.w-100.p-0.mx-0 {
    border: 4px solid #b3d3dc;
    overflow: hidden;
    border-radius: 18px;
}

/* HEADER */
div#crowdfund-header-container {
    background: white;
    padding-top: 2rem;
    padding-bottom: 2rem;
}

/* HEADER: PROGRESS */
div#crowdfund-progress-bar {
    height: 2rem;
    margin: 0 1rem;
    border-radius: 1rem!important;
    overflow: hidden;
    box-sizing: border-box;
    width: calc(100% - 2rem)!important;
    /* border: 2px solid #c3e4ee1f; */
}

    div#crowdfund-progress-bar div#crowdfund-progress-bar-confirmed-bar {
        background-color: #fba41f;
    }

/* HEADER: STATS */
.crowdfund-stats > div {
    background: transparent;
    border-right: 1px solid #f1f1f1;
    padding-top: 1rem;
    padding-bottom: 1rem;
    text-align: center;
}

    .crowdfund-stats > div > h5 {
        font-weight: 600;
        font-size: 1.6rem;
    }

    .crowdfund-stats > div > h5.text-muted {
        font-size: 1rem;
        font-weight: 600;
        font-style: italic;
        text-transform: capitalize;
        margin-bottom: 0;
    }

/* HEADER: CAP */
span#crowdfund-header-target-hardcap {
    font-size: 1.25rem;
    padding-left: 0.5rem;
}

span#crowdfund-header-target-amount {
    background: #fff1df;
    padding: 0.2rem 0.6rem;
    border-radius: 0.6rem;
    color: #5d3800;
}

/* ------  */

div#crowdfund-header-container {
    text-align: center;
    flex-direction: column;
}

span#crowdfund-header-start-date {
    display: block;
    font-style: italic;
    text-transform: lowercase;
}

#crowdfund-body-header + hr {
    height: 1px;
    margin-bottom: 2rem;
    background: #f1f1f1;
    opacity: 1;
    margin-top: 0;
}

/* HEADER: TAGLINE */
#crowdfund-body-header h2#crowdfund-body-header-tagline {
    font-size: 1.4rem;
    font-weight: normal;
    color: var(--btcpay-body-text)!important;
    text-align: center;
}

/* PERKS: HOVER */
.perks-container .perk-zoom-bg.bg-primary {
    background-color: #FFF!important;
    border-radius: 6px;
}

.perks-container .perk-zoom-text {
    font-size: 1.4rem;
    font-weight: 600!important;
    color: inherit;
    line-height: 1.6rem;
    padding: 0 1rem;
}

/* PERKS: BORDERs */

.perks-container > div:nth-of-type(1) {
    border-width: 2px;
    border-color: #54b3cf;
    background-color: #54b3cf;
}

.perks-container > div:nth-of-type(1) .card-body {
    background: white;
    border-radius: 0 0 6px 6px;
}

.perks-container > div:nth-of-type(2) {
    border-width: 2px;
    border-color: #78b8b2;
    background-color: #54b3cf;
}

.perks-container > div:nth-of-type(2) .card-body {
    background: white;
    border-radius: 0 0 6px 6px;
}

.perks-container > div:nth-of-type(3) {
    border-width: 2px;
    border-color: #8bbca3;
    background-color: #8bbca3;
}

.perks-container > div:nth-of-type(3) .card-body {
    background: white;
    border-radius: 0 0 6px 6px;
}

.perks-container > div:nth-of-type(4) {
    border-width: 2px;
    border-color: #9dbe95;
    background-color: #9dbe95;
}

.perks-container > div:nth-of-type(4) .card-body {
    background: white;
    border-radius: 0 0 6px 6px;
}

.perks-container > div:nth-of-type(5) {
    border-width: 2px;
    border-color: #b0c086;
    background-color: #b0c086;
}

.perks-container > div:nth-of-type(5) .card-body {
    background: white;
    border-radius: 0 0 6px 6px;
}

.perks-container > div:nth-of-type(6) {
    border-width: 2px;
    border-color: #213991;
    background-color: #213991;
}

.perks-container > div:nth-of-type(6) .card-body {
    background: white;
    border-radius: 0 0 6px 6px;
}

.perks-container > div:nth-of-type(7) {
    border-width: 2px;
    border-color: #c3e4ee;
    background-color: #c3e4ee;
}

.perks-container > div:nth-of-type(7) .card-body {
    background: white;
    border-radius: 0 0 6px 6px;
}

.perks-container > div:nth-of-type(8) {
    border-width: 2px;
    border-color: #e7c85a;
    background-color: #e7c85a;
}

.perks-container > div:nth-of-type(8) .card-body {
    background: white;
    border-radius: 0 0 6px 6px;
}

.perks-container > div:nth-of-type(9),
.perks-container > div:nth-of-type(10) {
    border-width: 2px;
}

#crowdfund-body-header > .row {
    flex-direction: column;
    align-items: center;
}

div#crowdfund-body-header-cta-container {
    margin: 1rem 0;
}

/* RESPONSIVE VIDEO */
.embed-responsive {
    position: relative;
    padding-bottom: 56.10%;
    height: 0;
    overflow: hidden;
}
 
.embed-responsive iframe,
.embed-responsive object,
.embed-responsive embed {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}
```

Screenshot 2021-08-18 at 00 41 17

### PR DESCRIPTION
**Pull request by dennisreimann**
Closes #2783.

While I was at it I also refactored a lot of aspects: First and foremost the non-JS/simple version and JS-enabled version got unified. This will ease maintaining and changing the UI, because we have everything in one view now.

Also incorporated the light/dark theme -- we might also want to add the the switch, I can extend it if that's wanted.

light

dark

Other changes:

- Bootstrap Vue compatibility patch for Bootstrap v5 modals
- Improved the fireworks animation

### CODE REVIEW

**Comment by dstrukt** [comment]
LGTM. 

As I mentioned in MM, I'll likely follow up with some UI improvements (padding, re-arranging, etc..) in a follow up PR or mock, but this is a huge improvement from the existing view, and the fact that it's re-factored into a unified view will make that much easier.

**Comment by pavlenex** [comment]
Concept ACK. @dennisreimann you mind if we try to tackle https://github.com/btcpayserver/btcpayserver/issues/2782 in this one as well? Seems like a minor thing?

**Comment by dennisreimann** [comment]
@pavlenex the image width constraint is in there already, I can extend it with other tags like video and iframe too. Thanks for the pointer!

**Comment by NicolasDorier** [comment]
@dennisreimann in a future PR, could you allow customization of the theme at the crowdfund level?

I think that in some case people would not expect changing btcpay theme would result into changing their crowdfund design.

We should also do the same for invoice.

**Comment by dennisreimann** [comment]
Continuing in #2927

**Pull request merged**
