### PR TITLE
Make file management UI more useful

### PR DESCRIPTION
**Pull request by Kukks**
Before

After

### CODE REVIEW

**Review by dennisreimann — APPROVED** [review]
Nice one!

**Comment by pavlenex** [comment]
Feedback we received wrt this one is:

1. If I have 100 photos, newly uploaded one is below the fold, have to know that it's on the bottom
2. When I want to add photo to POS app and copy the file, it doesn't work (absolute vs relative paths)

@Kukks any chance we can resolve these two as well?

**Comment by dennisreimann** [comment]
> When I want to add photo to POS app and copy the file, it doesn't work (absolute vs relative paths)

@NicolasDorier and I talked about this, I'll add direct file upload in the POS. No need to consider it here then.

**Comment by pavlenex** [comment]
@dennisreimann Makes sense, will log as a separate issue, should we still tackle above the fold vs below the fold item in this PR?

**Comment by Kukks** [comment]
> > When I want to add photo to POS app and copy the file, it doesn't work (absolute vs relative paths)
> 
> @NicolasDorier and I talked about this, I'll add direct file upload in the POS. No need to consider it here then.

How do you intend to do this considering the item editor is a js enhancement?

**Comment by dennisreimann** [comment]
@pavlenex good point, moved it to the top:

grafik

> How do you intend to do this considering the item editor is a js enhancement?

I'll check that and will continue that topic in #5086.

**Comment by pavlenex** [comment]
Thanks @dennisreimann this was exactly what Paralelni Polis cashier asked us to accommodate. cACK

**Pull request merged**
