### PR TITLE
update bootstrap to 4.2.1

### PR DESCRIPTION
**Pull request by Kukks**
Updated bootstrap to latest and generated the css to use btcpay's variables

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Why changing it?

**Comment by Kukks** [comment]
Bug fixes and newer utilities that I'm using for crowdfunding feature

**Comment by NicolasDorier** [comment]
I am a bit afraid to break lot's of thing by merging this.
People having custom style will not explode?

**Comment by Kukks** [comment]
There should not have been any breaking changes, just fixes and new
additions to styling utilities. Maybe @esky33 can help us test it after?

**Comment by Eskyee** [comment]
just merged Kukks bootstrap bump, I find no breaking changes, all seems ok, nothing strange found.
;) good job @Kukks ;)

**Pull request merged**
