### PR TITLE
Renamed Payment Request "Created" field to "CreatedTime" for consistancy since we already have a breaking change

### PR DESCRIPTION
**Pull request by woutersamaey**
New PR to finish what we discussed in #3221

### CODE REVIEW

**Comment by woutersamaey** [comment]
@NicolasDorier we have @Kukks blessing :+1:

**Comment by woutersamaey** [comment]
I was a bit surprised only 2 files needed changing, sure this is OK?

**Review by Kukks — CHANGES_REQUESTED** [review]
It's not ok, the build is failing. If you use Rider/VS, you can "refactor rename" which makes sure to change all usages of it

**Comment by woutersamaey** [comment]
Thanks for the advice @Kukks . Turns out it was only 1 occurrence. Let's see if the build succeeds this time.

**Review by Kukks — APPROVED** [review]

**Comment by woutersamaey** [comment]
:tada:

**Pull request merged**
