### PR TITLE
Form quick fixes

### PR DESCRIPTION
**Pull request by Kukks**

### CODE REVIEW

**Comment by Kukks** [comment]
@woutersamaey  Can you test with this PR and see if everything is ok for you?

**Comment by woutersamaey** [comment]
@Kukks The HTML escaping issue has been fixed, but the field `name` attributes still have the underscore prefix, so 50% ok.

**Comment by woutersamaey** [comment]
@Kukks maybe it's this thing? 
image

**Comment by woutersamaey** [comment]
Yep, I can confirm the underscore is added here...

**Comment by NicolasDorier** [comment]
It really close https://github.com/btcpayserver/btcpayserver/pull/4085 or you messed up with the issue number?
ACK for me as soon as @woutersamaey says it's good to go.

**Pull request merged**
