### PR TITLE
allow admin update default rate provider and default currency for stores

### LINKED ISSUE #5653: Server admin can set up default rate provider and default currency for stores on the server
From @NicolasDorier 

Server admin can set up default rate provider and default currency for stores on server

### PR DESCRIPTION
**Pull request by TChukwuleta**
resolve #5653 

Allow server admin can change currencies and providers for stores. 

Cc. @dennisreimann

### CODE REVIEW

**Comment by TChukwuleta** [comment]
this is up for review :)

**Comment by NicolasDorier** [comment]
@TChukwuleta the idea isn't to give the admin the ability to change the default of individual stores.

The idea is to give the admin the ability to change what is selected by default in the "Create Store" wizard, so that new users don't have to select their currency and the right exchange manually.

**Comment by TChukwuleta** [comment]
Oh. I see, thank you @NicolasDorier

**Comment by TChukwuleta** [comment]
Hey @NicolasDorier  I updated the policy section in server settings to give the admin the ability to update default currency, which is now used as default for create currency, and in scenarios where there is none, it selects the previous default USD (storeblob.defaultcurrency)

**Comment by NicolasDorier** [comment]
Did a minor rewording of the label.

**Pull request merged**
