### PR TITLE
Add support for removing network fee on first payment

### PR DESCRIPTION
**Pull request by NicolasDorier**

### CODE REVIEW

**Comment by NicolasDorier** [comment]
image

Ping @bitcoinshirt , is it clear enough?

**Comment by NicolasDorier** [comment]
This will interest @astupidmoose

**Comment by NicolasDorier** [comment]
There was also an issue about it somewhere

**Comment by bitcoinshirt** [comment]
@NicolasDorier Yes, the note is quite clear.

**Pull request merged**
