### PR TITLE
bump

### PR DESCRIPTION
**Pull request by dalijolijo**
NBitcoin v4.1.1.68 : https://github.com/MetacoSA/NBitcoin/blob/master/NBitcoin/NBitcoin.csproj
NBXplorer.Client v1.0.3.10 : https://github.com/dgarage/NBXplorer/blob/master/NBXplorer.Client/NBXplorer.Client.csproj
image: nicolasdorier/nbxplorer: v1.1.0.12 : https://hub.docker.com/r/nicolasdorier/nbxplorer/builds/

### CODE REVIEW

**Comment by Kukks** [comment]
The tests are failing @dalijolijo  Was there a breaking change?

**Comment by Kukks** [comment]
```
Starting test execution, please wait...
[xUnit.net 00:00:02.28]     BTCPayServer.Tests.UnitTest1.RoundupCurrenciesCorrectly [FAIL]
Failed   BTCPayServer.Tests.UnitTest1.RoundupCurrenciesCorrectly
Error Message:
 System.MissingMethodException : Method not found: 'Void NBitcoin.NetworkSetBase.RegisterDefaultCookiePath(NBitcoin.Network, System.String[])'.
Stack Trace:
   at NBitcoin.Altcoins.Bitcore.PostInit()
   at NBitcoin.NetworkSetBase.EnsureRegistered() in C:\Sources\NBitcoin\NBitcoin\NetworkSet.cs:line 89
   at NBitcoin.NetworkSetBase.GetNetwork(NetworkType networkType) in C:\Sources\NBitcoin\NBitcoin\NetworkSet.cs:line 44
   at NBXplorer.NBXplorerNetwork..ctor(INetworkSet networkSet, NetworkType networkType)
   at NBXplorer.NBXplorerNetworkProvider.InitBitcore(NetworkType networkType)
   at NBXplorer.NBXplorerNetworkProvider..ctor(NetworkType networkType)
   at BTCPayServer.BTCPayNetworkProvider..ctor(NetworkType networkType) in /home/circleci/project/BTCPayServer/BTCPayNetworkProvider.cs:line 46
   at BTCPayServer.Services.Rates.CurrencyNameTable.LoadCurrency() in /home/circleci/project/BTCPayServer/Services/Rates/CurrencyNameTable.cs:line 170
   at BTCPayServer.Services.Rates.CurrencyNameTable..ctor() in /home/circleci/project/BTCPayServer/Services/Rates/CurrencyNameTable.cs:line 40
   at BTCPayServer.Tests.UnitTest1.RoundupCurrenciesCorrectly() in /home/circleci/project/BTCPayServer.Tests/UnitTest1.cs:line 347
[xUnit.net 00:00:07.67]     BTCPayServer.Tests.UnitTest1.CanParseCurrencyValue [FAIL]
Failed   BTCPayServer.Tests.UnitTest1.CanParseCurrencyValue
Error Message:
 System.TypeInitializationException : The type initializer for 'BTCPayServer.CurrencyValue' threw an exception.
---- System.MissingMethodException : Method not found: 'Void NBitcoin.NetworkSetBase.RegisterDefaultCookiePath(NBitcoin.Network, System.String[])'.
Stack Trace:
   at BTCPayServer.CurrencyValue.TryParse(String str, CurrencyValue& value) in /home/circleci/project/BTCPayServer/CurrencyValue.cs:line 18
   at BTCPayServer.Tests.UnitTest1.CanParseCurrencyValue() in /home/circleci/project/BTCPayServer.Tests/UnitTest1.cs:line 1269
----- Inner Stack Trace -----
   at NBitcoin.Altcoins.Dogecoin.PostInit()
   at NBitcoin.NetworkSetBase.EnsureRegistered() in C:\Sources\NBitcoin\NBitcoin\NetworkSet.cs:line 89
   at NBitcoin.NetworkSetBase.GetNetwork(NetworkType networkType) in C:\Sources\NBitcoin\NBitcoin\NetworkSet.cs:line 44
   at NBXplorer.NBXplorerNetwork..ctor(INetworkSet networkSet, NetworkType networkType)
   at NBXplorer.NBXplorerNetworkProvider.InitDogecoin(NetworkType networkType)
   at NBXplorer.NBXplorerNetworkProvider..ctor(NetworkType networkType)
   at BTCPayServer.BTCPayNetworkProvider..ctor(NetworkType networkType) in /home/circleci/project/BTCPayServer/BTCPayNetworkProvider.cs:line 46
   at BTCPayServer.Services.Rates.CurrencyNameTable.LoadCurrency() in /home/circleci/project/BTCPayServer/Services/Rates/CurrencyNameTable.cs:line 170
   at BTCPayServer.Services.Rates.CurrencyNameTable..ctor() in /home/circleci/project/BTCPayServer/Services/Rates/CurrencyNameTable.cs:line 40
   at BTCPayServer.CurrencyValue..cctor() in /home/circleci/project/BTCPayServer/CurrencyValue.cs:line 14
```

**Comment by dalijolijo** [comment]
@Kukks I am adding NBXplorer.Client [v1.0.3.10](https://github.com/dgarage/NBXplorer/blob/master/NBXplorer.Client/NBXplorer.Client.csproj)

**Comment by NicolasDorier** [comment]
oh that's bad wat.

**Comment by NicolasDorier** [comment]
ah yeah, missing a lib

**Comment by NicolasDorier** [comment]
please update the testframework as well.

**Comment by dalijolijo** [comment]
In which file?

**Comment by NicolasDorier** [comment]
tests csproj

**Comment by NicolasDorier** [comment]
actually there is none, sorry

**Pull request merged**
