### PR TITLE
allow facade lock in for access token creation 

### LINKED ISSUE #692: Pairing Link that Locks in Merchant Facade
In apps that pair to BTCPay, right now we can give the user the link `<host>/api-tokens` and it conveniently takes them right to pairing. However many users get confused by the `facade` drop-down. 

It's a minor thing, but it would be cool to have it so a different sub-URI,  (maybe `<host>/merchant-api-tokens`) would take them to a different version of the pairing page where they are probibited from selecting a facade and `merchant` is just assumed. One less thing for them to screw up.

### PR DESCRIPTION
**Pull request by Kukks**
closes #692

### CODE REVIEW

**Comment by NicolasDorier** [comment]
the facade feature is not used at all. Better to remove all trace of it in btcpay.

**Comment by Kukks** [comment]
Maybe we can merge this one in anyway @NicolasDorier until we sort out the other PR( which may take a while since it is a bit big)

**Comment by NicolasDorier** [comment]
you want me to bulldoze the thing?

**Comment by Kukks** [comment]
https://giphy.com/gifs/just-do-it-24xRxrDCLxhT2

**Comment by NicolasDorier** [comment]
4067d4b00f0e2cffedffa06600f791d8efaed974

**Pull request closed without merging**
