### PR TITLE
Slugify URLs

### PR DESCRIPTION
**Pull request by bolatovumar**
address #921

### CODE REVIEW

**Comment by NicolasDorier** [comment]
The tests do not pass, it must break something

**Comment by Kukks** [comment]
Do all the links still work without the slug version?

**Comment by bolatovumar** [comment]
@NicolasDorier yeah, it's because some tests try to hit the old non-slugified urls.

@Kukks no, old non-slugified URLs do not work which might be a problem.

**Comment by NicolasDorier** [comment]
I think it is also easier to directly edit the Route attributes.

**Comment by bolatovumar** [comment]
Cool, I will just add the attributes then.

**Comment by bolatovumar** [comment]
Added attribute routes for  `Account` and `Manage` controllers. Can do other controllers if this change looks good to you @NicolasDorier @Kukks.

**Comment by NicolasDorier** [comment]
Sorry for looking at it only now, tests fail.

**Comment by bolatovumar** [comment]
@NicolasDorier sorry, was busy lately. Will fix this up soon.

**Comment by bolatovumar** [comment]
I really don't understand why the remaining tests are failing so I give up now.

**Pull request closed without merging**
