### PR TITLE
Change obsolete fields in IPN fixes #5361

### LINKED ISSUE #5361: [Bug]: BTCPayServer.HostedServices.BitpayIPNSender fail to send notifications
### What is your BTCPay version?

BTCPay Server v1.11.5 

### How did you deploy BTCPay Server?

Environment: Development (Debug) Win10 x64 French (fr-FR)

### What happened?

BTCPay fail to send notifications...

### How did you encounter this bug?

working on a new plugin...
the fast way to reproduce is using the pay button: 
- set any URL as Server IPN 
- set the currency to BTC
- set an amount in decimals eg; 0.58
- click the preview button to create the invoice
- do something to trigger the notification sending... pay it or mark it invalid...
- take a look in the console.

### Relevant log output

```shell
in v1.11.4
fail: Events:         Error while calling event async handler
System.FormatException: Impossible to parse the string in a bitcoin amount
   at NBitcoin.Money.Parse(String bitcoin)
   at NBitcoin.Money.op_Implicit(String value)
   at BTCPayServer.HostedServices.BitpayIPNSender.Notify(InvoiceEntity invoice, InvoiceEvent invoiceEvent, Boolean extendedNotification, Boolean sendMail) in D:\btcpayserver-1.11.4\BTCPayServer\HostedServices\BitpayIPNSender.cs:line 117
   at BTCPayServer.HostedServices.BitpayIPNSender.<StartAsync>b__19_0(InvoiceEvent e) in D:\btcpayserver-1.11.4\BTCPayServer\HostedServices\BitpayIPNSender.cs:line 271
   at BTCPayServer.EventAggregator.ChannelSubscription`1.Listen() in D:\btcpayserver-1.11.4\BTCPayServer\EventAggregator.cs:line 167

in v1.11.5
fail: Events:         Error while calling event async handler
System.FormatException: Impossible to parse the string in a bitcoin amount
   at NBitcoin.Money.Parse(String bitcoin)
   at NBitcoin.Money.op_Implicit(String value)
   at BTCPayServer.HostedServices.BitpayIPNSender.Notify(InvoiceEntity invoice, InvoiceEvent invoiceEvent, Boolean extendedNotification, Boolean sendMail) in D:\btcpayserver-1.11.5\BTCPayServer\HostedServices\BitpayIPNSender.cs:line 117
   at BTCPayServer.HostedServices.BitpayIPNSender.<StartAsync>b__19_0(InvoiceEvent e) in D:\btcpayserver-1.11.5\BTCPayServer\HostedServices\BitpayIPNSender.cs:line 271
   at BTCPayServer.EventAggregator.ChannelSubscription`1.Listen() in D:\btcpayserver-1.11.5\BTCPayServer\EventAggregator.cs:line 167
```

### What browser do you use?

_No response_

### Additional information

Impossible to parse the string in a bitcoin amount because the amounts are with a "," not a "."...
i fixed this by adding CultureInfo.InvariantCulture to the .ToString() in btcpayserver-1.11.5\BTCPayServer\Services\Invoices\InvoiceEntity.cs Lines 596 to 603:
<pre>
cryptoInfo.Price = subtotalPrice.ToString(CultureInfo.InvariantCulture);
cryptoInfo.Due = accounting.Due.ToString(CultureInfo.InvariantCulture);
cryptoInfo.Paid = accounting.Paid.ToString(CultureInfo.InvariantCulture);
cryptoInfo.TotalDue = accounting.TotalDue.ToString(CultureInfo.InvariantCulture);
cryptoInfo.NetworkFee = accounting.NetworkFee.ToString(CultureInfo.InvariantCulture);
cryptoInfo.CryptoPaid = accounting.CryptoPaid.ToString(CultureInfo.InvariantCulture);
</pre>

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

### PR DESCRIPTION
**Pull request by Kukks**

### CODE REVIEW

**Comment by ndeet** [comment]
I still see those errors in the build log when running locally:
```
fail: Events:         Error while calling event async handler
System.FormatException: Impossible to parse the string in a bitcoin amount
   at NBitcoin.Money.Parse(String bitcoin)
   at NBitcoin.Money.op_Implicit(String value)
   at BTCPayServer.HostedServices.BitpayIPNSender.Notify(InvoiceEntity invoice, InvoiceEvent invoiceEvent, Boolean extendedNotification, Boolean sendMail) in /home/ndeet/RiderProjects/btcpayserver/BTCPayServer/HostedServices/BitpayIPNSender.cs:line 116
   at BTCPayServer.HostedServices.BitpayIPNSender.<StartAsync>b__19_0(InvoiceEvent e) in /home/ndeet/RiderProjects/btcpayserver/BTCPayServer/HostedServices/BitpayIPNSender.cs:line 269
   at BTCPayServer.EventAggregator.ChannelSubscription`1.Listen() in /home/ndeet/RiderProjects/btcpayserver/BTCPayServer/EventAggregator.cs:line 167
fail: Events:         Error while calling event async handler
System.FormatException: Impossible to parse the string in a bitcoin amount
   at NBitcoin.Money.Parse(String bitcoin)
   at NBitcoin.Money.op_Implicit(String value)
   at BTCPayServer.HostedServices.BitpayIPNSender.Notify(InvoiceEntity invoice, InvoiceEvent invoiceEvent, Boolean extendedNotification, Boolean sendMail) in /home/ndeet/RiderProjects/btcpayserver/BTCPayServer/HostedServices/BitpayIPNSender.cs:line 116
   at BTCPayServer.HostedServices.BitpayIPNSender.<StartAsync>b__19_0(InvoiceEvent e) in /home/ndeet/RiderProjects/btcpayserver/BTCPayServer/HostedServices/BitpayIPNSender.cs:line 276
   at BTCPayServer.EventAggregator.ChannelSubscription`1.Listen() in /home/ndeet/RiderProjects/btcpayserver/BTCPayServer/EventAggregator.cs:line 167
fail: Events:         Error while calling event async handler
System.FormatException: Impossible to parse the string in a bitcoin amount
   at NBitcoin.Money.Parse(String bitcoin)
   at NBitcoin.Money.op_Implicit(String value)
   at BTCPayServer.HostedServices.BitpayIPNSender.Notify(InvoiceEntity invoice, InvoiceEvent invoiceEvent, Boolean extendedNotification, Boolean sendMail) in /home/ndeet/RiderProjects/btcpayserver/BTCPayServer/HostedServices/BitpayIPNSender.cs:line 116
   at BTCPayServer.HostedServices.BitpayIPNSender.<StartAsync>b__19_0(InvoiceEvent e) in /home/ndeet/RiderProjects/btcpayserver/BTCPayServer/HostedServices/BitpayIPNSender.cs:line 269
   at BTCPayServer.EventAggregator.ChannelSubscription`1.Listen() in /home/ndeet/RiderProjects/btcpayserver/BTCPayServer/EventAggregator.cs:line 167
```

It looks like a parse error but then also that mail notification error. I assume they are unrelated and the parse error should not happen even if the mail fails.

**Comment by Kukks** [comment]
weird i dont get it but i tested after my change 🤔

**Comment by ndeet** [comment]
Double checked to be on the correct commit and I see the code change in the BitpayIPNSender.cs file. Could it be that only the `notification.Data.BTCDue = btcCryptoInfo.Due;` property is missing/null (Line 116) under certain circumstances?

**Comment by ndeet** [comment]
the ipn fires after payment and after confs, so due amount will be 0 or missing in that case?

**Comment by ndeet** [comment]
Ran the debugger, the lines above with btcCryptoInfo.Rate does not fail because it is a decimal but the other amounts are all strings, so maybe there is no automatic casting to decimal happening or needs to be done manually? I have no clue about C# though, so could be wrong :P

**Comment by dennisreimann** [comment]
While testing I also added an invoice via the POS and now I also see them, so that's likely related to the POS data, I guess — this is happening on maste though, so not related to this PR:

```
fail: Events:         Error while calling event async handler
System.FormatException: Impossible to parse the string in a bitcoin amount
   at NBitcoin.Money.Parse(String bitcoin)
   at NBitcoin.Money.op_Implicit(String value)
   at BTCPayServer.HostedServices.BitpayIPNSender.Notify(InvoiceEntity invoice, InvoiceEvent invoiceEvent, Boolean extendedNotification, Boolean sendMail) in /home/d11n/Sources/btcpay/server/BTCPayServer/HostedServices/BitpayIPNSender.cs:line 117
   at BTCPayServer.HostedServices.BitpayIPNSender.<StartAsync>b__19_0(InvoiceEvent e) in /home/d11n/Sources/btcpay/server/BTCPayServer/HostedServices/BitpayIPNSender.cs:line 284
   at BTCPayServer.EventAggregator.ChannelSubscription`1.Listen() in /home/d11n/Sources/btcpay/server/BTCPayServer/EventAggregator.cs:line 167
```

**Comment by NicolasDorier** [comment]
This fix doesn't work because those I think those properties are actually equivalent.

**Comment by NicolasDorier** [comment]
Fixed it on https://github.com/btcpayserver/btcpayserver/commit/ec076d1560ce9af09186d5feb89d2dbfb19aa13b @AdilElFarissi  already found the proper fix in the issue.

**Comment by ndeet** [comment]
Mentioned fix works now :+1:

**Pull request closed without merging**
