### PR TITLE
Re-add S3 and Google storage options and bump libs

### PR DESCRIPTION
**Pull request by Kukks**

### CODE REVIEW

**Comment by dennisreimann** [comment]
lgtm. why were they removed?

**Comment by NicolasDorier** [comment]
Nobody is missing it, and this isn't well tested. I think we shouldn't integrate to providers.

**Review by fernandohre — APPROVED** [review]

**Comment by Kukks** [comment]
@NicolasDorier How about we only bump the libs then?

**Comment by NicolasDorier** [comment]
I think we should go the plugin route indeed @bolatovumar

**Pull request closed without merging**
