### PR TITLE
Minor readme cleanup + license clarification

### PR DESCRIPTION
**Pull request by pavlenex**
This PR provides a very tiny cleanup of the readme.md and adds a single paragraph that hopefully clarifies license (especially logos and graphics).

### CODE REVIEW

**Comment by Kukks** [comment]
the branch you based this off is super old

**Comment by pavlenex** [comment]
I don't think that should matter since the readme file is intact since then?

**Comment by Kukks** [comment]
> 
> 
> I don't think that should matter since the readme file is intact since then?
Just makes the tests fail :)

**Comment by pavlenex** [comment]
Ah okay, lemme do a new PR, saw a thing or two that I'd like to fix anyways.

**Comment by Kukks** [comment]
nah its fine

**Pull request merged**
