### PR TITLE
Tame flaky Selenium tests

### PR DESCRIPTION
**Pull request by dennisreimann**

### CODE REVIEW

**Comment by Kukks** [comment]
Tried in #2158 but got 
```
[xUnit.net 00:01:35.75]         02/17/2021 14:08:06 +00:00 :Tests:   BTCPayTester disposed
  X CanUseCoinSelection [4s 563ms]
  Error Message:
   OpenQA.Selenium.ElementClickInterceptedException : element click intercepted: Element <button type="submit" class="btn btn-primary" id="...">Continue</button> is not clickable at point (372, 544). Other element would receive the click: <p class="text-muted pt-2">...</p>
  (Session info: headless chrome=88.0.4324.146)
  Stack Trace:
     at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.Click()
   at BTCPayServer.Tests.SeleniumTester.GenerateWallet(String cryptoCode, String seed, Boolean importkeys, Boolean privkeys, ScriptPubKeyType format) in /source/BTCPayServer.Tests/SeleniumTester.cs:line 161
   at BTCPayServer.Tests.ChromeTests.CanUseCoinSelection() in /source/BTCPayServer.Tests/SeleniumTests.cs:line 554
--- End of stack trace from previous location where exception was thrown ---
  Standard Output Messages:
```

**Comment by dennisreimann** [comment]
Yikes, that's exactly the problem the `Thread.Sleep(250)` is supposed to solve. Selenium seems to have issues with the opening an closing animation not being done and hence not being able to click the button (maybe while it moves). 
I got one more idea, let me poke around some more …

**Comment by dennisreimann** [comment]
This time it's the `CanUseTorClient` integration test failing – so I'd beg for you to give this another chance @Kukks :D

**Review by Kukks — APPROVED** [review]
seems to work now across other PRs that I tested this with too!

**Pull request merged**
