### PR TITLE
2195 Invoice metadata now saves correctly

### PR DESCRIPTION
**Pull request by saliehendricks**
#2195 Fixes metadata not saving due to 2 separate db contexts being used.

Calling invoice PUT api call:
/api/v1/stores/{storeid}/invoices/{invoiceid}
{
    "Metadata": {
        "PosData": 333
    }
}

Should result in the UI updating immediately:
image

Should also show the result in the API GET call:
/api/v1/stores/{storeid}/invoices/{invoiceid}
(this looked like it was working simply due to the fact that the model was updated and returned to the API caller)

### CODE REVIEW

**Review by Kukks — APPROVED** [review]
LGTM, great job!

**Comment by NicolasDorier** [comment]
There was no test on that? shit

**Comment by Kukks** [comment]
> There was no test on that? shit

There was but the test needed additional checks

**Comment by saliehendricks** [comment]
The test is and was likely passing because the controller just passes back the metadata object that was sent in. There was no integration test that checks the crud on update invoice that I can see.

**Comment by NicolasDorier** [comment]
`Assert.True(a == a)`

**Pull request merged**
