### PR TITLE
Fix format on expired invoice DON'T MERGE

### PR DESCRIPTION
**Pull request by britttttk**
\n was showing up in expired invoice. This change hides it but I couldn't get a newline to work so maybe it could just be removed.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
you need to fix it in transiflex, I generate those file automatically now.

**Comment by britttttk** [comment]
I uploaded the en.json file in this PR to Transifex for the new source file because Transifex recognizes /n and creates a symbol for it, for translator readability. It also brings your comment into the files.

**Comment by britttttk** [comment]
I broke them only on Transifex right? A modified string in the source file will become an untranslated string in the translations. There is a history tab in the translation editor to bring them back easily.

**Comment by britttttk** [comment]
If it's \n in Transifex in the source code, I don't understand how it becomes \\n from their translation. I think the user just copies the symbol. When I download the translated file for use it's still \n. Neither create a newline in the invoice so does the utility help this or only just converting it for fr and en.

**Comment by NicolasDorier** [comment]
I mean right now if I run my scripts, all the translations for `InvoiceExpired_Body_1 ` are screwed, so can you revert what you did on transifex?

**Comment by NicolasDorier** [comment]
I run the test `PullTransifexTranslations` to pull translation from transifex and update BTCPay project.

**Pull request closed without merging**
