### PR TITLE
Fix LNURL-Withdraw payments

### LINKED ISSUE #4663: [Bug]: POS fails with NFC & LNURLw payment
### What is your BTCPay version?

BTCPay Server v1.7.12+9344113ae

### How did you deploy BTCPay Server?

lunanode

### What happened?

error message shown when payment is attempted
```
Could not fetch bolt11 invoice to pay to:
Amount is out of bounds.
```

### How did you encounter this bug?

Using the POS app on an Android phone as a PWA

- Set up a charge for 10 sats
- Clicked `pay by NFC & LNURLW`
- Tapped a card to make payment

message was displayed and payment was not made

### Relevant log output

_No response_

### What browser do you use?

_No response_

### Additional information

_No response_

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

### PR DESCRIPTION
**Pull request by dennisreimann**
Fixes:
- Missing request data when called directly via `_uilnurlController.GetLNURLForInvoice`
- Comparisons of `long` and `LightMoney`, which did not work, because the `amount` provided was in sats and Lightmoney compares to millisats.

Closes #4663.

### CODE REVIEW

**Review by Kukks — APPROVED** [review]
Utack

**Comment by NicolasDorier** [comment]
A test is failing

**Comment by dennisreimann** [comment]
Yes, must be because I left out something from my working copy. I can take a look. 

Can we merge #4671 first? What I did here was based on that.

**Comment by NicolasDorier** [comment]
done

**Pull request merged**
