### PR TITLE
Fix monero sync height check

### PR DESCRIPTION
**Pull request by Kukks**
based on issue at https://github.com/monero-project/monero/issues/7029

### CODE REVIEW

**Comment by Eskyee** [comment]
BTCPAY devs wasting time on fixing shitcoins 😂 get me out of here... oooh yeahhhh I forgot they were paid

**Comment by Kukks** [comment]
> BTCPAY devs wasting time on fixing shitcoins 😂 get me out of here... oooh yeahhhh I forgot they were paid
@Eskyee Stupid, rude and unproductive comment. 
I do what I want with my own time. I definitely spend the biggest majority (beyond a standard full-time job amount too) of my time on non-altcoin code.

**Comment by Eskyee** [comment]
Yeaaah whatever... the code looks pretty.. your still fixing bugs 😂

**Comment by Eskyee** [comment]
The Production is Bitcoin.. simple not a shitcoin factory

**Pull request merged**
