### PR TITLE
Implementing indicator that shows total line row can be expanded

### PR DESCRIPTION
**Pull request by lepipele**
References:
https://github.com/btcpayserver/btcpayserver/issues/19#issuecomment-354586029
https://forkbitpay.slack.com/archives/C7M093Z55/p1514743072000005

### CODE REVIEW

**Comment by NicolasDorier** [comment]
it seems the arrow show only when I point the mouse on the header.

**Comment by lepipele** [comment]
@NicolasDorier yeah I didn't want to change look too much because I loved how clean it is. Rather just give indication that row can be expanded. 

Give it a try for a day/two... if it doesn't stick all we need to do is remove `:hover` from CSS and arrow will be always visible.

**Comment by NicolasDorier** [comment]
Another alternative if you like the clean look is to play on the opacity of the arrow (if possible) where by default it is super light, and when over more dark?

**Comment by lepipele** [comment]
@NicolasDorier https://github.com/lepipele/btcpayserver/commit/ee3144f34a37d0adf8c9d99a27a8116a9914b9ef

**Pull request merged**
