### PR TITLE
Dashboard balance fixes

### PR DESCRIPTION
**Pull request by dennisreimann**
Some more edge case fixes.

### CODE REVIEW

**Comment by gruve-p** [comment]
Just tested this PR but I get a different error now:

FireFox:
image

Edge browser:
image

**Comment by dennisreimann** [comment]
@gruve-p Thanks again for reporting that. You must be using the old NBXplorer backend then, please consider migrating to the new version. See these docs for context:

- https://github.com/dgarage/NBXplorer/blob/master/docs/Postgres-Migration.md
- https://blog.btcpayserver.org/nbxplorer-postgres/

I've updated the dashboard tile to at least show the balance in that case.

grafik

**Comment by gruve-p** [comment]
Just tested the updated PR. It now looks like this:
image

The weird thing is that I already migrated from DBTrie to the new Postgres backend 2 months ago (using the `--automigrate` flag)

NBXPlorer debug log:

```
info: Configuration:  Data Directory: /root/.nbxplorer/Main
info: Configuration:  Configuration File: /root/.nbxplorer/Main/settings.config
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: GRS
info: Configuration:  DBCache: 50 MB
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: GRS
info: Configuration:  DBCache: 50 MB
info: NBXplorer.DatabaseSetup: Postgres services activated
Hosting environment: Production
Content root path: /root/NBXplorer/NBXplorer/bin/Release/net6.0/
Now listening on: http://127.0.0.1:24444
Application started. Press Ctrl+C to shut down.
info: NBXplorer.Indexer.GRS: TCP Connection succeed, handshaking...
info: NBXplorer.Indexer.GRS: Handshaked
info: NBXplorer.Indexer.GRS: Testing RPC connection to http://localhost:1441/
info: NBXplorer.Indexer.GRS: RPC connection successful
info: NBXplorer.Indexer.GRS: Full node version detected: 230000
info: NBXplorer.Indexer.GRS: NBXplorer is correctly whitelisted by the node
info: NBXplorer.Events: GRS: Node state changed: NotStarted => NBXplorerSynching
info: NBXplorer.Events: GRS: Node state changed: NBXplorerSynching => Ready
```

BTCPayserver debug log:

```
Warning NETSDK1174: The abbreviation of -p for --project is deprecated. Please use --project.
info: Configuration:  Data Directory: /root/.grspayserver/Main
info: Configuration:  Configuration File: /root/.btcpayserver/Main/settings.config
info: BTCPayServer.Plugins.PluginManager: Loading plugins from /root/.btcpayserver/Plugins
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer - 1.5.4.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Shopify - 1.5.4.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.PayButton - 1.5.4.0
info: Configuration:  Supported chains: GRS
info: Configuration:  GRS: Explorer url is http://127.0.0.1:24444/
info: Configuration:  GRS: Cookie file is /root/.nbxplorer/Main/.cookie
info: Configuration:  Network: Mainnet
info: Configuration:  Root Path: /
info: PayServer:      Starting listening NBXplorer (GRS)
info: PayServer:      Start watching invoices
warn: PayServer:      Warning: Error while trying to load rates from cache
System.FormatException: Invalid currency pair
   at BTCPayServer.Rating.CurrencyPair.Parse(String str) in /root/btcpayserver/BTCPayServer.Rating/CurrencyPair.cs:line 21
   at BTCPayServer.Services.Rates.BackgroundFetcherRateJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /root/btcpayserver/BTCPayServer.Rating/Providers/BackgroundFetcherRateProvider.cs:line 40
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at BTCPayServer.Services.SettingsRepository.Deserialize[T](String value) in /root/btcpayserver/BTCPayServer/Services/SettingsRepository.cs:line 72
   at BTCPayServer.Services.SettingsRepository.<>c__DisplayClass4_0`1.<<GetSettingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at BTCPayServer.Services.SettingsRepository.<>c__DisplayClass4_0`1.<<GetSettingAsync>b__0>d.MoveNext() in /root/btcpayserver/BTCPayServer/Services/SettingsRepository.cs:line 33
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at BTCPayServer.Services.SettingsRepository.GetSettingAsync[T](String name) in /root/btcpayserver/BTCPayServer/Services/SettingsRepository.cs:line 29
   at BTCPayServer.HostedServices.RatesHostedService.TryLoadRateCache() in /root/btcpayserver/BTCPayServer/HostedServices/RatesHostedService.cs:line 118
info: PayServer:      Starting payment request expiration watcher
info: PayServer:      2 pending payment requests being checked since last run
info: Configuration:  Now listening on: http://127.0.0.1:23000
info: PayServer:      GRS: Checking if any pending invoice got paid while offline...
info: PayServer:      GRS: 0 payments happened while offline
info: PayServer:      Connected to WebSocket of NBXplorer (GRS)
```

**Comment by dennisreimann** [comment]
Hmm, that NBXplorer line should read `Configuration:  Connection to NBXplorer's database successful, dashboard and reporting features activated.`

@NicolasDorier any idea?

**Comment by dennisreimann** [comment]
@Nicolas that's the first of the links I posted above. It's in the NBXplorer docs.

**Comment by gruve-p** [comment]
@NicolasDorier 

I was indeed using 2 seperate postgres connection strings for nbxplorer and btcpayserver. I have changed it now to use the same connection string but the problem remains.

NBXplorer testnet start command:
`./run.sh --testnet --chains=grs --grsrpcuser redacted --grsrpcpassword redacted --postgres="UserID=btcpay;Password=redacted;Host=localhost;Port=5432;Database=btcpay" `

NBXplorer log:
```
info: Configuration:  Data Directory: /root/.nbxplorer/TestNet
info: Configuration:  Configuration File: /root/.nbxplorer/TestNet/settings.config
info: Configuration:  Network: Testnet
info: Configuration:  Supported chains: GRS
info: Configuration:  DBCache: 50 MB
info: Configuration:  Network: Testnet
info: Configuration:  Supported chains: GRS
info: Configuration:  DBCache: 50 MB
info: NBXplorer.DatabaseSetup: Postgres services activated
Hosting environment: Production
Content root path: /root/NBXplorer/NBXplorer/bin/Release/net6.0/
Now listening on: http://127.0.0.1:24445
Application started. Press Ctrl+C to shut down.
info: NBXplorer.Indexer.GRS: TCP Connection succeed, handshaking...
info: NBXplorer.Indexer.GRS: Handshaked
info: NBXplorer.Indexer.GRS: Testing RPC connection to http://localhost:17766/
info: NBXplorer.Indexer.GRS: RPC connection successful
info: NBXplorer.Indexer.GRS: Full node version detected: 230000
info: NBXplorer.Indexer.GRS: NBXplorer is correctly whitelisted by the node
info: NBXplorer.Events: GRS: Node state changed: NotStarted => NBXplorerSynching
info: NBXplorer.Events: GRS: Node state changed: NBXplorerSynching => Ready
```

btcpayserver start command:
`./run.sh --postgres="UserID=btcpay;Password=redacted;Host=localhost;Port=5432;Database=btcpay" --testnet --chains=grs --grslightning="type=clightning;server=unix://root/.lightning/testnet/lightning-rpc" --grsexternalspark="server=https://testnet.grspay.com/spark/grs/;cookiefile=/root/groestlcoin-spark/config" --grsexternalcharge="server=https://testnet.grspay.com/groestlcoin-lightning-charge/grs/;cookiefilepath=/root/groestlcoin-lightning-charge/config"`

btcpayserver log:
```
info: Configuration:  Data Directory: /root/.btcpayserver/TestNet
info: Configuration:  Configuration File: /root/.btcpayserver/TestNet/settings.config
info: Configuration:  Creating configuration file
info: BTCPayServer.Plugins.PluginManager: Loading plugins from /root/.btcpayserver/Plugins
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer - 1.5.4.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Shopify - 1.5.4.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.PayButton - 1.5.4.0
info: Configuration:  Supported chains: GRS
info: Configuration:  GRS: Explorer url is http://127.0.0.1:24445/
info: Configuration:  GRS: Cookie file is /root/.nbxplorer/TestNet/.cookie
info: Configuration:  Network: Testnet
info: Configuration:  Root Path: /
info: PayServer:      Starting listening NBXplorer (GRS)
info: PayServer:      Start watching invoices
info: PayServer:      Starting payment request expiration watcher
info: PayServer:      0 pending payment requests being checked since last run
info: Configuration:  Now listening on: http://127.0.0.1:23001
info: PayServer:      GRS: Checking if any pending invoice got paid while offline...
info: PayServer:      GRS: 0 payments happened while offline
info: PayServer:      Connected to WebSocket of NBXplorer (GRS)
```

**Comment by gruve-p** [comment]
> @gruve-p you need to set `BTCPAY_EXPLORERPOSTGRES` to the same connection string as nbxplorer. 

Thank you! This was the solution!
Chart working now:

image

**Comment by gruve-p** [comment]
ACK https://github.com/btcpayserver/btcpayserver/pull/3876/commits/9a3518529586bc6915f80d86383e8a3d87272e84

**Comment by gruve-p** [comment]
> @NicolasDorier Ok, I added the explanation in [dgarage/NBXplorer#366](https://github.com/dgarage/NBXplorer/pull/366). I think this one is ready to get merged then.

I dont think thats the right place to explain it. It should made more clear on: https://github.com/btcpayserver/btcpayserver-doc/blob/master/docs/Deployment/ManualDeploymentExtended.md as thats what I personally use

**Comment by dennisreimann** [comment]
I think we should link to the migration docs on that page and while we are at it, we can leave that sentence there too.

**Comment by dennisreimann** [comment]
Updated the docs in btcpayserver/btcpayserver-doc@22d6322d8a0c540ad9f79c212f675c725eb4b87c

**Pull request merged**
