### PR TITLE
Specify PayJoin enabled in Payment Link heading

### PR DESCRIPTION
**Pull request by orangesurf**
I wish to make a suggestion to the way the "Payment link" heading is displayed in checkout.

Currently it shows "Payment link" even if PayJoin is enabled.

There is an icon and information on hover but I missed these, I think altering the heading would make it even more obvious.

### CODE REVIEW

**Comment by dstrukt** [comment]
Do you mind posting screenshots?

I can follow along in the code, but I'm curious to see how it looks in context, thanks!

**Comment by pavlenex** [comment]
@3609 
Screenshot 2022-04-08 at 12 08 57

Screenshot 2022-04-08 at 12 08 52

I think for now it's good to emphasize PayJoin. I however think once we do #3567 we really have to think how much of these complexities a user should know about and how much should be handled automatically by their wallet. We just have way too much information that a regular person paying in bitcoin doesn't know about and we should try to abstract those.

So for now I think this is okay, but in bigger perspective, we should really try to thinker about abstracting the complexities. I even think `payment link` itself is very confusing for a user.

**Comment by dstrukt** [comment]
Agree @pavlenex, and thanks for the screenshots.

**Comment by orangesurf** [comment]
Thanks for doing the screenshots @pavlenex. By "So for now I think this is okay," do you mean how it is currently or how the pull request is?

**Pull request merged**
