### PR TITLE
Fix MySQL support

### PR DESCRIPTION
**Pull request by NicolasDorier**
Should fix https://github.com/btcpayserver/btcpayserver/issues/1224

@ketominer I integrated https://github.com/btcpayserver/btcpayserver/pull/703 in this PR.
However, I think you had some other columns with the problem, can you remind me which?

Please test this PR, did not tested it.

### CODE REVIEW

**Comment by rockstardev** [comment]
DMed @ketominer... will update when he gets time to test.

**Comment by NicolasDorier** [comment]
I will merge that for now. It is blocking the update to .net core 3.1.

I think it is not complete and some columns also need to be sized correctly.

**Comment by ketominer** [comment]
Hi, after messing around with column sizes and the recent change in the ORM that now forces utf8mb4 and makes migrations fail, here is a schema that seems to work for master. I've also made a migration script to convert from latin1 to utf8mb4 for nodl users and change column sizes so keys doesn't exceed 3072 bytes (the critical place was CREATE TABLE `HistoricalAddressInvoices` (
  `InvoiceDataId` varchar(250) NOT NULL,
  `Address` varchar(512) NOT NULL, where (250+512)*4 should stay < 3072. While these widths seem enough according to my first tests, invoices with a big payload could still fail like before increasing the sizes.

`-- MySQL dump 10.16  Distrib 10.2.29-MariaDB, for debian-linux-gnu (aarch64)
--
-- Host: localhost    Database: btcpay
-- ------------------------------------------------------
-- Server version	10.2.29-MariaDB-1:10.2.29+maria~bionic

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `AddressInvoices`
--

DROP TABLE IF EXISTS `AddressInvoices`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `AddressInvoices` (
  `Address` varchar(512) NOT NULL,
  `InvoiceDataId` varchar(255) DEFAULT NULL,
  `CreatedTime` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`Address`),
  KEY `IX_AddressInvoices_InvoiceDataId` (`InvoiceDataId`),
  CONSTRAINT `FK_AddressInvoices_Invoices_InvoiceDataId` FOREIGN KEY (`InvoiceDataId`) REFERENCES `Invoices` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `ApiKeys`
--

DROP TABLE IF EXISTS `ApiKeys`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ApiKeys` (
  `Id` varchar(50) NOT NULL,
  `StoreId` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `IX_ApiKeys_StoreId` (`StoreId`),
  CONSTRAINT `FK_ApiKeys_Stores_StoreId` FOREIGN KEY (`StoreId`) REFERENCES `Stores` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `Apps`
--

DROP TABLE IF EXISTS `Apps`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `Apps` (
  `Id` varchar(255) NOT NULL,
  `AppType` longtext DEFAULT NULL,
  `Created` datetime(6) NOT NULL,
  `Name` longtext DEFAULT NULL,
  `Settings` longtext DEFAULT NULL,
  `StoreDataId` varchar(255) DEFAULT NULL,
  `TagAllInvoices` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`Id`),
  KEY `IX_Apps_StoreDataId` (`StoreDataId`),
  CONSTRAINT `FK_Apps_Stores_StoreDataId` FOREIGN KEY (`StoreDataId`) REFERENCES `Stores` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `AspNetRoleClaims`
--

DROP TABLE IF EXISTS `AspNetRoleClaims`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `AspNetRoleClaims` (
  `Id` int(11) NOT NULL,
  `ClaimType` longtext DEFAULT NULL,
  `ClaimValue` longtext DEFAULT NULL,
  `RoleId` varchar(255) NOT NULL,
  PRIMARY KEY (`Id`),
  KEY `IX_AspNetRoleClaims_RoleId` (`RoleId`),
  CONSTRAINT `FK_AspNetRoleClaims_AspNetRoles_RoleId` FOREIGN KEY (`RoleId`) REFERENCES `AspNetRoles` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `AspNetRoles`
--

DROP TABLE IF EXISTS `AspNetRoles`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `AspNetRoles` (
  `Id` varchar(255) NOT NULL,
  `ConcurrencyStamp` longtext DEFAULT NULL,
  `Name` varchar(256) DEFAULT NULL,
  `NormalizedName` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE KEY `RoleNameIndex` (`NormalizedName`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `AspNetUserClaims`
--

DROP TABLE IF EXISTS `AspNetUserClaims`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `AspNetUserClaims` (
  `Id` int(11) NOT NULL,
  `ClaimType` longtext DEFAULT NULL,
  `ClaimValue` longtext DEFAULT NULL,
  `UserId` varchar(255) NOT NULL,
  PRIMARY KEY (`Id`),
  KEY `IX_AspNetUserClaims_UserId` (`UserId`),
  CONSTRAINT `FK_AspNetUserClaims_AspNetUsers_UserId` FOREIGN KEY (`UserId`) REFERENCES `AspNetUsers` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `AspNetUserLogins`
--

DROP TABLE IF EXISTS `AspNetUserLogins`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `AspNetUserLogins` (
  `LoginProvider` varchar(255) NOT NULL,
  `ProviderKey` varchar(255) NOT NULL,
  `ProviderDisplayName` longtext DEFAULT NULL,
  `UserId` varchar(255) NOT NULL,
  PRIMARY KEY (`LoginProvider`,`ProviderKey`),
  KEY `IX_AspNetUserLogins_UserId` (`UserId`),
  CONSTRAINT `FK_AspNetUserLogins_AspNetUsers_UserId` FOREIGN KEY (`UserId`) REFERENCES `AspNetUsers` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `AspNetUserRoles`
--

DROP TABLE IF EXISTS `AspNetUserRoles`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `AspNetUserRoles` (
  `UserId` varchar(255) NOT NULL,
  `RoleId` varchar(255) NOT NULL,
  PRIMARY KEY (`UserId`,`RoleId`),
  KEY `IX_AspNetUserRoles_RoleId` (`RoleId`),
  CONSTRAINT `FK_AspNetUserRoles_AspNetRoles_RoleId` FOREIGN KEY (`RoleId`) REFERENCES `AspNetRoles` (`Id`) ON DELETE CASCADE,
  CONSTRAINT `FK_AspNetUserRoles_AspNetUsers_UserId` FOREIGN KEY (`UserId`) REFERENCES `AspNetUsers` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `AspNetUserTokens`
--

DROP TABLE IF EXISTS `AspNetUserTokens`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `AspNetUserTokens` (
  `UserId` varchar(255) NOT NULL,
  `LoginProvider` varchar(255) NOT NULL,
  `Name` varchar(255) NOT NULL,
  `Value` longtext DEFAULT NULL,
  PRIMARY KEY (`UserId`,`LoginProvider`,`Name`),
  CONSTRAINT `FK_AspNetUserTokens_AspNetUsers_UserId` FOREIGN KEY (`UserId`) REFERENCES `AspNetUsers` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `AspNetUsers`
--

DROP TABLE IF EXISTS `AspNetUsers`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `AspNetUsers` (
  `Id` varchar(255) NOT NULL,
  `AccessFailedCount` int(11) NOT NULL,
  `ConcurrencyStamp` longtext DEFAULT NULL,
  `Email` varchar(256) DEFAULT NULL,
  `EmailConfirmed` bit(1) NOT NULL,
  `LockoutEnabled` bit(1) NOT NULL,
  `LockoutEnd` datetime(6) DEFAULT NULL,
  `NormalizedEmail` varchar(256) DEFAULT NULL,
  `NormalizedUserName` varchar(256) DEFAULT NULL,
  `PasswordHash` longtext DEFAULT NULL,
  `PhoneNumber` longtext DEFAULT NULL,
  `PhoneNumberConfirmed` bit(1) NOT NULL,
  `SecurityStamp` longtext DEFAULT NULL,
  `TwoFactorEnabled` bit(1) NOT NULL,
  `UserName` varchar(256) DEFAULT NULL,
  `RequiresEmailConfirmation` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `UserNameIndex` (`NormalizedUserName`),
  KEY `EmailIndex` (`NormalizedEmail`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `Files`
--

DROP TABLE IF EXISTS `Files`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `Files` (
  `Id` varchar(255) NOT NULL,
  `FileName` longtext DEFAULT NULL,
  `StorageFileName` longtext DEFAULT NULL,
  `Timestamp` datetime(6) NOT NULL,
  `ApplicationUserId` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `IX_Files_ApplicationUserId` (`ApplicationUserId`),
  CONSTRAINT `FK_Files_AspNetUsers_ApplicationUserId` FOREIGN KEY (`ApplicationUserId`) REFERENCES `AspNetUsers` (`Id`) ON DELETE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `HistoricalAddressInvoices`
--

DROP TABLE IF EXISTS `HistoricalAddressInvoices`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `HistoricalAddressInvoices` (
  `InvoiceDataId` varchar(250) NOT NULL,
  `Address` varchar(512) NOT NULL,
  `Assigned` datetime(6) NOT NULL,
  `UnAssigned` datetime(6) DEFAULT NULL,
  `CryptoCode` longtext DEFAULT NULL,
  PRIMARY KEY (`InvoiceDataId`,`Address`),
  CONSTRAINT `FK_HistoricalAddressInvoices_Invoices_InvoiceDataId` FOREIGN KEY (`InvoiceDataId`) REFERENCES `Invoices` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `InvoiceEvents`
--

DROP TABLE IF EXISTS `InvoiceEvents`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `InvoiceEvents` (
  `InvoiceDataId` varchar(255) NOT NULL,
  `UniqueId` varchar(255) NOT NULL,
  `Message` longtext DEFAULT NULL,
  `Timestamp` datetime(6) NOT NULL,
  PRIMARY KEY (`InvoiceDataId`,`UniqueId`),
  CONSTRAINT `FK_InvoiceEvents_Invoices_InvoiceDataId` FOREIGN KEY (`InvoiceDataId`) REFERENCES `Invoices` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `Invoices`
--

DROP TABLE IF EXISTS `Invoices`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `Invoices` (
  `Id` varchar(255) NOT NULL,
  `Blob` longblob DEFAULT NULL,
  `Created` datetime(6) NOT NULL,
  `CustomerEmail` longtext DEFAULT NULL,
  `ExceptionStatus` longtext DEFAULT NULL,
  `ItemCode` longtext DEFAULT NULL,
  `OrderId` longtext DEFAULT NULL,
  `Status` longtext DEFAULT NULL,
  `StoreDataId` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `IX_Invoices_StoreDataId` (`StoreDataId`),
  CONSTRAINT `FK_Invoices_Stores_StoreDataId` FOREIGN KEY (`StoreDataId`) REFERENCES `Stores` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `PairedSINData`
--

DROP TABLE IF EXISTS `PairedSINData`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `PairedSINData` (
  `Id` varchar(255) NOT NULL,
  `Label` longtext DEFAULT NULL,
  `PairingTime` datetime(6) NOT NULL,
  `SIN` varchar(255) DEFAULT NULL,
  `StoreDataId` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `IX_PairedSINData_SIN` (`SIN`),
  KEY `IX_PairedSINData_StoreDataId` (`StoreDataId`),
  CONSTRAINT `FK_PairedSINData_Stores_StoreDataId` FOREIGN KEY (`StoreDataId`) REFERENCES `Stores` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `PairingCodes`
--

DROP TABLE IF EXISTS `PairingCodes`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `PairingCodes` (
  `Id` varchar(255) NOT NULL,
  `DateCreated` datetime(6) NOT NULL,
  `Expiration` datetime(6) NOT NULL,
  `Facade` longtext DEFAULT NULL,
  `Label` longtext DEFAULT NULL,
  `SIN` longtext DEFAULT NULL,
  `StoreDataId` longtext DEFAULT NULL,
  `TokenValue` longtext DEFAULT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `PaymentRequests`
--

DROP TABLE IF EXISTS `PaymentRequests`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `PaymentRequests` (
  `Id` varchar(255) NOT NULL,
  `StoreDataId` varchar(255) DEFAULT NULL,
  `Status` int(11) NOT NULL,
  `Blob` longblob DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `IX_PaymentRequests_Status` (`Status`),
  KEY `IX_PaymentRequests_StoreDataId` (`StoreDataId`),
  CONSTRAINT `FK_PaymentRequests_Stores_StoreDataId` FOREIGN KEY (`StoreDataId`) REFERENCES `Stores` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `Payments`
--

DROP TABLE IF EXISTS `Payments`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `Payments` (
  `Id` varchar(512) NOT NULL,
  `Blob` longblob DEFAULT NULL,
  `InvoiceDataId` varchar(255) DEFAULT NULL,
  `Accounted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`Id`),
  KEY `IX_Payments_InvoiceDataId` (`InvoiceDataId`),
  CONSTRAINT `FK_Payments_Invoices_InvoiceDataId` FOREIGN KEY (`InvoiceDataId`) REFERENCES `Invoices` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `PendingInvoices`
--

DROP TABLE IF EXISTS `PendingInvoices`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `PendingInvoices` (
  `Id` varchar(255) NOT NULL,
  PRIMARY KEY (`Id`),
  CONSTRAINT `FK_PendingInvoices_Invoices_Id` FOREIGN KEY (`Id`) REFERENCES `Invoices` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `RefundAddresses`
--

DROP TABLE IF EXISTS `RefundAddresses`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `RefundAddresses` (
  `Id` varchar(255) NOT NULL,
  `Blob` longblob DEFAULT NULL,
  `InvoiceDataId` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `IX_RefundAddresses_InvoiceDataId` (`InvoiceDataId`),
  CONSTRAINT `FK_RefundAddresses_Invoices_InvoiceDataId` FOREIGN KEY (`InvoiceDataId`) REFERENCES `Invoices` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `Settings`
--

DROP TABLE IF EXISTS `Settings`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `Settings` (
  `Id` varchar(255) NOT NULL,
  `Value` longtext DEFAULT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `Stores`
--

DROP TABLE IF EXISTS `Stores`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `Stores` (
  `Id` varchar(255) NOT NULL,
  `DerivationStrategy` longtext DEFAULT NULL,
  `SpeedPolicy` int(11) NOT NULL,
  `StoreCertificate` longblob DEFAULT NULL,
  `StoreName` longtext DEFAULT NULL,
  `StoreWebsite` longtext DEFAULT NULL,
  `StoreBlob` longblob DEFAULT NULL,
  `DerivationStrategies` longtext DEFAULT NULL,
  `DefaultCrypto` longtext DEFAULT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `U2FDevices`
--

DROP TABLE IF EXISTS `U2FDevices`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `U2FDevices` (
  `Id` varchar(255) NOT NULL,
  `Name` longtext DEFAULT NULL,
  `KeyHandle` longblob NOT NULL,
  `PublicKey` longblob NOT NULL,
  `AttestationCert` longblob NOT NULL,
  `Counter` int(11) NOT NULL,
  `ApplicationUserId` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `IX_U2FDevices_ApplicationUserId` (`ApplicationUserId`),
  CONSTRAINT `FK_U2FDevices_AspNetUsers_ApplicationUserId` FOREIGN KEY (`ApplicationUserId`) REFERENCES `AspNetUsers` (`Id`) ON DELETE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `UserStore`
--

DROP TABLE IF EXISTS `UserStore`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `UserStore` (
  `ApplicationUserId` varchar(255) NOT NULL,
  `StoreDataId` varchar(255) NOT NULL,
  `Role` longtext DEFAULT NULL,
  PRIMARY KEY (`ApplicationUserId`,`StoreDataId`),
  KEY `IX_UserStore_StoreDataId` (`StoreDataId`),
  CONSTRAINT `FK_UserStore_AspNetUsers_ApplicationUserId` FOREIGN KEY (`ApplicationUserId`) REFERENCES `AspNetUsers` (`Id`) ON DELETE CASCADE,
  CONSTRAINT `FK_UserStore_Stores_StoreDataId` FOREIGN KEY (`StoreDataId`) REFERENCES `Stores` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `__EFMigrationsHistory`
--

DROP TABLE IF EXISTS `__EFMigrationsHistory`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `__EFMigrationsHistory` (
  `MigrationId` varchar(95) NOT NULL,
  `ProductVersion` varchar(32) NOT NULL,
  PRIMARY KEY (`MigrationId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping events for database 'btcpay'
--

--
-- Dumping routines for database 'btcpay'
--
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2020-02-16 18:02:22
`

**Comment by pavlenex** [comment]
@NicolasDorier ^

**Comment by NicolasDorier** [comment]
@ketominer so if I understand, there is nothing for me to do on master now?

**Pull request merged**
