### PR TITLE
Improve section spacings on manage store page

### PR DESCRIPTION
**Pull request by dennisreimann**
Found this spacing issue and used it as areason to improve the spacing of all the sections on the Manage Store page:

spacing

Most of the line changes are caused by removing outer divs, nevertheless please check that I've not broken something I've maybe overlooked here.

The page looks cleaner now and imho the structure of the sections is better this way.

fullpage

### CODE REVIEW

**Comment by britttttk** [comment]
ACK

**Comment by pavlenex** [comment]
Merging this PR now blocks stores from being created with the following error:
```
btcpayserver\BTCPayServer\Views\Stores\UpdateStore.cshtml

    'StoreViewModel' does not contain a definition for 'PayJoinEnabled' and no accessible extension method 'PayJoinEnabled' accepting a first argument of type 'StoreViewModel' could be found (are you missing a using directive or an assembly reference?)

                        <input asp-for="PayJoinEnabled" type="checkbox" class="form-check-input"/>

'StoreViewModel' does not contain a definition for 'PayJoinEnabled' and no accessible extension method 'PayJoinEnabled' accepting a first argument of type 'StoreViewModel' could be found (are you missing a using directive or an assembly reference?)

                        <label asp-for="PayJoinEnabled" class="form-check-label"></label>

'StoreViewModel' does not contain a definition for 'PayJoinEnabled' and no accessible extension method 'PayJoinEnabled' accepting a first argument of type 'StoreViewModel' could be found (are you missing a using directive or an assembly reference?)

                            <span asp-validation-for="PayJoinEnabled" class="text-danger"></span>

```

**Comment by dennisreimann** [comment]
@pavlenex did `dotnet restore` resolve this for you?

**Comment by pavlenex** [comment]
Build-> Clean Solution and re-building helped. It was on my end.

**Pull request merged**
